-- ─────────────────────────────────────────────────────────────────────────────
-- Vim's HMS — Phase 5, RC-003: the tariff engine
--
-- `docs/prompts/phase-05-billing-rcm.md` §5.1 in tables. Twelve of them, all in
-- schema `mdm`, all prefixed `tariff_`. This is the FIRST module of Phase 5 and
-- the prompt is explicit about why: "A single `resolve(service, payer, class,
-- date, branch)` API that **every** bill line calls". A billing module written
-- before its pricing authority acquires a rate column somebody types into, and
-- from then on the hospital has two prices for one service.
--
-- Generated by `prisma migrate diff --from-url`, then post-processed to strip
-- the thirty-seven DropIndex statements Prisma emits for hand-written SQL it
-- cannot represent — the same hazard the Phase-4 migration documents. Nothing
-- below the generated section is Prisma's.
--
-- Read the four sections at the foot of this file in this order:
--   §A  monthly partitioning of the change log, and why it is append-only
--   §B  row-level security — every new table, no exceptions
--   §C  the constraints that carry the guarantees RC-003 §5 makes:
--         C.1  ONE published version per plan per instant (exclusion constraint)
--         C.2  a published version is IMMUTABLE (trigger)
--         C.3  deterministic resolution: one rate per service/class/band
--         C.4  a package's component split totals 100
--         C.5  a taxable item must carry a GST rate and an HSN/SAC
--         C.6  min ≤ base ≤ max, when the guard rails are set
--   §D  grants, and the append-only revoke on the change log
-- ─────────────────────────────────────────────────────────────────────────────

-- CreateEnum
CREATE TYPE "mdm"."TariffPlanType" AS ENUM ('self_pay', 'corporate', 'tpa', 'insurer', 'government_scheme', 'staff', 'camp');

-- CreateEnum
CREATE TYPE "mdm"."TariffPlanScope" AS ENUM ('branch', 'hospital', 'group');

-- CreateEnum
CREATE TYPE "mdm"."TariffPlanStatus" AS ENUM ('active', 'inactive');

-- CreateEnum
CREATE TYPE "mdm"."TariffVersionStatus" AS ENUM ('draft', 'pending_approval', 'approved', 'published', 'superseded', 'withdrawn');

-- CreateEnum
CREATE TYPE "mdm"."TariffTimeBand" AS ENUM ('normal', 'after_hours', 'night', 'holiday', 'emergency');

-- CreateEnum
CREATE TYPE "mdm"."TariffTaxTreatment" AS ENUM ('exempt', 'taxable', 'nil_rated');

-- CreateEnum
CREATE TYPE "mdm"."TariffDiscountScope" AS ENUM ('all', 'department', 'service_group', 'service');

-- CreateEnum
CREATE TYPE "mdm"."TariffDiscountType" AS ENUM ('pct', 'amount', 'formula');

-- CreateEnum
CREATE TYPE "mdm"."TariffExcessRule" AS ENUM ('itemise', 'absorb', 'cap_alert');

-- CreateEnum
CREATE TYPE "mdm"."TariffSheetStatus" AS ENUM ('uploaded', 'mapping', 'review', 'approved', 'published', 'rejected');

-- CreateEnum
CREATE TYPE "mdm"."TariffMatchMethod" AS ENUM ('code', 'rohini', 'fuzzy', 'prior', 'manual');

-- CreateEnum
CREATE TYPE "mdm"."TariffRowDecision" AS ENUM ('accept', 'edit', 'reject', 'pending');

-- CreateEnum
CREATE TYPE "mdm"."TariffSchemeSource" AS ENUM ('pmjay_hbp', 'cghs', 'echs', 'esic', 'state', 'custom');

-- CreateEnum
CREATE TYPE "mdm"."TariffChangeSource" AS ENUM ('manual', 'bulk', 'import', 'formula', 'scheme_import');

-- CreateEnum
CREATE TYPE "mdm"."TariffMissingRateStatus" AS ENUM ('open', 'priced', 'waived');

-- AlterTable
ALTER TABLE "queue"."queue_definitions" ALTER COLUMN "reset_time" SET DEFAULT '00:00:00'::time;

-- CreateTable
CREATE TABLE "mdm"."tariff_plans" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "code" VARCHAR(32) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "plan_type" "mdm"."TariffPlanType" NOT NULL,
    "currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "payer_id" UUID,
    "scheme_id" UUID,
    "corporate_id" UUID,
    "scope" "mdm"."TariffPlanScope" NOT NULL DEFAULT 'hospital',
    "derived_from_plan_id" UUID,
    "derivation_formula" JSONB,
    "rounding_rule" JSONB NOT NULL DEFAULT '{"mode":"half_up","decimals":2}',
    "priority" SMALLINT NOT NULL DEFAULT 0,
    "is_default_self_pay" BOOLEAN NOT NULL DEFAULT false,
    "is_rate_editable" BOOLEAN NOT NULL DEFAULT true,
    "status" "mdm"."TariffPlanStatus" NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "tariff_plans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_versions" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "plan_id" UUID NOT NULL,
    "version_no" INTEGER NOT NULL,
    "effective_from" DATE NOT NULL,
    "effective_to" DATE,
    "status" "mdm"."TariffVersionStatus" NOT NULL DEFAULT 'draft',
    "basis" JSONB,
    "change_note" TEXT,
    "simulation_result" JSONB,
    "approval_id" UUID,
    "submitted_by" UUID,
    "submitted_at" TIMESTAMPTZ(6),
    "approved_by" UUID,
    "approved_at" TIMESTAMPTZ(6),
    "published_by" UUID,
    "published_at" TIMESTAMPTZ(6),
    "withdrawn_by" UUID,
    "withdrawn_at" TIMESTAMPTZ(6),
    "withdraw_reason" TEXT,
    "source_file_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "tariff_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_items" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "version_id" UUID NOT NULL,
    "service_id" UUID NOT NULL,
    "bed_class_id" UUID,
    "time_band" "mdm"."TariffTimeBand",
    "unit" VARCHAR(32) NOT NULL DEFAULT 'each',
    "base_rate" DECIMAL(14,2) NOT NULL,
    "min_rate" DECIMAL(14,2),
    "max_rate" DECIMAL(14,2),
    "hsn_sac" VARCHAR(16),
    "tax_treatment" "mdm"."TariffTaxTreatment" NOT NULL DEFAULT 'exempt',
    "gst_rate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "payer_code" VARCHAR(64),
    "payer_service_name" VARCHAR(255),
    "cost_amount" DECIMAL(14,2),
    "revenue_head_id" UUID,
    "doctor_share_rule_id" UUID,
    "is_negotiable" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "tariff_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_packages" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "version_id" UUID NOT NULL,
    "package_id" UUID NOT NULL,
    "bed_class_id" UUID,
    "package_rate" DECIMAL(14,2) NOT NULL,
    "cap_rules" JSONB NOT NULL DEFAULT '{}',
    "exclusions" JSONB NOT NULL DEFAULT '[]',
    "excess_rule" "mdm"."TariffExcessRule" NOT NULL DEFAULT 'cap_alert',
    "component_split" JSONB NOT NULL DEFAULT '{}',
    "pre_hosp_days" INTEGER NOT NULL DEFAULT 0,
    "post_hosp_days" INTEGER NOT NULL DEFAULT 0,
    "scheme_package_code" VARCHAR(64),
    "nabh_multiplier" DECIMAL(5,3),
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "tariff_packages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_discount_rules" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "plan_id" UUID NOT NULL,
    "version_id" UUID,
    "scope" "mdm"."TariffDiscountScope" NOT NULL DEFAULT 'all',
    "target_id" UUID,
    "discount_type" "mdm"."TariffDiscountType" NOT NULL,
    "value" DECIMAL(14,4) NOT NULL,
    "applies_to" VARCHAR(16) NOT NULL DEFAULT 'gross',
    "excluded_item_types" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "volume_tiers" JSONB,
    "cap_amount" DECIMAL(14,2),
    "effective_from" DATE NOT NULL,
    "effective_to" DATE,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "tariff_discount_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_payer_sheets" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "payer_id" UUID NOT NULL,
    "empanelment_id" UUID,
    "file_id" UUID NOT NULL,
    "template_id" UUID,
    "uploaded_by" UUID NOT NULL,
    "uploaded_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rows_total" INTEGER NOT NULL DEFAULT 0,
    "rows_matched" INTEGER NOT NULL DEFAULT 0,
    "rows_unmatched" INTEGER NOT NULL DEFAULT 0,
    "status" "mdm"."TariffSheetStatus" NOT NULL DEFAULT 'uploaded',
    "version_id" UUID,
    "diff_report_file_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "tariff_payer_sheets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_sheet_rows" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "sheet_id" UUID NOT NULL,
    "row_no" INTEGER NOT NULL,
    "payer_code" VARCHAR(64),
    "payer_description" VARCHAR(500),
    "payer_rate" DECIMAL(14,2),
    "bed_class_col" VARCHAR(64),
    "match_service_id" UUID,
    "match_method" "mdm"."TariffMatchMethod",
    "match_score" DECIMAL(5,4),
    "decision" "mdm"."TariffRowDecision" NOT NULL DEFAULT 'pending',
    "edited_rate" DECIMAL(14,2),
    "remarks" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "tariff_sheet_rows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_scheme_imports" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "scheme_id" UUID NOT NULL,
    "circular_ref" VARCHAR(128) NOT NULL,
    "circular_date" DATE NOT NULL,
    "source" "mdm"."TariffSchemeSource" NOT NULL,
    "file_id" UUID,
    "packages_added" INTEGER NOT NULL DEFAULT 0,
    "packages_removed" INTEGER NOT NULL DEFAULT 0,
    "packages_repriced" INTEGER NOT NULL DEFAULT 0,
    "version_id" UUID,
    "diff_file_id" UUID,
    "imported_by" UUID NOT NULL,
    "imported_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tariff_scheme_imports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_change_log" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "version_id" UUID NOT NULL,
    "item_id" UUID,
    "package_id" UUID,
    "service_id" UUID,
    "field" VARCHAR(64) NOT NULL,
    "old_value" TEXT,
    "new_value" TEXT,
    "changed_by" UUID NOT NULL,
    "changed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" TEXT,
    "approval_id" UUID,
    "source" "mdm"."TariffChangeSource" NOT NULL DEFAULT 'manual',

    CONSTRAINT "tariff_change_log_pkey" PRIMARY KEY ("id","changed_at")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_missing_rates" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "service_id" UUID NOT NULL,
    "plan_id" UUID,
    "bed_class_id" UUID,
    "first_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "occurrences" INTEGER NOT NULL DEFAULT 1,
    "sample_bill_line_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "status" "mdm"."TariffMissingRateStatus" NOT NULL DEFAULT 'open',
    "resolved_by" UUID,
    "resolved_at" TIMESTAMPTZ(6),
    "resolution_note" TEXT,

    CONSTRAINT "tariff_missing_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_rate_cards" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "version_id" UUID NOT NULL,
    "language" VARCHAR(16) NOT NULL DEFAULT 'en-IN',
    "file_id" UUID,
    "published_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_by" UUID NOT NULL,
    "display_locations" TEXT[] DEFAULT ARRAY[]::TEXT[],

    CONSTRAINT "tariff_rate_cards_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mdm"."tariff_benchmarks" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "service_id" UUID NOT NULL,
    "source_name" VARCHAR(200) NOT NULL,
    "peer_rate" DECIMAL(14,2) NOT NULL,
    "city" VARCHAR(120),
    "as_of" DATE NOT NULL,
    "file_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,

    CONSTRAINT "tariff_benchmarks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "tariff_plans_hospital_id_plan_type_status_idx" ON "mdm"."tariff_plans"("hospital_id", "plan_type", "status");

-- CreateIndex
CREATE INDEX "tariff_plans_hospital_id_payer_id_idx" ON "mdm"."tariff_plans"("hospital_id", "payer_id");

-- CreateIndex
CREATE UNIQUE INDEX "tariff_plans_hospital_id_branch_id_code_key" ON "mdm"."tariff_plans"("hospital_id", "branch_id", "code");

-- CreateIndex
CREATE INDEX "tariff_versions_hospital_id_plan_id_effective_from_idx" ON "mdm"."tariff_versions"("hospital_id", "plan_id", "effective_from" DESC);

-- CreateIndex
CREATE INDEX "tariff_versions_hospital_id_status_idx" ON "mdm"."tariff_versions"("hospital_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "tariff_versions_plan_id_version_no_key" ON "mdm"."tariff_versions"("plan_id", "version_no");

-- CreateIndex
CREATE INDEX "tariff_items_hospital_id_service_id_version_id_idx" ON "mdm"."tariff_items"("hospital_id", "service_id", "version_id");

-- CreateIndex
CREATE INDEX "tariff_items_version_id_bed_class_id_idx" ON "mdm"."tariff_items"("version_id", "bed_class_id");

-- CreateIndex
CREATE INDEX "tariff_packages_hospital_id_package_id_idx" ON "mdm"."tariff_packages"("hospital_id", "package_id");

-- CreateIndex
CREATE UNIQUE INDEX "tariff_packages_version_id_package_id_bed_class_id_key" ON "mdm"."tariff_packages"("version_id", "package_id", "bed_class_id");

-- CreateIndex
CREATE INDEX "tariff_discount_rules_hospital_id_plan_id_effective_from_idx" ON "mdm"."tariff_discount_rules"("hospital_id", "plan_id", "effective_from" DESC);

-- CreateIndex
CREATE INDEX "tariff_payer_sheets_hospital_id_payer_id_status_idx" ON "mdm"."tariff_payer_sheets"("hospital_id", "payer_id", "status");

-- CreateIndex
CREATE INDEX "tariff_sheet_rows_hospital_id_sheet_id_decision_idx" ON "mdm"."tariff_sheet_rows"("hospital_id", "sheet_id", "decision");

-- CreateIndex
CREATE UNIQUE INDEX "tariff_sheet_rows_sheet_id_row_no_key" ON "mdm"."tariff_sheet_rows"("sheet_id", "row_no");

-- CreateIndex
CREATE INDEX "tariff_scheme_imports_hospital_id_scheme_id_circular_date_idx" ON "mdm"."tariff_scheme_imports"("hospital_id", "scheme_id", "circular_date" DESC);

-- CreateIndex
CREATE INDEX "tariff_change_log_hospital_id_version_id_changed_at_idx" ON "mdm"."tariff_change_log"("hospital_id", "version_id", "changed_at" DESC);

-- CreateIndex
CREATE INDEX "tariff_change_log_hospital_id_service_id_changed_at_idx" ON "mdm"."tariff_change_log"("hospital_id", "service_id", "changed_at" DESC);

-- CreateIndex
CREATE INDEX "tariff_missing_rates_hospital_id_status_last_seen_at_idx" ON "mdm"."tariff_missing_rates"("hospital_id", "status", "last_seen_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "tariff_missing_rates_hospital_id_branch_id_service_id_plan__key" ON "mdm"."tariff_missing_rates"("hospital_id", "branch_id", "service_id", "plan_id", "bed_class_id");

-- CreateIndex
CREATE INDEX "tariff_rate_cards_hospital_id_branch_id_published_at_idx" ON "mdm"."tariff_rate_cards"("hospital_id", "branch_id", "published_at" DESC);

-- CreateIndex
CREATE INDEX "tariff_benchmarks_hospital_id_service_id_as_of_idx" ON "mdm"."tariff_benchmarks"("hospital_id", "service_id", "as_of" DESC);

-- CreateIndex
CREATE INDEX "stock_ledger_hospital_id_patient_id_moved_at_idx" ON "inventory"."stock_ledger"("hospital_id", "patient_id", "moved_at");

-- AddForeignKey
ALTER TABLE "mdm"."tariff_versions" ADD CONSTRAINT "tariff_versions_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "mdm"."tariff_plans"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mdm"."tariff_items" ADD CONSTRAINT "tariff_items_version_id_fkey" FOREIGN KEY ("version_id") REFERENCES "mdm"."tariff_versions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mdm"."tariff_packages" ADD CONSTRAINT "tariff_packages_version_id_fkey" FOREIGN KEY ("version_id") REFERENCES "mdm"."tariff_versions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mdm"."tariff_discount_rules" ADD CONSTRAINT "tariff_discount_rules_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "mdm"."tariff_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mdm"."tariff_sheet_rows" ADD CONSTRAINT "tariff_sheet_rows_sheet_id_fkey" FOREIGN KEY ("sheet_id") REFERENCES "mdm"."tariff_payer_sheets"("id") ON DELETE CASCADE ON UPDATE CASCADE;



-- ═════════════════════════════════════════════════════════════════════════════
-- §A. THE CHANGE LOG: MONTHLY PARTITIONS, APPEND ONLY
--
-- `mdm.tariff_change_log` is the audit of record for pricing. RC-003 §5 keeps it
-- 8 years for GST and contract audit, and a hospital repricing a few thousand
-- services a year fills it steadily. Partitioned monthly so the eventual purge
-- is a DETACH rather than a table rewrite, and so a query for "what changed in
-- March" reads one partition.
--
-- Prisma cannot express declarative partitioning, so the table it created is
-- replaced here. Doing this in the same migration that created it is safe
-- precisely because nothing has written to it yet.
-- ═════════════════════════════════════════════════════════════════════════════
DROP TABLE IF EXISTS "mdm"."tariff_change_log";

CREATE TABLE "mdm"."tariff_change_log" (
  "id"          UUID NOT NULL,
  "hospital_id" UUID NOT NULL,
  "version_id"  UUID NOT NULL,
  "item_id"     UUID,
  "package_id"  UUID,
  "service_id"  UUID,
  "field"       VARCHAR(64) NOT NULL,
  "old_value"   TEXT,
  "new_value"   TEXT,
  "changed_by"  UUID NOT NULL,
  "changed_at"  TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "reason"      TEXT,
  "approval_id" UUID,
  "source"      "mdm"."TariffChangeSource" NOT NULL DEFAULT 'manual',
  CONSTRAINT "tariff_change_log_pkey" PRIMARY KEY ("id", "changed_at")
) PARTITION BY RANGE ("changed_at");

CREATE INDEX "tariff_change_log_hospital_id_version_id_changed_at_idx"
  ON "mdm"."tariff_change_log" ("hospital_id", "version_id", "changed_at" DESC);
CREATE INDEX "tariff_change_log_hospital_id_service_id_changed_at_idx"
  ON "mdm"."tariff_change_log" ("hospital_id", "service_id", "changed_at" DESC);

-- Twelve months forward plus a default. The worker's partition-maintenance job
-- (ADR-0008) keeps the window rolling; this is only the initial set so the
-- table is writable the moment the migration finishes.
DO $$
DECLARE
  v_start date := date_trunc('month', now())::date - interval '1 month';
  v_i int;
  v_from date;
  v_to date;
BEGIN
  FOR v_i IN 0..12 LOOP
    v_from := (v_start + (v_i || ' months')::interval)::date;
    v_to   := (v_start + ((v_i + 1) || ' months')::interval)::date;
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS mdm.%I PARTITION OF mdm.tariff_change_log FOR VALUES FROM (%L) TO (%L)',
      'tariff_change_log_' || to_char(v_from, 'YYYYMM'), v_from, v_to
    );
  END LOOP;
END
$$;

CREATE TABLE IF NOT EXISTS "mdm"."tariff_change_log_default"
  PARTITION OF "mdm"."tariff_change_log" DEFAULT;

COMMENT ON TABLE "mdm"."tariff_change_log_default" IS
  'Safety net only. A non-empty default partition is an alertable anomaly (docs/07 §6), never a normal state.';


-- ═════════════════════════════════════════════════════════════════════════════
-- §B. ROW-LEVEL SECURITY
--
-- Same generic loop the Phase-1..4 migrations use: it finds every table in the
-- tenant schemas that has no `tenant_isolation` policy yet and applies one
-- derived from the columns actually present. Reused verbatim rather than
-- hand-listing the twelve new tables, because a hand-written list is a list
-- somebody forgets to add the thirteenth table to — and an unpoliced table in a
-- policed schema is not an omission, it is a cross-tenant read.
-- ═════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
  r record;
  v_has_hospital boolean;
  v_hospital_null boolean;
  v_has_branch boolean;
  v_using text;
  v_check text;
  v_count int := 0;
BEGIN
  FOR r IN
    SELECT n.nspname AS schema_name, c.relname AS table_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN ('core', 'mdm', 'patient', 'clinical', 'lab', 'rad', 'pharmacy', 'inventory', 'finance', 'queue', 'engage', 'billing', 'integration')
      AND c.relkind IN ('r', 'p')
      AND c.relispartition = false
      AND c.relname NOT LIKE '\_prisma%'
      AND c.relname <> 'cdss_safety_floor'
      AND NOT EXISTS (
        SELECT 1 FROM pg_policy p
        WHERE p.polrelid = c.oid AND p.polname = 'tenant_isolation'
      )
    ORDER BY n.nspname, c.relname
  LOOP
    SELECT
      count(*) FILTER (WHERE column_name = 'hospital_id') > 0,
      bool_or(column_name = 'hospital_id' AND is_nullable = 'YES'),
      count(*) FILTER (WHERE column_name = 'branch_id') > 0
    INTO v_has_hospital, v_hospital_null, v_has_branch
    FROM information_schema.columns
    WHERE table_schema = r.schema_name AND table_name = r.table_name;

    EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', r.schema_name, r.table_name);

    IF v_has_hospital AND NOT v_hospital_null THEN
      v_using := 'hospital_id = ANY (core.accessible_hospital_ids())';
      IF v_has_branch THEN
        v_using := v_using || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))';
      END IF;
      v_check := v_using;

    ELSIF v_has_hospital AND v_hospital_null THEN
      v_using := '(hospital_id IS NULL OR hospital_id = ANY (core.accessible_hospital_ids()))';
      IF v_has_branch THEN
        v_using := v_using || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))';
      END IF;
      v_check := 'hospital_id = ANY (core.accessible_hospital_ids())';
      IF v_has_branch THEN
        v_check := v_check || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))';
      END IF;

    ELSE
      v_using := 'false';
      v_check := 'false';
    END IF;

    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I.%I', r.schema_name, r.table_name);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I.%I FOR ALL TO hms_app USING (%s) WITH CHECK (%s)',
      r.schema_name, r.table_name, v_using, v_check
    );

    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_ro ON %I.%I', r.schema_name, r.table_name);
    EXECUTE format(
      'CREATE POLICY tenant_isolation_ro ON %I.%I FOR SELECT TO hms_readonly USING (%s)',
      r.schema_name, r.table_name, v_using
    );

    v_count := v_count + 1;
  END LOOP;

  RAISE NOTICE 'Row-level security enabled with tenant policies on % new tables', v_count;
END
$$;

-- Assert it here rather than trusting the integration suite to notice later.
-- A migration that half-applied its own security is worse than one that failed.
DO $$
DECLARE
  v_missing text;
BEGIN
  SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ')
  INTO v_missing
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'mdm'
    AND c.relname LIKE 'tariff\_%'
    AND c.relkind IN ('r', 'p')
    AND c.relispartition = false
    AND (
      NOT c.relrowsecurity
      OR NOT EXISTS (SELECT 1 FROM pg_policy p WHERE p.polrelid = c.oid AND p.polname = 'tenant_isolation')
    );

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'RC-003 tables without RLS or without a tenant policy: %', v_missing;
  END IF;
END
$$;


-- ═════════════════════════════════════════════════════════════════════════════
-- §C. THE CONSTRAINTS RC-003 §5 DEPENDS ON
--
-- Everything here is a guarantee the application must not be able to break by
-- forgetting a check. `docs/03` puts invariants in the database wherever the
-- database can hold them, because a service is one refactor away from skipping
-- its own validation and the row it wrote outlives the bug.
-- ═════════════════════════════════════════════════════════════════════════════

-- ── C.1  ONE published version per plan per instant ─────────────────────────
--
-- RC-003 §5, verbatim: "One published version per plan per instant (DB
-- exclusion constraint)." Without it, "which rate applied on the 3rd" has two
-- answers, the resolver picks whichever the planner returned first, and the
-- bill becomes indefensible in exactly the audit that asks.
--
-- `effective_to` is nullable and means open-ended, so it maps to `infinity`.
-- `btree_gist` is required for the `=` half on a uuid and is already installed
-- (infra/docker/postgres/init/01-extensions.sql).
ALTER TABLE "mdm"."tariff_versions"
  ADD CONSTRAINT "tariff_versions_no_overlapping_published"
  EXCLUDE USING gist (
    "plan_id" WITH =,
    daterange("effective_from", "effective_to", '[)') WITH &&
  )
  WHERE (status = 'published');

COMMENT ON CONSTRAINT "tariff_versions_no_overlapping_published" ON "mdm"."tariff_versions" IS
  'RC-003 §5. Two published versions of one plan may never cover the same day: a bill line must have exactly one applicable rate, not a race between two.';

-- A version cannot end before it starts.
ALTER TABLE "mdm"."tariff_versions"
  ADD CONSTRAINT "tariff_versions_dates_ordered"
  CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from");


-- ── C.2  a published version is IMMUTABLE ───────────────────────────────────
--
-- RC-003 §5: "A published version is immutable: no updates to `tariff_items` of
-- a published version; changes require a new version (enforced by trigger)."
--
-- This is what makes a ten-revisions-old bill explainable. Every bill line
-- snapshots `tariff_version_id` + `tariff_item_id`; if the item could later be
-- edited, the snapshot would point at a row that no longer says what it said
-- when it priced the line, and "why this price" would answer with today's
-- number for a bill raised two years ago.
CREATE OR REPLACE FUNCTION "mdm".tariff_refuse_published_edit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_status "mdm"."TariffVersionStatus";
  v_version_id uuid;
BEGIN
  v_version_id := COALESCE(NEW.version_id, OLD.version_id);

  SELECT status INTO v_status
  FROM "mdm"."tariff_versions"
  WHERE id = v_version_id;

  -- `superseded` is also frozen: it priced real bills and they must stay
  -- explainable. Only a draft, or a version still awaiting approval, is soft.
  IF v_status IN ('published', 'superseded', 'withdrawn') THEN
    RAISE EXCEPTION
      'Tariff version % is % and is immutable. Create a new version instead (RC-003 §5).',
      v_version_id, v_status
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN COALESCE(NEW, OLD);
END
$$;

CREATE TRIGGER "tariff_items_immutable_when_published"
  BEFORE UPDATE OR DELETE ON "mdm"."tariff_items"
  FOR EACH ROW EXECUTE FUNCTION "mdm".tariff_refuse_published_edit();

CREATE TRIGGER "tariff_packages_immutable_when_published"
  BEFORE UPDATE OR DELETE ON "mdm"."tariff_packages"
  FOR EACH ROW EXECUTE FUNCTION "mdm".tariff_refuse_published_edit();

-- Inserting a row into an already-published version is the same violation
-- wearing a different hat: it changes what that version says.
CREATE TRIGGER "tariff_items_no_insert_when_published"
  BEFORE INSERT ON "mdm"."tariff_items"
  FOR EACH ROW EXECUTE FUNCTION "mdm".tariff_refuse_published_edit();

CREATE TRIGGER "tariff_packages_no_insert_when_published"
  BEFORE INSERT ON "mdm"."tariff_packages"
  FOR EACH ROW EXECUTE FUNCTION "mdm".tariff_refuse_published_edit();


-- ── C.3  deterministic resolution ───────────────────────────────────────────
--
-- One rate per (version, service, bed class, time band). Both discriminators
-- are nullable — "no bed class" and "any time band" are meaningful — and a
-- plain UNIQUE treats each NULL as distinct, so a service could hold two
-- "no bed class, no band" rows and `resolveRate` would return whichever came
-- back first. That is a non-deterministic price, which is the one thing a
-- pricing authority may not be.
CREATE UNIQUE INDEX "uq_tariff_items_resolution"
  ON "mdm"."tariff_items" (
    "version_id",
    "service_id",
    (COALESCE("bed_class_id", '00000000-0000-0000-0000-000000000000'::uuid)),
    (COALESCE("time_band", 'normal'))
  );

COMMENT ON INDEX "mdm"."uq_tariff_items_resolution" IS
  'RC-003 §4. Coalesced because NULL bed class and NULL time band are real values here, and a plain UNIQUE would let a service carry two default rates.';


-- ── C.4  a package''s component split totals 100 ────────────────────────────
--
-- The split allocates one package price across revenue heads. A split that does
-- not add up misallocates revenue silently for as long as nobody reconciles,
-- and the discrepancy surfaces at year end as an unexplained variance rather
-- than as an error at the moment somebody typed it.
CREATE OR REPLACE FUNCTION "mdm".tariff_check_component_split()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_total numeric;
BEGIN
  IF NEW.component_split IS NULL OR NEW.component_split = '{}'::jsonb THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(sum((value #>> '{}')::numeric), 0)
  INTO v_total
  FROM jsonb_each(NEW.component_split);

  IF abs(v_total - 100) > 0.01 THEN
    RAISE EXCEPTION
      'Package component split totals %, not 100 (RC-003 §5).', v_total
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END
$$;

CREATE TRIGGER "tariff_packages_component_split_totals_100"
  BEFORE INSERT OR UPDATE ON "mdm"."tariff_packages"
  FOR EACH ROW EXECUTE FUNCTION "mdm".tariff_check_component_split();

ALTER TABLE "mdm"."tariff_packages"
  ADD CONSTRAINT "tariff_packages_rate_non_negative" CHECK ("package_rate" >= 0);


-- ── C.5  a taxable item must be taxable *somewhere* ─────────────────────────
--
-- RC-003 §5: "HSN/SAC and tax treatment are mandatory on every item; a taxable
-- item with `gst_rate = 0` is rejected." An item marked taxable at 0 % is
-- indistinguishable in the ledger from an exempt one, and the two are different
-- lines on a GST return.
ALTER TABLE "mdm"."tariff_items"
  ADD CONSTRAINT "tariff_items_taxable_needs_rate"
  CHECK ("tax_treatment" <> 'taxable' OR ("gst_rate" > 0 AND "hsn_sac" IS NOT NULL));

ALTER TABLE "mdm"."tariff_items"
  ADD CONSTRAINT "tariff_items_rate_non_negative" CHECK ("base_rate" >= 0);


-- ── C.6  the guard rails, when they are set ─────────────────────────────────
ALTER TABLE "mdm"."tariff_items"
  ADD CONSTRAINT "tariff_items_within_guard_rails"
  CHECK (
    ("min_rate" IS NULL OR "base_rate" >= "min_rate")
    AND ("max_rate" IS NULL OR "base_rate" <= "max_rate")
    AND ("min_rate" IS NULL OR "max_rate" IS NULL OR "min_rate" <= "max_rate")
  );

-- A discount rule cannot end before it starts, and a percentage cannot exceed
-- 100 — a 150 % discount is a refund with extra steps and must not be
-- representable as a rate rule.
ALTER TABLE "mdm"."tariff_discount_rules"
  ADD CONSTRAINT "tariff_discount_rules_dates_ordered"
  CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from");

ALTER TABLE "mdm"."tariff_discount_rules"
  ADD CONSTRAINT "tariff_discount_rules_pct_bounded"
  CHECK ("discount_type" <> 'pct' OR ("value" >= 0 AND "value" <= 100));


-- ═════════════════════════════════════════════════════════════════════════════
-- §D. GRANTS, AND THE APPEND-ONLY REVOKE
-- ═════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
  r record;
  v_count int := 0;
BEGIN
  FOR r IN
    SELECT n.nspname AS schema_name, c.relname AS table_name, c.oid
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'mdm'
      AND c.relkind IN ('r', 'p')
      AND c.relispartition = false
      AND c.relname LIKE 'tariff\_%'
      AND NOT has_table_privilege('hms_app', c.oid, 'SELECT')
  LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I.%I TO hms_app', r.schema_name, r.table_name);
    EXECUTE format('GRANT SELECT ON %I.%I TO hms_readonly', r.schema_name, r.table_name);
    v_count := v_count + 1;
  END LOOP;
  RAISE NOTICE 'Granted application DML on % RC-003 table(s)', v_count;
END
$$;

-- Partitions inherit nothing: grant the change log's children explicitly, and
-- only SELECT + INSERT, which is the whole point of the next statement.
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'mdm'
      AND c.relname LIKE 'tariff\_change\_log%'
      -- Tables and partitions only. `pg_class` also holds this table's indexes,
      -- and GRANT on an index is an error, not a no-op.
      AND c.relkind IN ('r', 'p')
  LOOP
    EXECUTE format('GRANT SELECT, INSERT ON mdm.%I TO hms_app', r.relname);
    EXECUTE format('GRANT SELECT ON mdm.%I TO hms_readonly', r.relname);
    EXECUTE format('REVOKE UPDATE, DELETE ON mdm.%I FROM hms_app', r.relname);
  END LOOP;
END
$$;

-- `mdm.tariff_change_log` is the pricing audit of record: "Never updated, never
-- deleted" (RC-003 §4). The revoke is the control; a service that tries is
-- refused by the database rather than by a code review that did not happen.
REVOKE UPDATE, DELETE ON "mdm"."tariff_change_log" FROM hms_app;

COMMENT ON TABLE "mdm"."tariff_change_log" IS
  'Append-only. Every rate change, retained 8 years for GST and contract audit (RC-003 §4/§5). UPDATE and DELETE are revoked from the application role.';

COMMENT ON TABLE "mdm"."tariff_missing_rates" IS
  'The MISSING_RATE worklist. A rate that cannot be resolved holds the bill line; it is never billed at zero, because a zero is indistinguishable from a free service until the month-end reconciliation fails.';

COMMENT ON TABLE "mdm"."tariff_benchmarks" IS
  'Peer rates for comparison only. There is deliberately no path from this table into rate resolution.';
