/**
 * The 64 system role templates from `docs/05 §System role templates`.
 *
 * `EN-007 §3.3.2`: "**System role templates** (60+ per docs/05) seeded as
 * read-only templates; hospital clones to **custom roles**."
 *
 * A template's permission set is deliberately *thin in Phase 0*. A ward nurse
 * genuinely can do almost nothing yet — there is no MAR, no vitals, no chart —
 * and inflating the list now would produce a role matrix that lies. Each later
 * phase appends the keys its modules register, and `permission-matrix.json`
 * (docs/09 §3.2) turns every such change into a reviewed diff of who can now do
 * what.
 *
 * The home workspace is what `/login` routes to (docs/05 §Login/UX flow).
 */
import type { AbacConditions } from './abac.js';
import { assertRegisteredPermission } from './permissions.js';

export type WorkspaceKey =
  | 'tenant-console'
  | 'admin-console'
  | 'branch-admin'
  | 'clinical-governance'
  | 'department-dashboard'
  | 'doctor-opd'
  | 'ip-rounds'
  | 'er-board'
  | 'ot-schedule'
  | 'anaesthesia-worklist'
  | 'icu-board'
  | 'radiology-reading'
  | 'lab-validation'
  | 'referral-portal'
  | 'vitals-room'
  | 'nursing-station'
  | 'icu-flowsheet'
  | 'triage-board'
  | 'ot-checklist'
  | 'infection-control'
  | 'nursing-command-centre'
  | 'task-list'
  | 'registration'
  | 'call-console'
  | 'cash-counter'
  | 'billing-desk'
  | 'insurance-queue'
  | 'corporate-accounts'
  | 'pharmacy-rx-queue'
  | 'pharmacy-ward-indents'
  | 'pharmacy-admin'
  | 'lab-bench'
  | 'lab-collection'
  | 'lab-qc'
  | 'radiology-modality'
  | 'blood-bank'
  | 'cssd'
  | 'diet-worklist'
  | 'therapy-schedule'
  | 'dialysis-board'
  | 'counselling-sessions'
  | 'mrd-queue'
  | 'stores'
  | 'procurement'
  | 'finance'
  | 'hr'
  | 'biomedical'
  | 'facility'
  | 'housekeeping'
  | 'gate-console'
  | 'ambulance-dispatch'
  | 'kitchen-board'
  | 'quality'
  | 'crm'
  | 'it-console'
  | 'privacy-dashboard'
  | 'audit-workspace'
  | 'patient-portal'
  | 'family-view'
  | 'corporate-portal'
  | 'payer-portal'
  | 'vendor-portal'
  | 'device-display';

export type RoleCategory =
  | 'saas'
  | 'admin'
  | 'medical'
  | 'nursing'
  | 'diagnostics'
  | 'pharmacy'
  | 'therapy'
  | 'records'
  | 'supply'
  | 'finance'
  | 'facilities'
  | 'governance'
  | 'external'
  | 'device';

export interface RoleTemplate {
  /** Stable key. Referenced by SSO group mappings and seeds; never renamed. */
  readonly key: string;
  /** Row number in docs/05 §System role templates, so the mapping is auditable. */
  readonly docsRow: number;
  readonly name: string;
  readonly description: string;
  readonly category: RoleCategory;
  readonly homeWorkspace: WorkspaceKey;
  readonly permissions: readonly string[];
  readonly abacDefaults: AbacConditions;
  /**
   * `docs/04 §2`: "MFA: TOTP mandatory for Admin, Finance, Pharmacy-narcotics,
   * Blood bank, MRD-export, Privacy Officer"; EN-007 §3.4.2 adds Billing,
   * Insurance and IT.
   */
  readonly mfaMandatory: boolean;
  /** Granting this role needs two approvers (EN-007 §5). */
  readonly sensitiveGrant: boolean;
  /** Resident/intern roles: their clinical output needs a consultant co-sign (docs/05 row 14). */
  readonly requiresCoSign: boolean;
}

// ── composable permission bundles ────────────────────────────────────────────

/** What literally every authenticated staff member can do. */
const BASE_STAFF = [
  'org.read',
  'mdm.read',
  'tpl.form.read',
  'lic.entitlement.read',
  'gateway.status.read',
  'print.job.create',
  'print.job.read',
  'wf.request.create',
  'wf.request.read',
  'wf.delegation.manage',
] as const;

/** Anyone who touches a patient. */
const BASE_CLINICAL = [
  ...BASE_STAFF,
  'barcode.scan',
  'tpl.response.write',
  'tpl.response.read',
  'tpl.render',
  'org.patient.locate',
  'org.patient.cross_access',
] as const;

/** Clinicians who may break glass in an emergency (docs/05 §Login: "any clinician"). */
const BREAK_GLASS = ['org.patient.break_glass'] as const;

/** Anyone who signs a clinical document. */
const SIGNS_DOCUMENTS = ['tpl.response.sign', 'tpl.response.amend'] as const;

/** Anyone who approves things. */
const APPROVER = ['wf.decide', 'wf.report.read'] as const;

/** Department heads. */
const HOD_BASE = [
  ...APPROVER,
  'admin.access.approve',
  'admin.access.review',
  'admin.role.read',
  'audit.user.read',
  'mdm.quality.read',
  'notify.report.read',
] as const;

/** Label/wristband printing roles. */
const LABEL_PRINTER = ['barcode.label.print', 'barcode.label.reprint'] as const;

// ── the 64 templates ─────────────────────────────────────────────────────────

const templates: readonly RoleTemplate[] = [
  {
    key: 'super_admin',
    docsRow: 1,
    name: 'Super Admin (SaaS operator)',
    description:
      'The SaaS operator. Manages tenants, plans, licence keys and global masters. Impersonation is time-boxed, read-only by default and audited under both identities.',
    category: 'saas',
    homeWorkspace: 'tenant-console',
    permissions: [
      ...BASE_STAFF,
      'admin.hospital.configure',
      'admin.settings.read',
      'admin.settings.configure',
      'admin.impersonate',
      'admin.status.read',
      'admin.report.read',
      'admin.flags.configure',
      'lic.plan.manage',
      'lic.subscription.manage',
      'lic.subscription.read',
      'lic.override.manage',
      'lic.billing.manage',
      'lic.key.issue',
      'lic.usage.admin',
      'lic.report.admin',
      'dr.status.fleet',
      'security.posture.fleet',
      'ihub.package.manage',
      'tpl.bundle.manage',
      'gateway.product.manage',
    ],
    abacDefaults: { deviceBound: true },
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'hospital_admin',
    docsRow: 2,
    name: 'Hospital Admin / Group Admin',
    description:
      'Owns the tenant control plane: users, roles, settings, masters, branches, feature flags and the audit viewer.',
    category: 'admin',
    homeWorkspace: 'admin-console',
    permissions: [
      ...BASE_STAFF,
      ...APPROVER,
      'admin.hospital.configure',
      'admin.settings.read',
      'admin.settings.configure',
      'admin.calendar.configure',
      'admin.numbering.configure',
      'admin.user.read',
      'admin.user.create',
      'admin.user.update',
      'admin.user.deactivate',
      'admin.user.reset',
      'admin.role.read',
      'admin.role.configure',
      'admin.role.assign',
      'admin.access.approve',
      'admin.access.review',
      'admin.security.configure',
      'admin.session.manage',
      'admin.device.manage',
      'admin.audit.read',
      'admin.flags.configure',
      'admin.licence.read',
      'admin.status.read',
      'admin.report.read',
      'audit.read',
      'audit.user.read',
      'audit.report.read',
      'audit.retention.configure',
      'org.branch.manage',
      'org.branch.onboard',
      'org.registration.manage',
      'org.policy.manage',
      'org.access.manage',
      'org.report.read',
      'org.transfer.manage',
      'wf.matrix.manage',
      'wf.matrix.publish',
      'wf.process.manage',
      'wf.calendar.manage',
      'wf.delegation.admin',
      'wf.bypass',
      'notify.policy.manage',
      'notify.type.manage',
      'notify.admin.read',
      'notify.report.read',
      'mdm.org.propose',
      'mdm.org.approve',
      'mdm.quality.read',
      'mdm.review.manage',
      'mdm.report.read',
      'mdm.sync.manage',
      'tpl.print.publish',
      'tpl.form.publish',
      'tpl.branding.manage',
      'tpl.bundle.manage',
      'lic.subscription.read',
      'lic.subscription.request',
      'lic.usage.read',
      'lic.invoice.read',
      'dr.policy.configure',
      'dr.status.read',
      'dr.restore.approve',
      'dr.downtime.manage',
      'dr.drill.read',
      'sso.breakglass.manage',
      'sso.stepup.configure',
      'sso.report.read',
      'security.posture.read',
      'security.report.read',
      'gateway.client.manage',
      'admin.print.configure',
      'admin.print.read',
    ],
    // No narrowing: a Hospital Admin's reach is set by their branch grants in
    // `org_user_branch_access`, not by an ABAC default (EN-041 §3.7).
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'branch_admin',
    docsRow: 3,
    name: 'Branch Admin',
    description: 'Runs one branch: its configuration, counters, wards and staff. Cannot see another branch.',
    category: 'admin',
    homeWorkspace: 'branch-admin',
    permissions: [
      ...BASE_STAFF,
      ...APPROVER,
      'admin.settings.read',
      'admin.settings.configure',
      'admin.calendar.configure',
      'admin.user.read',
      'admin.user.create',
      'admin.user.update',
      'admin.role.read',
      'admin.role.assign',
      'admin.access.approve',
      'admin.device.manage',
      'admin.status.read',
      'admin.report.read',
      'org.registration.manage',
      'org.master.override',
      'org.transfer.manage',
      'mdm.org.propose',
      'tpl.branding.manage',
      'lic.usage.read',
      'admin.print.configure',
      'admin.print.read',
      'barcode.scheme.configure',
    ],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'medical_superintendent',
    docsRow: 4,
    name: 'Medical Superintendent / Medical Director',
    description:
      'Clinical governance: all clinical read, quality, MLC, mortality review, break-glass review and the final rung of every clinical escalation ladder.',
    category: 'governance',
    homeWorkspace: 'clinical-governance',
    permissions: [
      ...BASE_CLINICAL,
      ...BREAK_GLASS,
      ...APPROVER,
      'audit.read',
      'audit.patient.read',
      'audit.breakglass.review',
      'audit.report.read',
      'admin.role.read',
      'admin.report.read',
      'notify.escalation.read',
      'notify.admin.manage',
      'notify.policy.manage',
      'notify.type.manage',
      'notify.report.read',
      'wf.bypass',
      'wf.audit.read',
      'tpl.form.publish',
      'mdm.clinical.approve',
      'mdm.pharmacy.approve',
      'mdm.emergency_change',
      'org.report.read',
      'security.incident.read',
      'dr.status.read',
    ],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'hod',
    docsRow: 5,
    name: 'HOD (Head of Department)',
    description: 'Department scheduling, approvals and KPIs, scoped to their own department.',
    category: 'medical',
    homeWorkspace: 'department-dashboard',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS, ...HOD_BASE, 'tpl.form.manage'],
    abacDefaults: { ownDepartmentOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'doctor_consultant_opd',
    docsRow: 6,
    name: 'Doctor — Consultant (OPD)',
    description: 'Outpatient consultation, e-prescribing, orders, results, referrals and own earnings.',
    category: 'medical',
    homeWorkspace: 'doctor-opd',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS, 'notify.escalation.read'],
    abacDefaults: { ownPatientsOnly: false, careTeamOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'doctor_ip',
    docsRow: 7,
    name: 'Doctor — Inpatient / Ward',
    description: 'Ward rounds, inpatient orders, notes, discharge and transfers.',
    category: 'medical',
    homeWorkspace: 'ip-rounds',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS, 'notify.escalation.read'],
    abacDefaults: { careTeamOnly: true, assignedWardOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'doctor_emergency',
    docsRow: 8,
    name: 'Doctor — Emergency Physician',
    description: 'Emergency department: triage view, ER orders, MLC registration and admission decisions.',
    category: 'medical',
    homeWorkspace: 'er-board',
    permissions: [
      ...BASE_CLINICAL,
      ...BREAK_GLASS,
      ...SIGNS_DOCUMENTS,
      'notify.escalation.read',
      'barcode.wristband.issue',
      ...LABEL_PRINTER,
    ],
    // Emergency physicians deliberately have no care-team restriction: an ER
    // patient has no care team yet (docs/04 §7, EN-041 §3.4.2 break-glass).
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'surgeon',
    docsRow: 9,
    name: 'Surgeon',
    description: 'OT booking, operation notes, implant capture and surgical consent.',
    category: 'medical',
    homeWorkspace: 'ot-schedule',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS, 'barcode.verify.implant'],
    abacDefaults: { careTeamOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'anaesthetist',
    docsRow: 10,
    name: 'Anaesthetist',
    description: 'Pre-anaesthetic checkup, intra-operative record and PACU.',
    category: 'medical',
    homeWorkspace: 'anaesthesia-worklist',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS],
    abacDefaults: { careTeamOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'intensivist',
    docsRow: 11,
    name: 'Intensivist',
    description: 'ICU flowsheet, ventilator management and severity scores.',
    category: 'medical',
    homeWorkspace: 'icu-board',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS, 'notify.escalation.read'],
    abacDefaults: { assignedWardOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'radiologist',
    docsRow: 12,
    name: 'Radiologist',
    description: 'Reading worklist, PACS viewer, structured reporting and sign-off.',
    category: 'diagnostics',
    homeWorkspace: 'radiology-reading',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS, 'mdm.radiology.propose'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'pathologist',
    docsRow: 13,
    name: 'Pathologist / Lab Director',
    description: 'Result validation, quality control, sign-off and external quality assessment.',
    category: 'diagnostics',
    homeWorkspace: 'lab-validation',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, ...SIGNS_DOCUMENTS, 'mdm.lab.propose', 'mdm.lab.approve'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'resident_doctor',
    docsRow: 14,
    name: 'Resident / Junior Doctor / Intern',
    description:
      'Same clinical surface as a doctor but output requires consultant co-signature, and safety overrides are unavailable.',
    category: 'medical',
    homeWorkspace: 'doctor-opd',
    // Deliberately NOT granted break-glass or any `*.override` key: docs/06 §5.2 #16
    // says the allergy hard-stop "disables for roles without `override` (residents)".
    permissions: [...BASE_CLINICAL],
    abacDefaults: { careTeamOnly: true, ownDepartmentOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: true,
  },
  {
    key: 'referring_doctor',
    docsRow: 15,
    name: 'Visiting / Referring Doctor',
    description: 'External clinician with read access to the patients they referred, through the referral portal.',
    category: 'external',
    homeWorkspace: 'referral-portal',
    permissions: ['org.read', 'mdm.read', 'tpl.form.read', 'tpl.response.read', 'org.patient.locate'],
    abacDefaults: { ownPatientsOnly: true, dataClassMasks: ['aadhaar', 'address'] },
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'nurse_opd',
    docsRow: 16,
    name: 'Nurse — OPD / Vitals',
    description: 'Vitals room, injections and dressings.',
    category: 'nursing',
    homeWorkspace: 'vitals-room',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER, 'barcode.verify.sample'],
    abacDefaults: { ownDepartmentOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'nurse_ward',
    docsRow: 17,
    name: 'Nurse — Ward',
    description: 'Nursing station: vitals, medication administration, notes, handover and ward indents.',
    category: 'nursing',
    homeWorkspace: 'nursing-station',
    permissions: [
      ...BASE_CLINICAL,
      ...LABEL_PRINTER,
      'barcode.wristband.issue',
      'barcode.verify.mar',
      'barcode.verify.sample',
      'notify.escalation.read',
    ],
    abacDefaults: { assignedWardOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'nurse_icu',
    docsRow: 18,
    name: 'Nurse — ICU',
    description: 'Hourly charting, ventilator observations and infusion management.',
    category: 'nursing',
    homeWorkspace: 'icu-flowsheet',
    permissions: [
      ...BASE_CLINICAL,
      ...LABEL_PRINTER,
      'barcode.verify.mar',
      'barcode.verify.sample',
      'barcode.verify.blood',
      'notify.escalation.read',
    ],
    abacDefaults: { assignedWardOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'nurse_er_triage',
    docsRow: 19,
    name: 'Nurse — ER / Triage',
    description: 'Triage board and emergency nursing.',
    category: 'nursing',
    homeWorkspace: 'triage-board',
    permissions: [
      ...BASE_CLINICAL,
      ...LABEL_PRINTER,
      'barcode.wristband.issue',
      'barcode.verify.mar',
      'barcode.verify.sample',
      'notify.escalation.read',
    ],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'nurse_ot_scrub',
    docsRow: 20,
    name: 'Nurse — OT / Scrub',
    description: 'OT checklist, instrument and swab counts, consumables and implant capture.',
    category: 'nursing',
    homeWorkspace: 'ot-checklist',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER, 'barcode.verify.implant', 'barcode.verify.cssd'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'infection_control_nurse',
    docsRow: 21,
    name: 'Nurse — Infection Control Officer',
    description: 'Healthcare-associated infection surveillance and isolation management.',
    category: 'nursing',
    homeWorkspace: 'infection-control',
    permissions: [...BASE_CLINICAL, ...BREAK_GLASS, 'audit.report.read', 'notify.report.read'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'nurse_supervisor',
    docsRow: 22,
    name: 'Nurse Supervisor / Matron',
    description: 'Nursing command centre: roster, nurse-patient ratios, audits and the escalation board.',
    category: 'nursing',
    homeWorkspace: 'nursing-command-centre',
    permissions: [
      ...BASE_CLINICAL,
      ...BREAK_GLASS,
      ...APPROVER,
      'notify.escalation.read',
      'notify.admin.manage',
      'notify.report.read',
      'admin.access.approve',
      'org.transfer.manage',
      'barcode.verify.override',
      'barcode.report.read',
    ],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'ward_attendant',
    docsRow: 23,
    name: 'Ward Boy / Attendant / Transport',
    description: 'Mobile task list for patient transport and bed status updates.',
    category: 'facilities',
    homeWorkspace: 'task-list',
    permissions: ['org.read', 'mdm.read', 'tpl.form.read', 'barcode.scan', 'print.job.create', 'print.job.read'],
    abacDefaults: { assignedWardOnly: true, dataClassMasks: ['aadhaar', 'address', 'mobile', 'diagnosis'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'receptionist',
    docsRow: 24,
    name: 'Receptionist / Front Office',
    description: 'Patient registration, appointments, token issue and ABHA linkage.',
    category: 'admin',
    homeWorkspace: 'registration',
    permissions: [
      ...BASE_STAFF,
      'barcode.scan',
      ...LABEL_PRINTER,
      'barcode.wristband.issue',
      'org.patient.locate',
      'tpl.render',
      'tpl.response.write',
      'tpl.response.read',
      'email.verify.send',
    ],
    abacDefaults: { dataClassMasks: ['diagnosis'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'call_centre_agent',
    docsRow: 25,
    name: 'Call Centre Agent',
    description: 'Appointments, enquiries and follow-up calls.',
    category: 'admin',
    homeWorkspace: 'call-console',
    permissions: [...BASE_STAFF, 'org.patient.locate', 'tpl.render'],
    abacDefaults: { dataClassMasks: ['aadhaar', 'diagnosis'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'cashier',
    docsRow: 26,
    name: 'Cashier',
    description: 'Cash counter: receipts, shift open/close and limited refunds.',
    category: 'finance',
    homeWorkspace: 'cash-counter',
    permissions: [...BASE_STAFF, 'barcode.scan', 'tpl.render', 'print.job.reprint'],
    abacDefaults: { amountLimit: { maxAmount: '2000.00', combine: 'whichever_is_lower' } },
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'billing_executive',
    docsRow: 27,
    name: 'Billing Executive (OP/IP)',
    description: 'Bills, interim bills and discounts within a configured ceiling.',
    category: 'finance',
    homeWorkspace: 'billing-desk',
    permissions: [...BASE_STAFF, 'barcode.scan', 'tpl.render', 'print.job.reprint', 'email.message.resend'],
    // docs/05 §ABAC gives the worked example: "amount_limit (discount ≤ 10 %)".
    abacDefaults: { amountLimit: { maxPercent: '10', maxAmount: '5000.00', combine: 'whichever_is_lower' } },
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'insurance_desk',
    docsRow: 28,
    name: 'Insurance / TPA Desk',
    description: 'Pre-authorisation, claims and supporting documents.',
    category: 'finance',
    homeWorkspace: 'insurance-queue',
    permissions: [...BASE_STAFF, 'tpl.render', 'tpl.response.read', 'org.patient.locate', 'mdm.payer.propose'],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'corporate_billing',
    docsRow: 29,
    name: 'Corporate / B2B Billing',
    description: 'Corporate accounts, invoices and statements of account.',
    category: 'finance',
    homeWorkspace: 'corporate-accounts',
    permissions: [...BASE_STAFF, 'tpl.render', 'email.send', 'email.message.read'],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'pharmacist_op',
    docsRow: 30,
    name: 'Pharmacist (OP)',
    description: 'Outpatient dispensing, over-the-counter sales and returns.',
    category: 'pharmacy',
    homeWorkspace: 'pharmacy-rx-queue',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER, 'mdm.pharmacy.propose'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'pharmacist_ip',
    docsRow: 31,
    name: 'Pharmacist (IP / Ward stock)',
    description: 'Ward indents, unit-dose dispensing and returns.',
    category: 'pharmacy',
    homeWorkspace: 'pharmacy-ward-indents',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER, 'mdm.pharmacy.propose'],
    abacDefaults: { assignedWardOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'pharmacy_incharge',
    docsRow: 32,
    name: 'Pharmacy In-charge',
    description:
      'Pharmacy administration: purchasing, pricing, and narcotics under two-person authorisation.',
    category: 'pharmacy',
    homeWorkspace: 'pharmacy-admin',
    permissions: [
      ...BASE_CLINICAL,
      ...LABEL_PRINTER,
      ...APPROVER,
      'mdm.pharmacy.propose',
      'mdm.pharmacy.approve',
      'mdm.inventory.propose',
      'barcode.verify.override',
      'barcode.report.read',
    ],
    abacDefaults: { requiresSecondPerson: true },
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'lab_technician',
    docsRow: 33,
    name: 'Lab Technician',
    description: 'Bench worklist and result entry. Deliberately cannot validate — that is the pathologist.',
    category: 'diagnostics',
    homeWorkspace: 'lab-bench',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER, 'barcode.verify.sample'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'phlebotomist',
    docsRow: 34,
    name: 'Phlebotomist / Sample Collector',
    description: 'Collection list, sample collection, rejection and label printing.',
    category: 'diagnostics',
    homeWorkspace: 'lab-collection',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER, 'barcode.verify.sample'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'lab_quality_manager',
    docsRow: 35,
    name: 'Lab Quality Manager',
    description: 'Internal quality control, external quality assessment and NABL documentation.',
    category: 'diagnostics',
    homeWorkspace: 'lab-qc',
    permissions: [...BASE_CLINICAL, 'mdm.lab.propose', 'mdm.lab.approve', 'mdm.quality.read', 'audit.report.read'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'radiology_technician',
    docsRow: 36,
    name: 'Radiology Technician',
    description: 'Modality worklist, scheduling and acquisition status.',
    category: 'diagnostics',
    homeWorkspace: 'radiology-modality',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'blood_bank_officer',
    docsRow: 37,
    name: 'Blood Bank Technician / Officer',
    description: 'Donors, components, cross-match and issue under two-person verification.',
    category: 'diagnostics',
    homeWorkspace: 'blood-bank',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER, 'barcode.verify.blood'],
    abacDefaults: { requiresSecondPerson: true },
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'cssd_technician',
    docsRow: 38,
    name: 'CSSD Technician / In-charge',
    description: 'Tray assembly, sterilisation cycles, issue and return, and recall.',
    category: 'supply',
    homeWorkspace: 'cssd',
    permissions: [...BASE_STAFF, 'barcode.scan', ...LABEL_PRINTER, 'barcode.verify.cssd'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'dietician',
    docsRow: 39,
    name: 'Dietician',
    description: 'Nutritional assessment and diet orders.',
    category: 'therapy',
    homeWorkspace: 'diet-worklist',
    permissions: [...BASE_CLINICAL, ...SIGNS_DOCUMENTS],
    abacDefaults: { careTeamOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'therapist',
    docsRow: 40,
    name: 'Physiotherapist / Occupational / Speech Therapist',
    description: 'Therapy assessments and session records.',
    category: 'therapy',
    homeWorkspace: 'therapy-schedule',
    permissions: [...BASE_CLINICAL, ...SIGNS_DOCUMENTS],
    abacDefaults: { careTeamOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'dialysis_technician',
    docsRow: 41,
    name: 'Dialysis Technician',
    description: 'Dialysis board, sessions and machine assignment.',
    category: 'therapy',
    homeWorkspace: 'dialysis-board',
    permissions: [...BASE_CLINICAL, ...LABEL_PRINTER],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'counsellor',
    docsRow: 42,
    name: 'Counsellor / Psychologist',
    description:
      'Session notes with restricted visibility. Mental-health records are excluded from cross-branch sharing by default (EN-041 §3.4.3).',
    category: 'therapy',
    homeWorkspace: 'counselling-sessions',
    permissions: [...BASE_CLINICAL, ...SIGNS_DOCUMENTS],
    abacDefaults: { ownPatientsOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'mrd_officer',
    docsRow: 43,
    name: 'MRD Officer / Coder',
    description: 'Coding, deficiency management, record retrieval and retention.',
    category: 'records',
    homeWorkspace: 'mrd-queue',
    permissions: [
      ...BASE_CLINICAL,
      'audit.patient.read',
      'audit.read',
      'audit.report.read',
      'mdm.clinical.propose',
      'mdm.terminology.manage',
      'mdm.map.manage',
      'mdm.valueset.manage',
      'tpl.print.manage',
      'tpl.governance.read',
      'tpl.reprint.override',
      'email.message.resend',
    ],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'stores_keeper',
    docsRow: 44,
    name: 'Stores Keeper / Store In-charge',
    description: 'Goods receipt, issues and stock counts.',
    category: 'supply',
    homeWorkspace: 'stores',
    permissions: [...BASE_STAFF, 'barcode.scan', ...LABEL_PRINTER, 'mdm.inventory.propose', 'org.transfer.manage'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'purchase_officer',
    docsRow: 45,
    name: 'Purchase Officer',
    description: 'Indents, requests for quotation and purchase orders.',
    category: 'supply',
    homeWorkspace: 'procurement',
    permissions: [
      ...BASE_STAFF,
      ...APPROVER,
      'wf.decide.bulk',
      'mdm.inventory.propose',
      'mdm.inventory.approve',
      'tpl.render',
      'email.send',
    ],
    abacDefaults: { amountLimit: { maxAmount: '50000.00', combine: 'whichever_is_lower' } },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'accountant',
    docsRow: 46,
    name: 'Accountant / Finance Manager',
    description: 'General ledger, accounts payable and receivable, banking and financial reports.',
    category: 'finance',
    homeWorkspace: 'finance',
    permissions: [
      ...BASE_STAFF,
      ...APPROVER,
      'wf.decide.bulk',
      'wf.matrix.manage',
      'wf.matrix.publish',
      'mdm.finance.propose',
      'mdm.finance.approve',
      'tpl.render',
      'tpl.print.manage',
      'org.finance.read',
      'lic.invoice.read',
      'lic.invoice.pay',
      'lic.subscription.read',
      'audit.report.read',
      'email.send',
    ],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'hr_executive',
    docsRow: 47,
    name: 'HR Executive / HR Manager',
    description: 'Employee master, leave and payroll.',
    category: 'admin',
    homeWorkspace: 'hr',
    permissions: [
      ...BASE_STAFF,
      ...APPROVER,
      'wf.decide.bulk',
      'wf.delegation.admin',
      'wf.matrix.manage',
      'admin.user.read',
      'admin.user.create',
      'admin.user.update',
      'admin.user.deactivate',
      'sso.reconcile',
      'tpl.render',
      'security.awareness.manage',
    ],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'biomedical_engineer',
    docsRow: 48,
    name: 'Biomedical Engineer',
    description: 'Equipment registry, calibration, breakdowns and AERB compliance.',
    category: 'facilities',
    homeWorkspace: 'biomedical',
    permissions: [...BASE_STAFF, 'barcode.scan', ...LABEL_PRINTER, 'security.patch.manage', 'admin.status.read'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'facility_maintenance',
    docsRow: 49,
    name: 'Facility / Maintenance',
    description: 'Work orders and preventive maintenance.',
    category: 'facilities',
    homeWorkspace: 'facility',
    permissions: [...BASE_STAFF, 'barcode.scan'],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'housekeeping',
    docsRow: 50,
    name: 'Housekeeping Supervisor / Staff',
    description: 'Mobile task list for room turnover and bio-medical waste rounds.',
    category: 'facilities',
    homeWorkspace: 'housekeeping',
    permissions: ['org.read', 'mdm.read', 'tpl.form.read', 'barcode.scan', 'print.job.create', 'print.job.read'],
    abacDefaults: { dataClassMasks: ['aadhaar', 'address', 'mobile', 'diagnosis', 'full_name'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'security_officer',
    docsRow: 51,
    name: 'Security Officer / Guard',
    description: 'Gate console: visitors, passes and incident logging.',
    category: 'facilities',
    homeWorkspace: 'gate-console',
    permissions: [...BASE_STAFF, 'barcode.scan', ...LABEL_PRINTER],
    abacDefaults: { dataClassMasks: ['aadhaar', 'diagnosis'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'ambulance_crew',
    docsRow: 52,
    name: 'Ambulance Dispatcher / Driver / EMT',
    description: 'Dispatch board and trip app with GPS and pre-hospital vitals.',
    category: 'facilities',
    homeWorkspace: 'ambulance-dispatch',
    permissions: [...BASE_CLINICAL, 'notify.escalation.read'],
    abacDefaults: { dataClassMasks: ['aadhaar'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'kitchen_staff',
    docsRow: 53,
    name: 'Canteen / Kitchen Staff',
    description: 'Kitchen board: diet dispatch and canteen point of sale.',
    category: 'facilities',
    homeWorkspace: 'kitchen-board',
    permissions: ['org.read', 'mdm.read', 'tpl.form.read', 'barcode.scan', 'print.job.create', 'print.job.read'],
    abacDefaults: { dataClassMasks: ['aadhaar', 'address', 'mobile', 'diagnosis'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'quality_manager',
    docsRow: 54,
    name: 'Quality Manager (NABH)',
    description: 'Quality indicators, audits, incident reporting and corrective/preventive action.',
    category: 'governance',
    homeWorkspace: 'quality',
    permissions: [
      ...BASE_STAFF,
      'audit.read',
      'audit.report.read',
      'audit.breakglass.review',
      'mdm.quality.read',
      'mdm.review.manage',
      'tpl.governance.read',
      'notify.report.read',
      'wf.report.read',
      'org.report.read',
      'dr.drill.manage',
      'dr.drill.read',
      'security.report.read',
      'barcode.report.read',
    ],
    abacDefaults: {},
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'marketing_crm',
    docsRow: 55,
    name: 'Marketing / CRM Executive',
    description: 'Leads, campaigns and outreach. Health content requires DPO approval.',
    category: 'admin',
    homeWorkspace: 'crm',
    permissions: [
      ...BASE_STAFF,
      'email.campaign.manage',
      'email.campaign.send',
      'email.suppression.manage',
      'email.report.read',
      'tpl.branding.manage',
      'tpl.print.manage',
    ],
    abacDefaults: { dataClassMasks: ['aadhaar', 'diagnosis'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'it_admin',
    docsRow: 56,
    name: 'IT Admin / Helpdesk',
    description: 'Tickets, devices, printers, integrations and security operations.',
    category: 'admin',
    homeWorkspace: 'it-console',
    permissions: [
      ...BASE_STAFF,
      'admin.user.read',
      'admin.user.reset',
      'admin.session.manage',
      'admin.device.manage',
      'admin.settings.read',
      'admin.status.read',
      'admin.report.read',
      'admin.print.configure',
      'admin.print.read',
      'print.job.manage',
      'barcode.scheme.configure',
      'barcode.device.configure',
      'ihub.connector.read',
      'ihub.connector.manage',
      'ihub.mapping.manage',
      'ihub.schedule.manage',
      'ihub.message.read',
      'ihub.message.retry',
      'ihub.message.replay',
      'ihub.dlq.manage',
      'ihub.health.read',
      'ihub.report.read',
      'sso.provider.manage',
      'sso.mapping.manage',
      'sso.identity.manage',
      'sso.log.read',
      'sso.scim.manage',
      'sso.reconcile',
      'sso.report.read',
      'audit.integrity.run',
      'audit.archive.manage',
      'audit.shipping.manage',
      'dr.repository.manage',
      'dr.backup.read',
      'dr.backup.run',
      'dr.restore.test',
      'dr.restore.request',
      'dr.drill.manage',
      'dr.runbook.manage',
      'dr.status.read',
      'dr.downtime.manage',
      'dr.maintenance.manage',
      'dr.report.read',
      'security.posture.read',
      'security.asset.manage',
      'security.vuln.manage',
      'security.patch.manage',
      'security.incident.read',
      'security.incident.manage',
      'security.endpoint.manage',
      'security.edge.manage',
      'security.siem.manage',
      'security.secret.manage',
      'security.report.read',
      'gateway.product.manage',
      'gateway.client.manage',
      'gateway.policy.manage',
      'gateway.usage.read',
      'gateway.log.read',
      'gateway.webhook.manage',
      'gateway.status.manage',
      'gateway.devportal.admin',
      'email.provider.manage',
      'email.sender.manage',
      'email.message.read',
      'email.message.resend',
      'email.suppression.manage',
      'email.report.read',
      'notify.type.manage',
      'notify.admin.read',
      'notify.report.read',
      'tpl.print.manage',
    ],
    abacDefaults: { deviceBound: true },
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'privacy_officer',
    docsRow: 57,
    name: 'Privacy Officer / DPO',
    description:
      'Consent ledger, PHI access reports, break-glass review, data-subject access requests and breach notification.',
    category: 'governance',
    homeWorkspace: 'privacy-dashboard',
    permissions: [
      ...BASE_STAFF,
      'audit.read',
      'audit.patient.read',
      'audit.user.read',
      'audit.breakglass.review',
      'audit.case.manage',
      'audit.export',
      'audit.integrity.run',
      'audit.retention.configure',
      'audit.config.manage',
      'audit.report.read',
      'admin.audit.read',
      'admin.audit.export',
      'org.audit.read',
      'org.policy.manage',
      'ihub.dataflow.read',
      'gateway.dataflow.read',
      'email.recipient.read',
      'email.phi.read',
      'security.breach.notify',
      'security.incident.read',
      'security.posture.read',
      'notify.admin.read',
      'wf.audit.read',
    ],
    abacDefaults: { deviceBound: true },
    mfaMandatory: true,
    sensitiveGrant: true,
    requiresCoSign: false,
  },
  {
    key: 'auditor',
    docsRow: 58,
    name: 'Auditor (internal / external)',
    description: 'Read-only across the tenant. Every export is audited.',
    category: 'governance',
    homeWorkspace: 'audit-workspace',
    permissions: [
      'org.read',
      'mdm.read',
      'mdm.report.read',
      'mdm.quality.read',
      'tpl.form.read',
      'tpl.governance.read',
      'lic.entitlement.read',
      'audit.read',
      'audit.patient.read',
      'audit.export',
      'audit.integrity.run',
      'audit.report.read',
      'admin.audit.read',
      'admin.audit.export',
      'admin.role.read',
      'admin.report.read',
      'org.audit.read',
      'org.report.read',
      'org.finance.read',
      'wf.audit.read',
      'wf.report.read',
      'dr.backup.read',
      'dr.drill.read',
      'dr.report.read',
      'security.posture.read',
      'security.incident.read',
      'security.report.read',
      'gateway.dataflow.read',
      'notify.report.read',
      'lic.subscription.read',
    ],
    abacDefaults: { dataClassMasks: ['aadhaar'] },
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'patient',
    docsRow: 59,
    name: 'Patient',
    description: 'Own records, appointments, bills and family access with consent. Authenticates by OTP or ABHA.',
    category: 'external',
    homeWorkspace: 'patient-portal',
    permissions: ['tpl.response.read', 'tpl.render'],
    abacDefaults: { ownPatientsOnly: true },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'family_attendant',
    docsRow: 60,
    name: 'Family / Attendant (bystander)',
    description: 'Limited view: bill, visiting pass and status updates. Linked by an explicit consent artefact.',
    category: 'external',
    homeWorkspace: 'family-view',
    permissions: ['tpl.render'],
    abacDefaults: { ownPatientsOnly: true, dataClassMasks: ['diagnosis', 'aadhaar'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'corporate_hr_client',
    docsRow: 61,
    name: 'Corporate HR Client',
    description: "Their employees' utilisation and invoices, through the corporate portal.",
    category: 'external',
    homeWorkspace: 'corporate-portal',
    permissions: ['tpl.render', 'lic.entitlement.read'],
    abacDefaults: { dataClassMasks: ['diagnosis', 'aadhaar', 'address'] },
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'payer_user',
    docsRow: 62,
    name: 'TPA / Insurer User',
    description: 'Pre-authorisations and claims for their own payer only.',
    category: 'external',
    homeWorkspace: 'payer-portal',
    permissions: ['tpl.render', 'tpl.response.read'],
    abacDefaults: { dataClassMasks: ['aadhaar'] },
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'vendor',
    docsRow: 63,
    name: 'Vendor',
    description: 'Purchase orders, invoices and consignment stock, through the vendor portal.',
    category: 'external',
    homeWorkspace: 'vendor-portal',
    permissions: ['tpl.render'],
    abacDefaults: {},
    mfaMandatory: true,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
  {
    key: 'device',
    docsRow: 64,
    name: 'Kiosk / TV / Device',
    description:
      'Scoped device token, not a person. Boards and kiosks read only what their pairing grants; they never idle out but their token is narrowly scoped.',
    category: 'device',
    homeWorkspace: 'device-display',
    permissions: ['print.agent', 'print.job.create', 'barcode.scan'],
    abacDefaults: { deviceBound: true, dataClassMasks: ['full_name', 'aadhaar', 'address', 'mobile', 'diagnosis'] },
    mfaMandatory: false,
    sensitiveGrant: false,
    requiresCoSign: false,
  },
];

// ── validation at import time ────────────────────────────────────────────────
// A template referencing an unregistered key would produce a role that grants
// nothing while looking correct in the admin UI. Fail the process instead.
for (const t of templates) {
  for (const key of t.permissions) {
    assertRegisteredPermission(key, `role template "${t.key}" (docs/05 row ${t.docsRow})`);
  }
}

const rowNumbers = new Set(templates.map((t) => t.docsRow));
if (rowNumbers.size !== templates.length) {
  throw new Error('Two role templates claim the same docs/05 row number.');
}
if (templates.length !== 64) {
  throw new Error(
    `docs/05 defines 64 system role templates; the registry has ${templates.length}. ` +
      `Add the missing template or update docs/05 — the two must agree.`,
  );
}

export const ROLE_TEMPLATES: readonly RoleTemplate[] = Object.freeze(templates);

const templatesByKey = new Map(ROLE_TEMPLATES.map((t) => [t.key, t]));

export function getRoleTemplate(key: string): RoleTemplate | undefined {
  return templatesByKey.get(key);
}

export const ROLE_TEMPLATE_KEYS: readonly string[] = Object.freeze(ROLE_TEMPLATES.map((t) => t.key));

/** docs/04 §2 / EN-007 §3.4.2 — roles that cannot log in without MFA enrolled. */
export const MFA_MANDATORY_ROLE_KEYS: readonly string[] = Object.freeze(
  ROLE_TEMPLATES.filter((t) => t.mfaMandatory).map((t) => t.key),
);

/** EN-007 §5 / EN-025 §3.3.3 — roles a group claim may never grant on its own. */
export const SENSITIVE_ROLE_KEYS: readonly string[] = Object.freeze(
  ROLE_TEMPLATES.filter((t) => t.sensitiveGrant).map((t) => t.key),
);
