-- ─────────────────────────────────────────────────────────────────────────────
-- Vim's HMS — Phase 0 platform schema
--
-- Generated by `prisma migrate dev --create-only`, then post-processed by
-- `packages/db/scripts/apply-partitioning.mjs` BEFORE first application to add
-- declarative monthly partitioning to the five high-write tables
-- (docs/03 §Table rules, docs/07 §4).
--
-- Applied in order after this file:
--   ..._partitions_and_indexes  — initial partitions, partial and trigram indexes
--   ..._rls_policies            — row-level security on every application table
--   ..._audit_guards            — append-only enforcement and the hash chain
--   ..._grants                  — least-privilege role grants
--
-- ROLLBACK: see the block at the foot of this file.
-- ─────────────────────────────────────────────────────────────────────────────

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "core";

-- CreateEnum
CREATE TYPE "core"."AuditActorType" AS ENUM ('user', 'service', 'device', 'system', 'patient', 'external_app');

-- CreateEnum
CREATE TYPE "core"."AuditActionType" AS ENUM ('insert', 'update', 'delete', 'read_phi', 'export', 'print', 'login', 'logout', 'approve', 'reject', 'sign', 'override', 'break_glass', 'config_change');

-- CreateEnum
CREATE TYPE "core"."AuditDataClass" AS ENUM ('phi', 'financial', 'hr', 'operational');

-- CreateEnum
CREATE TYPE "core"."AuditSensitivity" AS ENUM ('normal', 'sensitive', 'vip');

-- CreateEnum
CREATE TYPE "core"."AuditResult" AS ENUM ('success', 'denied', 'error');

-- CreateEnum
CREATE TYPE "core"."BreakGlassReviewStatus" AS ENUM ('pending', 'justified', 'not_justified', 'explained');

-- CreateEnum
CREATE TYPE "core"."AuditExportPurpose" AS ENUM ('dsar', 'court', 'regulator', 'internal_audit', 'certin', 'insurer');

-- CreateEnum
CREATE TYPE "core"."AuditCaseKind" AS ENUM ('privacy_investigation', 'hr', 'security_incident', 'medico_legal');

-- CreateEnum
CREATE TYPE "core"."UserType" AS ENUM ('staff', 'external', 'partner', 'device', 'service', 'patient');

-- CreateEnum
CREATE TYPE "core"."UserStatus" AS ENUM ('invited', 'active', 'locked', 'suspended', 'deactivated');

-- CreateEnum
CREATE TYPE "core"."AccessRequestStatus" AS ENUM ('pending', 'approved', 'rejected', 'withdrawn', 'expired');

-- CreateEnum
CREATE TYPE "core"."SessionMethod" AS ENUM ('password', 'sso', 'otp', 'device', 'impersonation', 'break_glass');

-- CreateEnum
CREATE TYPE "core"."DeviceKind" AS ENUM ('kiosk', 'tv', 'print_agent', 'workstation', 'mobile', 'analyzer');

-- CreateEnum
CREATE TYPE "core"."NumberingResetPolicy" AS ENUM ('fy', 'year', 'month', 'day', 'never');

-- CreateEnum
CREATE TYPE "core"."FileStatus" AS ENUM ('pending_upload', 'scanning', 'clean', 'infected', 'quarantined', 'deleted');

-- CreateEnum
CREATE TYPE "core"."HospitalStatus" AS ENUM ('active', 'suspended', 'closed');

-- CreateEnum
CREATE TYPE "core"."BranchKind" AS ENUM ('hospital', 'branch', 'satellite', 'collection_centre', 'daycare', 'polyclinic', 'warehouse');

-- CreateEnum
CREATE TYPE "core"."BranchStatus" AS ENUM ('provisioning', 'live', 'suspended', 'closed');

-- CreateEnum
CREATE TYPE "core"."ModuleProfile" AS ENUM ('full_hospital', 'opd_only', 'collection_centre', 'daycare');

-- CreateEnum
CREATE TYPE "core"."AccessScope" AS ENUM ('branch', 'entity', 'group');

-- CreateEnum
CREATE TYPE "core"."OrgUnitKind" AS ENUM ('ward', 'icu', 'ot_complex', 'block', 'floor', 'wing', 'department_unit');

-- CreateEnum
CREATE TYPE "core"."RegistrationKind" AS ENUM ('clinical_establishment', 'drug_licence', 'bmw_authorisation', 'aerb_licence', 'pcpndt_registration', 'fire_noc', 'nabh', 'nabl', 'abdm_hfr', 'gstin', 'pollution', 'lift', 'blood_bank', 'other');

-- CreateEnum
CREATE TYPE "core"."SharingMode" AS ENUM ('group', 'entity', 'branch');

-- CreateEnum
CREATE TYPE "core"."ResidencyConstraint" AS ENUM ('none', 'same_zone', 'aggregate_only');

-- CreateEnum
CREATE TYPE "core"."CrossBranchBasis" AS ENUM ('care_relationship', 'consent', 'break_glass', 'group_role');

-- CreateEnum
CREATE TYPE "core"."ResidencyPatientDataRule" AS ENUM ('allow', 'aggregate_only', 'deny');

-- CreateTable
CREATE TABLE "core"."audit_log" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "seq" BIGINT,
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "recorded_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actor_user_id" UUID,
    "actor_type" "core"."AuditActorType" NOT NULL DEFAULT 'user',
    "actor_role" VARCHAR(64),
    "impersonator_user_id" UUID,
    "session_id" UUID,
    "request_id" VARCHAR(128),
    "trace_id" VARCHAR(64),
    "ip" INET,
    "user_agent" VARCHAR(500),
    "device_id" UUID,
    "entity" VARCHAR(128) NOT NULL,
    "row_id" UUID,
    "business_key" VARCHAR(128),
    "action" "core"."AuditActionType" NOT NULL,
    "patient_id" UUID,
    "encounter_id" UUID,
    "before" JSONB,
    "after" JSONB,
    "changed_fields" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "reason_code" VARCHAR(64),
    "reason_text" TEXT,
    "data_class" "core"."AuditDataClass" NOT NULL,
    "sensitivity" "core"."AuditSensitivity" NOT NULL DEFAULT 'normal',
    "result" "core"."AuditResult" NOT NULL DEFAULT 'success',
    "denial_reason" VARCHAR(200),
    "app_module" VARCHAR(32),
    "api_route" VARCHAR(200),
    "row_count" INTEGER,
    "artifact_sha256" VARCHAR(64),
    "prev_hash" BYTEA,
    "row_hash" BYTEA,
    "sealed_at" TIMESTAMPTZ(6),

    CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id","occurred_at")
)
PARTITION BY RANGE ("occurred_at");
-- Partitioned monthly: 8–15 M rows/day at 2000 beds (EN-024 §13).
-- A month must be droppable in < 1 s (docs/07 §4), which DELETE can never be.


-- CreateTable
CREATE TABLE "core"."audit_chain_roots" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "chain_date" DATE NOT NULL,
    "first_seq" BIGINT NOT NULL,
    "last_seq" BIGINT NOT NULL,
    "row_count" BIGINT NOT NULL,
    "day_root" BYTEA NOT NULL,
    "prev_day_root" BYTEA,
    "computed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "anchored_at" TIMESTAMPTZ(6),
    "anchor_ref" VARCHAR(500),

    CONSTRAINT "audit_chain_roots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_integrity_runs" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "scope" VARCHAR(200) NOT NULL,
    "from_date" DATE,
    "to_date" DATE,
    "started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at" TIMESTAMPTZ(6),
    "rows_checked" BIGINT NOT NULL DEFAULT 0,
    "mismatches" INTEGER NOT NULL DEFAULT 0,
    "gaps" INTEGER NOT NULL DEFAULT 0,
    "status" VARCHAR(16) NOT NULL DEFAULT 'running',
    "details" JSONB NOT NULL DEFAULT '{}',
    "triggered_by" VARCHAR(16) NOT NULL DEFAULT 'schedule',

    CONSTRAINT "audit_integrity_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_break_glass" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "audit_log_id" UUID NOT NULL,
    "patient_id" UUID NOT NULL,
    "actor_user_id" UUID NOT NULL,
    "actor_role" VARCHAR(64),
    "reason_code" VARCHAR(64) NOT NULL,
    "reason_text" TEXT NOT NULL,
    "ward_id" UUID,
    "department_id" UUID,
    "care_team_checked" BOOLEAN NOT NULL DEFAULT true,
    "sensitivity" "core"."AuditSensitivity" NOT NULL DEFAULT 'normal',
    "notified_care_team_at" TIMESTAMPTZ(6),
    "notified_dpo_at" TIMESTAMPTZ(6),
    "review_status" "core"."BreakGlassReviewStatus" NOT NULL DEFAULT 'pending',
    "reviewed_by" UUID,
    "reviewed_at" TIMESTAMPTZ(6),
    "review_note" TEXT,
    "incident_ref" VARCHAR(64),
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_break_glass_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_retention_policies" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "data_class" VARCHAR(24) NOT NULL,
    "action_class" VARCHAR(32) NOT NULL,
    "online_days" INTEGER NOT NULL,
    "archive_years" INTEGER NOT NULL,
    "floor_days" INTEGER NOT NULL,
    "regulation" VARCHAR(300) NOT NULL,
    "archive_target" VARCHAR(200),
    "pseudonymise_on_erasure" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "audit_retention_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_archives" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "partition_name" VARCHAR(128) NOT NULL,
    "period_start" DATE NOT NULL,
    "period_end" DATE NOT NULL,
    "row_count" BIGINT NOT NULL,
    "file_ref" VARCHAR(500) NOT NULL,
    "file_sha256" VARCHAR(64) NOT NULL,
    "chain_root" BYTEA,
    "archived_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "storage_class" VARCHAR(32) NOT NULL DEFAULT 'standard_ia',
    "restorable_until" TIMESTAMPTZ(6),
    "restored_at" TIMESTAMPTZ(6),
    "purge_blocked_reason" VARCHAR(300),
    "held_row_count" BIGINT,

    CONSTRAINT "audit_archives_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_exports" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "requested_by" UUID NOT NULL,
    "purpose" "core"."AuditExportPurpose" NOT NULL,
    "scope" JSONB NOT NULL,
    "format" VARCHAR(16) NOT NULL,
    "row_count" BIGINT NOT NULL DEFAULT 0,
    "file_ref" VARCHAR(500),
    "file_sha256" VARCHAR(64),
    "certificate_65b_file_id" UUID,
    "integrity_status" VARCHAR(16),
    "approved_by" UUID,
    "approval_id" UUID,
    "patient_id" UUID,
    "exported_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_exports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_saved_searches" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "filters" JSONB NOT NULL,
    "schedule_cron" VARCHAR(64),
    "recipients" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "last_run_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "audit_saved_searches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_cases" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "title" VARCHAR(240) NOT NULL,
    "kind" "core"."AuditCaseKind" NOT NULL,
    "linked_incident_ref" VARCHAR(64),
    "status" VARCHAR(16) NOT NULL DEFAULT 'open',
    "opened_by" UUID NOT NULL,
    "opened_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "closed_at" TIMESTAMPTZ(6),
    "findings" TEXT,
    "evidence_bundle_file_id" UUID,
    "entry_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "notes" JSONB NOT NULL DEFAULT '[]',
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "audit_cases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."audit_field_policies" (
    "id" UUID NOT NULL,
    "hospital_id" UUID,
    "entity" VARCHAR(128) NOT NULL,
    "column" VARCHAR(64) NOT NULL,
    "mask" VARCHAR(16) NOT NULL,
    "data_class" VARCHAR(16) NOT NULL,
    "reason_required" BOOLEAN NOT NULL DEFAULT false,
    "note" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "audit_field_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."users" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "group_id" UUID,
    "username" VARCHAR(64) NOT NULL,
    "email" VARCHAR(254),
    "mobile" VARCHAR(20),
    "name" JSONB NOT NULL,
    "display_name" VARCHAR(200) NOT NULL,
    "employee_id" VARCHAR(64),
    "type" "core"."UserType" NOT NULL DEFAULT 'staff',
    "status" "core"."UserStatus" NOT NULL DEFAULT 'invited',
    "password_hash" TEXT,
    "password_changed_at" TIMESTAMPTZ(6),
    "must_change_password" BOOLEAN NOT NULL DEFAULT false,
    "mfa_enabled" BOOLEAN NOT NULL DEFAULT false,
    "mfa_methods" JSONB NOT NULL DEFAULT '[]',
    "mfa_secret_encrypted" TEXT,
    "recovery_codes_hash" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "pin_hash" TEXT,
    "sso_subject" VARCHAR(255),
    "professional" JSONB NOT NULL DEFAULT '{}',
    "preferences" JSONB NOT NULL DEFAULT '{}',
    "photo_file_id" UUID,
    "last_login_at" TIMESTAMPTZ(6),
    "failed_attempts" INTEGER NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMPTZ(6),
    "deleted_at" TIMESTAMPTZ(6),
    "deactivated_at" TIMESTAMPTZ(6),
    "deactivation_reason" VARCHAR(500),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."permissions" (
    "key" VARCHAR(96) NOT NULL,
    "module" VARCHAR(16) NOT NULL,
    "resource" VARCHAR(64) NOT NULL,
    "action" VARCHAR(32) NOT NULL,
    "description" TEXT NOT NULL,
    "data_class" VARCHAR(16) NOT NULL,
    "risk" VARCHAR(16) NOT NULL,
    "phase" INTEGER NOT NULL,
    "sensitive_grant" BOOLEAN NOT NULL DEFAULT false,
    "requires_second_person" BOOLEAN NOT NULL DEFAULT false,
    "requires_reason" BOOLEAN NOT NULL DEFAULT false,
    "requires_step_up" BOOLEAN NOT NULL DEFAULT false,
    "phi_read" BOOLEAN NOT NULL DEFAULT false,
    "clinical_safety_exempt" BOOLEAN NOT NULL DEFAULT false,
    "deprecated" BOOLEAN NOT NULL DEFAULT false,
    "synced_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "core"."roles" (
    "id" UUID NOT NULL,
    "hospital_id" UUID,
    "key" VARCHAR(64) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "description" TEXT NOT NULL,
    "template_key" VARCHAR(64),
    "abac_defaults" JSONB NOT NULL DEFAULT '{}',
    "home_workspace" VARCHAR(64) NOT NULL,
    "nav_preset" JSONB NOT NULL DEFAULT '{}',
    "is_system" BOOLEAN NOT NULL DEFAULT false,
    "mfa_mandatory" BOOLEAN NOT NULL DEFAULT false,
    "sensitive_grant" BOOLEAN NOT NULL DEFAULT false,
    "requires_co_sign" BOOLEAN NOT NULL DEFAULT false,
    "category" VARCHAR(24) NOT NULL,
    "docs_row" INTEGER,
    "version" INTEGER NOT NULL DEFAULT 1,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."role_permissions" (
    "role_id" UUID NOT NULL,
    "permission_key" VARCHAR(96) NOT NULL,

    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("role_id","permission_key")
);

-- CreateTable
CREATE TABLE "core"."user_roles" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role_id" UUID NOT NULL,
    "branch_id" UUID,
    "scope" JSONB NOT NULL DEFAULT '{}',
    "conditions" JSONB NOT NULL DEFAULT '{}',
    "valid_from" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "valid_to" TIMESTAMPTZ(6),
    "granted_by" UUID,
    "approval_id" UUID,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "source" VARCHAR(16) NOT NULL DEFAULT 'manual',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."sod_rules" (
    "id" UUID NOT NULL,
    "hospital_id" UUID,
    "perm_a" VARCHAR(96) NOT NULL,
    "perm_b" VARCHAR(96) NOT NULL,
    "mode" VARCHAR(8) NOT NULL,
    "reason" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "sod_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."access_requests" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role_id" UUID NOT NULL,
    "branch_id" UUID,
    "scope" JSONB NOT NULL DEFAULT '{}',
    "justification" TEXT NOT NULL,
    "requested_by" UUID NOT NULL,
    "status" "core"."AccessRequestStatus" NOT NULL DEFAULT 'pending',
    "approval_id" UUID,
    "decided_at" TIMESTAMPTZ(6),
    "decided_by" UUID,
    "decision_reason" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "access_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."access_reviews" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "period_start" DATE NOT NULL,
    "period_end" DATE NOT NULL,
    "due_at" TIMESTAMPTZ(6) NOT NULL,
    "status" VARCHAR(16) NOT NULL DEFAULT 'open',
    "opened_by" UUID,
    "completed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "access_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."access_review_items" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "review_id" UUID NOT NULL,
    "user_role_id" UUID NOT NULL,
    "reviewer_user_id" UUID,
    "decision" VARCHAR(16),
    "decided_at" TIMESTAMPTZ(6),
    "note" TEXT,

    CONSTRAINT "access_review_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."auth_policies" (
    "hospital_id" UUID NOT NULL,
    "password" JSONB NOT NULL DEFAULT '{}',
    "lockout" JSONB NOT NULL DEFAULT '{}',
    "mfa" JSONB NOT NULL DEFAULT '{}',
    "session" JSONB NOT NULL DEFAULT '{}',
    "otp" JSONB NOT NULL DEFAULT '{}',
    "sso" JSONB NOT NULL DEFAULT '{}',
    "pin" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "auth_policies_pkey" PRIMARY KEY ("hospital_id")
);

-- CreateTable
CREATE TABLE "core"."password_history" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "password_hash" TEXT NOT NULL,
    "changed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "password_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."sessions" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "branch_id" UUID,
    "device_id" UUID,
    "user_agent" VARCHAR(500),
    "ip" INET,
    "geo" VARCHAR(120),
    "method" "core"."SessionMethod" NOT NULL,
    "acr" VARCHAR(64),
    "amr" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "auth_time" TIMESTAMPTZ(6) NOT NULL,
    "refresh_family_id" UUID NOT NULL,
    "refresh_token_hash" TEXT,
    "refresh_generation" INTEGER NOT NULL DEFAULT 0,
    "has_unsaved_work" BOOLEAN NOT NULL DEFAULT false,
    "impersonator_user_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "revoked_at" TIMESTAMPTZ(6),
    "revoke_reason" VARCHAR(200),

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id","created_at")
)
PARTITION BY RANGE ("created_at");
-- Partitioned monthly: 180-day online retention per CERT-In (EN-007 §5).
-- A month must be droppable in < 1 s (docs/07 §4), which DELETE can never be.


-- CreateTable
CREATE TABLE "core"."devices" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "kind" "core"."DeviceKind" NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "location_label" VARCHAR(160),
    "fingerprint" VARCHAR(200),
    "token_hash" TEXT,
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "pairing_code" VARCHAR(16),
    "pairing_code_expires_at" TIMESTAMPTZ(6),
    "paired_by" UUID,
    "paired_at" TIMESTAMPTZ(6),
    "last_seen_at" TIMESTAMPTZ(6),
    "revoked_at" TIMESTAMPTZ(6),
    "revoke_reason" VARCHAR(200),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "devices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."mfa_challenges" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "purpose" VARCHAR(32) NOT NULL,
    "action_key" VARCHAR(96),
    "method" VARCHAR(24),
    "code_hash" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 5,
    "consumed_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mfa_challenges_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."otp_codes" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "target_hash" VARCHAR(64) NOT NULL,
    "channel" VARCHAR(16) NOT NULL,
    "purpose" VARCHAR(32) NOT NULL,
    "code_hash" TEXT NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "consumed_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "otp_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."login_audit" (
    "id" UUID NOT NULL,
    "hospital_id" UUID,
    "username_attempted" VARCHAR(254) NOT NULL,
    "user_id" UUID,
    "provider_id" UUID,
    "result" VARCHAR(32) NOT NULL,
    "reason_code" VARCHAR(64),
    "method" VARCHAR(24) NOT NULL,
    "acr" VARCHAR(64),
    "amr" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "ip" INET,
    "user_agent" VARCHAR(500),
    "geo" VARCHAR(120),
    "device_id" UUID,
    "latency_ms" INTEGER,
    "correlation_id" VARCHAR(128),
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "login_audit_pkey" PRIMARY KEY ("id","occurred_at")
)
PARTITION BY RANGE ("occurred_at");
-- Partitioned monthly: 180-day online retention per CERT-In (EN-024 §3.3).
-- A month must be droppable in < 1 s (docs/07 §4), which DELETE can never be.


-- CreateTable
CREATE TABLE "core"."impersonation_sessions" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "actor_user_id" UUID NOT NULL,
    "target_user_id" UUID NOT NULL,
    "ticket_ref" VARCHAR(64) NOT NULL,
    "reason" TEXT NOT NULL,
    "mode" VARCHAR(8) NOT NULL DEFAULT 'read',
    "approved_by" UUID,
    "approval_id" UUID,
    "session_id" UUID,
    "started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "ended_at" TIMESTAMPTZ(6),
    "ended_reason" VARCHAR(32),

    CONSTRAINT "impersonation_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."setting_definitions" (
    "key" VARCHAR(128) NOT NULL,
    "module" VARCHAR(16) NOT NULL,
    "label" VARCHAR(200) NOT NULL,
    "description" TEXT NOT NULL,
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "json_schema" JSONB NOT NULL,
    "default_value" JSONB NOT NULL,
    "sensitivity" VARCHAR(16) NOT NULL,
    "requires_approval" BOOLEAN NOT NULL DEFAULT false,
    "dual_control" BOOLEAN NOT NULL DEFAULT false,
    "synced_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "setting_definitions_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "core"."settings" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "department_id" UUID,
    "user_id" UUID,
    "key" VARCHAR(128) NOT NULL,
    "value" JSONB NOT NULL,
    "value_encrypted" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."holidays" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "date" DATE NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "kind" VARCHAR(16) NOT NULL,
    "applies_to" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "holidays_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."numbering_series" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "key" VARCHAR(48) NOT NULL,
    "pattern" VARCHAR(120) NOT NULL,
    "scope" VARCHAR(16) NOT NULL,
    "fy" VARCHAR(9),
    "current_value" BIGINT NOT NULL DEFAULT 0,
    "gapless" BOOLEAN NOT NULL DEFAULT false,
    "reset_policy" "core"."NumberingResetPolicy" NOT NULL DEFAULT 'fy',
    "version" INTEGER NOT NULL DEFAULT 1,
    "effective_from" TIMESTAMPTZ(6) NOT NULL,
    "effective_to" TIMESTAMPTZ(6),
    "locked_at" TIMESTAMPTZ(6),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "numbering_series_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."numbering_allocations" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "series_id" UUID NOT NULL,
    "number" BIGINT NOT NULL,
    "formatted" VARCHAR(120) NOT NULL,
    "ref_type" VARCHAR(64),
    "ref_id" UUID,
    "allocated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "allocated_by" UUID,
    "voided_at" TIMESTAMPTZ(6),
    "void_reason" VARCHAR(300),

    CONSTRAINT "numbering_allocations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."feature_flags" (
    "id" UUID NOT NULL,
    "key" VARCHAR(128) NOT NULL,
    "hospital_id" UUID,
    "branch_id" UUID,
    "role_key" VARCHAR(64),
    "user_id" UUID,
    "enabled" BOOLEAN NOT NULL,
    "rollout_pct" INTEGER,
    "expires_at" TIMESTAMPTZ(6),
    "note" VARCHAR(500),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "feature_flags_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."files" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "bucket" VARCHAR(120) NOT NULL,
    "object_key" VARCHAR(500) NOT NULL,
    "filename" VARCHAR(300) NOT NULL,
    "content_type" VARCHAR(160) NOT NULL,
    "detected_content_type" VARCHAR(160),
    "size_bytes" BIGINT NOT NULL,
    "sha256" VARCHAR(64),
    "status" "core"."FileStatus" NOT NULL DEFAULT 'pending_upload',
    "scan_result" VARCHAR(200),
    "scanned_at" TIMESTAMPTZ(6),
    "contains_phi" BOOLEAN NOT NULL DEFAULT false,
    "patient_id" UUID,
    "ref_type" VARCHAR(64),
    "ref_id" UUID,
    "storage_class" VARCHAR(32) NOT NULL DEFAULT 'standard',
    "retain_until" TIMESTAMPTZ(6),
    "legal_hold" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."idempotency_keys" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "key" VARCHAR(200) NOT NULL,
    "user_id" UUID,
    "route" VARCHAR(200) NOT NULL,
    "method" VARCHAR(8) NOT NULL,
    "request_hash" VARCHAR(64) NOT NULL,
    "status" VARCHAR(16) NOT NULL DEFAULT 'in_flight',
    "response_status" INTEGER,
    "response_body" JSONB,
    "locked_until" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."outbox_events" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "aggregate" VARCHAR(64) NOT NULL,
    "aggregate_id" VARCHAR(128) NOT NULL,
    "aggregate_version" INTEGER,
    "event_type" VARCHAR(128) NOT NULL,
    "schema_version" INTEGER NOT NULL DEFAULT 1,
    "payload" JSONB NOT NULL,
    "contains_phi" BOOLEAN NOT NULL DEFAULT false,
    "actor_user_id" UUID,
    "actor_type" VARCHAR(16) NOT NULL DEFAULT 'user',
    "correlation_id" VARCHAR(128) NOT NULL,
    "causation_id" VARCHAR(128),
    "trace_id" VARCHAR(64),
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_at" TIMESTAMPTZ(6),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "dead_lettered_at" TIMESTAMPTZ(6),
    "retention_days" INTEGER NOT NULL DEFAULT 7,

    CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id","occurred_at")
)
PARTITION BY RANGE ("occurred_at");
-- Partitioned monthly: ~500 k rows/day, purged 7 days after publish (docs/07 §1.3).
-- A month must be droppable in < 1 s (docs/07 §4), which DELETE can never be.


-- CreateTable
CREATE TABLE "core"."dr_drills" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "kind" VARCHAR(32) NOT NULL,
    "scheduled_at" TIMESTAMPTZ(6) NOT NULL,
    "started_at" TIMESTAMPTZ(6),
    "finished_at" TIMESTAMPTZ(6),
    "rpo_achieved_seconds" INTEGER,
    "rto_achieved_seconds" INTEGER,
    "passed" BOOLEAN,
    "conducted_by" UUID,
    "witnessed_by" UUID,
    "findings" TEXT,
    "report_file_id" UUID,
    "capa_ref" VARCHAR(64),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "dr_drills_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."downtime_windows" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID,
    "kind" VARCHAR(24) NOT NULL,
    "from_at" TIMESTAMPTZ(6) NOT NULL,
    "to_at" TIMESTAMPTZ(6),
    "reason" TEXT NOT NULL,
    "declared_by" UUID NOT NULL,
    "reserved_number_block" JSONB,
    "closed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "downtime_windows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."org_groups" (
    "id" UUID NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "legal_name" VARCHAR(300) NOT NULL,
    "brand" VARCHAR(120),
    "logo_file_id" UUID,
    "default_currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "default_timezone" VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    "hq_address" JSONB,
    "status" "core"."HospitalStatus" NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "org_groups_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."hospitals" (
    "id" UUID NOT NULL,
    "group_id" UUID,
    "code" VARCHAR(24) NOT NULL,
    "legal_name" VARCHAR(300) NOT NULL,
    "display_name" VARCHAR(200) NOT NULL,
    "entity_type" VARCHAR(64),
    "primary_gstin" VARCHAR(15),
    "pan" VARCHAR(10),
    "tan" VARCHAR(10),
    "cin" VARCHAR(21),
    "registrations" JSONB NOT NULL DEFAULT '{}',
    "rohini_id" VARCHAR(32),
    "hfr_id" VARCHAR(64),
    "timezone" VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    "locale" VARCHAR(16) NOT NULL DEFAULT 'en-IN',
    "languages" TEXT[] DEFAULT ARRAY['en-IN']::TEXT[],
    "currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "books_currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "fy_start_month" SMALLINT NOT NULL DEFAULT 4,
    "residency_zone" VARCHAR(8) NOT NULL DEFAULT 'in',
    "address" JSONB NOT NULL DEFAULT '{}',
    "contacts" JSONB NOT NULL DEFAULT '{}',
    "dpo" JSONB NOT NULL DEFAULT '{}',
    "grievance_officer" JSONB NOT NULL DEFAULT '{}',
    "logo_light_file_id" UUID,
    "logo_dark_file_id" UUID,
    "is_tenant_boundary" BOOLEAN NOT NULL DEFAULT true,
    "status" "core"."HospitalStatus" NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "hospitals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."branches" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "group_id" UUID,
    "code" VARCHAR(16) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "short_name" VARCHAR(40) NOT NULL,
    "path" VARCHAR(512),
    "parent_branch_id" UUID,
    "kind" "core"."BranchKind" NOT NULL DEFAULT 'branch',
    "serves_from_branch_id" UUID,
    "address" JSONB NOT NULL DEFAULT '{}',
    "state_code" CHAR(2),
    "gstin" VARCHAR(15),
    "timezone" VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    "currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "residency_zone" VARCHAR(8) NOT NULL DEFAULT 'in',
    "hfr_id" VARCHAR(64),
    "rohini_id" VARCHAR(32),
    "working_hours" JSONB NOT NULL DEFAULT '{}',
    "bed_count" INTEGER NOT NULL DEFAULT 0,
    "module_profile" "core"."ModuleProfile" NOT NULL DEFAULT 'full_hospital',
    "colour_token" VARCHAR(32) NOT NULL DEFAULT 'branch-1',
    "go_live_at" TIMESTAMPTZ(6),
    "status" "core"."BranchStatus" NOT NULL DEFAULT 'provisioning',
    "closed_at" TIMESTAMPTZ(6),
    "successor_branch_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "branches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."org_units" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "code" VARCHAR(32) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "kind" "core"."OrgUnitKind" NOT NULL,
    "path" VARCHAR(512),
    "capacity" INTEGER,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "org_units_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."org_branch_registrations" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "kind" "core"."RegistrationKind" NOT NULL,
    "number" VARCHAR(120) NOT NULL,
    "issuing_authority" VARCHAR(200),
    "valid_from" DATE,
    "valid_to" DATE,
    "document_file_id" UUID,
    "status" VARCHAR(24) NOT NULL DEFAULT 'valid',
    "renewal_owner_user_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "org_branch_registrations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."org_data_domains" (
    "id" UUID NOT NULL,
    "hospital_id" UUID,
    "domain_key" VARCHAR(64) NOT NULL,
    "sharing_mode" "core"."SharingMode" NOT NULL,
    "override_policy" JSONB NOT NULL DEFAULT '{}',
    "consent_required" BOOLEAN NOT NULL DEFAULT false,
    "residency_constraint" "core"."ResidencyConstraint" NOT NULL DEFAULT 'none',
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "org_data_domains_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."org_user_branch_access" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "roles" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "scope" "core"."AccessScope" NOT NULL DEFAULT 'branch',
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "from_at" TIMESTAMPTZ(6) NOT NULL,
    "to_at" TIMESTAMPTZ(6),
    "granted_by" UUID,
    "reason" VARCHAR(500),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "org_user_branch_access_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."org_cross_branch_access_log" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "actor_user_id" UUID NOT NULL,
    "actor_branch_id" UUID NOT NULL,
    "patient_id" UUID NOT NULL,
    "target_branch_id" UUID NOT NULL,
    "target_entity_id" UUID,
    "basis" "core"."CrossBranchBasis" NOT NULL,
    "consent_ref" UUID,
    "reason" TEXT,
    "resources" JSONB NOT NULL DEFAULT '{}',
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewed_by" UUID,
    "reviewed_at" TIMESTAMPTZ(6),

    CONSTRAINT "org_cross_branch_access_log_pkey" PRIMARY KEY ("id","occurred_at")
)
PARTITION BY RANGE ("occurred_at");
-- Partitioned monthly: 7-year DPDP disclosure log (EN-041 §4).
-- A month must be droppable in < 1 s (docs/07 §4), which DELETE can never be.


-- CreateTable
CREATE TABLE "core"."org_branch_onboarding" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "template_source_branch_id" UUID,
    "steps" JSONB NOT NULL DEFAULT '[]',
    "smoke_test" JSONB NOT NULL DEFAULT '{}',
    "go_live_report_file_id" UUID,
    "started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(6),
    "elapsed_minutes" INTEGER,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "org_branch_onboarding_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "core"."org_residency_policies" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "group_id" UUID,
    "from_zone" VARCHAR(8) NOT NULL,
    "to_zone" VARCHAR(8) NOT NULL,
    "patient_data" "core"."ResidencyPatientDataRule" NOT NULL,
    "legal_basis" TEXT,
    "dpa_ref" VARCHAR(200),
    "approved_by" UUID,
    "effective_from" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "org_residency_policies_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "audit_log_hospital_id_occurred_at_idx" ON "core"."audit_log"("hospital_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "audit_log_patient_id_occurred_at_idx" ON "core"."audit_log"("patient_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "audit_log_actor_user_id_occurred_at_idx" ON "core"."audit_log"("actor_user_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "audit_log_entity_row_id_occurred_at_idx" ON "core"."audit_log"("entity", "row_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "audit_log_hospital_id_action_occurred_at_idx" ON "core"."audit_log"("hospital_id", "action", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "audit_log_hospital_id_business_key_idx" ON "core"."audit_log"("hospital_id", "business_key");

-- CreateIndex
CREATE INDEX "audit_log_hospital_id_sealed_at_idx" ON "core"."audit_log"("hospital_id", "sealed_at");

-- CreateIndex
CREATE UNIQUE INDEX "audit_log_hospital_seq_key" ON "core"."audit_log"("hospital_id", "seq", "occurred_at");

-- CreateIndex
CREATE INDEX "audit_chain_roots_hospital_id_chain_date_idx" ON "core"."audit_chain_roots"("hospital_id", "chain_date" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "audit_chain_roots_hospital_id_chain_date_key" ON "core"."audit_chain_roots"("hospital_id", "chain_date");

-- CreateIndex
CREATE INDEX "audit_integrity_runs_hospital_id_started_at_idx" ON "core"."audit_integrity_runs"("hospital_id", "started_at" DESC);

-- CreateIndex
CREATE INDEX "audit_integrity_runs_hospital_id_status_idx" ON "core"."audit_integrity_runs"("hospital_id", "status");

-- CreateIndex
CREATE INDEX "audit_break_glass_hospital_id_review_status_occurred_at_idx" ON "core"."audit_break_glass"("hospital_id", "review_status", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "audit_break_glass_hospital_id_patient_id_occurred_at_idx" ON "core"."audit_break_glass"("hospital_id", "patient_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "audit_break_glass_actor_user_id_occurred_at_idx" ON "core"."audit_break_glass"("actor_user_id", "occurred_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "audit_retention_policies_hospital_id_data_class_action_clas_key" ON "core"."audit_retention_policies"("hospital_id", "data_class", "action_class");

-- CreateIndex
CREATE INDEX "audit_archives_hospital_id_archived_at_idx" ON "core"."audit_archives"("hospital_id", "archived_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "audit_archives_hospital_id_partition_name_key" ON "core"."audit_archives"("hospital_id", "partition_name");

-- CreateIndex
CREATE INDEX "audit_exports_hospital_id_created_at_idx" ON "core"."audit_exports"("hospital_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "audit_exports_hospital_id_purpose_idx" ON "core"."audit_exports"("hospital_id", "purpose");

-- CreateIndex
CREATE UNIQUE INDEX "audit_saved_searches_hospital_id_user_id_name_key" ON "core"."audit_saved_searches"("hospital_id", "user_id", "name");

-- CreateIndex
CREATE INDEX "audit_cases_hospital_id_status_opened_at_idx" ON "core"."audit_cases"("hospital_id", "status", "opened_at" DESC);

-- CreateIndex
CREATE INDEX "audit_field_policies_entity_idx" ON "core"."audit_field_policies"("entity");

-- CreateIndex
CREATE UNIQUE INDEX "audit_field_policies_hospital_id_entity_column_key" ON "core"."audit_field_policies"("hospital_id", "entity", "column");

-- CreateIndex
CREATE INDEX "users_hospital_id_status_idx" ON "core"."users"("hospital_id", "status");

-- CreateIndex
CREATE INDEX "users_hospital_id_employee_id_idx" ON "core"."users"("hospital_id", "employee_id");

-- CreateIndex
CREATE INDEX "users_sso_subject_idx" ON "core"."users"("sso_subject");

-- CreateIndex
CREATE UNIQUE INDEX "users_group_username_key" ON "core"."users"("group_id", "username");

-- CreateIndex
CREATE INDEX "permissions_module_idx" ON "core"."permissions"("module");

-- CreateIndex
CREATE INDEX "permissions_deprecated_idx" ON "core"."permissions"("deprecated");

-- CreateIndex
CREATE INDEX "roles_hospital_id_active_idx" ON "core"."roles"("hospital_id", "active");

-- CreateIndex
CREATE INDEX "roles_template_key_idx" ON "core"."roles"("template_key");

-- CreateIndex
CREATE UNIQUE INDEX "roles_hospital_id_key_key" ON "core"."roles"("hospital_id", "key");

-- CreateIndex
CREATE INDEX "role_permissions_permission_key_idx" ON "core"."role_permissions"("permission_key");

-- CreateIndex
CREATE INDEX "user_roles_user_id_active_idx" ON "core"."user_roles"("user_id", "active");

-- CreateIndex
CREATE INDEX "user_roles_hospital_id_role_id_active_idx" ON "core"."user_roles"("hospital_id", "role_id", "active");

-- CreateIndex
CREATE INDEX "user_roles_hospital_id_branch_id_active_idx" ON "core"."user_roles"("hospital_id", "branch_id", "active");

-- CreateIndex
CREATE UNIQUE INDEX "sod_rules_hospital_id_perm_a_perm_b_key" ON "core"."sod_rules"("hospital_id", "perm_a", "perm_b");

-- CreateIndex
CREATE INDEX "access_requests_hospital_id_status_created_at_idx" ON "core"."access_requests"("hospital_id", "status", "created_at" DESC);

-- CreateIndex
CREATE INDEX "access_requests_user_id_idx" ON "core"."access_requests"("user_id");

-- CreateIndex
CREATE INDEX "access_reviews_hospital_id_status_due_at_idx" ON "core"."access_reviews"("hospital_id", "status", "due_at");

-- CreateIndex
CREATE INDEX "access_review_items_hospital_id_review_id_decision_idx" ON "core"."access_review_items"("hospital_id", "review_id", "decision");

-- CreateIndex
CREATE INDEX "password_history_user_id_changed_at_idx" ON "core"."password_history"("user_id", "changed_at" DESC);

-- CreateIndex
CREATE INDEX "sessions_hospital_id_user_id_created_at_idx" ON "core"."sessions"("hospital_id", "user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "sessions_refresh_family_id_idx" ON "core"."sessions"("refresh_family_id");

-- CreateIndex
CREATE INDEX "sessions_hospital_id_branch_id_revoked_at_idx" ON "core"."sessions"("hospital_id", "branch_id", "revoked_at");

-- CreateIndex
CREATE INDEX "devices_hospital_id_kind_revoked_at_idx" ON "core"."devices"("hospital_id", "kind", "revoked_at");

-- CreateIndex
CREATE INDEX "devices_pairing_code_idx" ON "core"."devices"("pairing_code");

-- CreateIndex
CREATE UNIQUE INDEX "devices_hospital_id_branch_id_name_key" ON "core"."devices"("hospital_id", "branch_id", "name");

-- CreateIndex
CREATE INDEX "mfa_challenges_hospital_id_user_id_purpose_idx" ON "core"."mfa_challenges"("hospital_id", "user_id", "purpose");

-- CreateIndex
CREATE INDEX "mfa_challenges_expires_at_idx" ON "core"."mfa_challenges"("expires_at");

-- CreateIndex
CREATE INDEX "otp_codes_hospital_id_target_hash_created_at_idx" ON "core"."otp_codes"("hospital_id", "target_hash", "created_at" DESC);

-- CreateIndex
CREATE INDEX "otp_codes_expires_at_idx" ON "core"."otp_codes"("expires_at");

-- CreateIndex
CREATE INDEX "login_audit_hospital_id_occurred_at_idx" ON "core"."login_audit"("hospital_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "login_audit_username_attempted_occurred_at_idx" ON "core"."login_audit"("username_attempted", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "login_audit_user_id_occurred_at_idx" ON "core"."login_audit"("user_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "login_audit_result_occurred_at_idx" ON "core"."login_audit"("result", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "impersonation_sessions_hospital_id_started_at_idx" ON "core"."impersonation_sessions"("hospital_id", "started_at" DESC);

-- CreateIndex
CREATE INDEX "impersonation_sessions_target_user_id_idx" ON "core"."impersonation_sessions"("target_user_id");

-- CreateIndex
CREATE INDEX "setting_definitions_module_idx" ON "core"."setting_definitions"("module");

-- CreateIndex
CREATE INDEX "settings_hospital_id_key_idx" ON "core"."settings"("hospital_id", "key");

-- CreateIndex
CREATE INDEX "settings_hospital_id_branch_id_key_idx" ON "core"."settings"("hospital_id", "branch_id", "key");

-- CreateIndex
CREATE INDEX "settings_user_id_key_idx" ON "core"."settings"("user_id", "key");

-- CreateIndex
CREATE INDEX "holidays_hospital_id_date_idx" ON "core"."holidays"("hospital_id", "date");

-- CreateIndex
CREATE UNIQUE INDEX "holidays_hospital_id_branch_id_date_name_key" ON "core"."holidays"("hospital_id", "branch_id", "date", "name");

-- CreateIndex
CREATE INDEX "numbering_series_hospital_id_key_active_idx" ON "core"."numbering_series"("hospital_id", "key", "active");

-- CreateIndex
CREATE UNIQUE INDEX "numbering_series_hospital_id_branch_id_key_fy_version_key" ON "core"."numbering_series"("hospital_id", "branch_id", "key", "fy", "version");

-- CreateIndex
CREATE INDEX "numbering_allocations_hospital_id_ref_type_ref_id_idx" ON "core"."numbering_allocations"("hospital_id", "ref_type", "ref_id");

-- CreateIndex
CREATE UNIQUE INDEX "numbering_allocations_series_id_number_key" ON "core"."numbering_allocations"("series_id", "number");

-- CreateIndex
CREATE INDEX "feature_flags_hospital_id_key_idx" ON "core"."feature_flags"("hospital_id", "key");

-- CreateIndex
CREATE INDEX "feature_flags_key_idx" ON "core"."feature_flags"("key");

-- CreateIndex
CREATE INDEX "files_hospital_id_ref_type_ref_id_idx" ON "core"."files"("hospital_id", "ref_type", "ref_id");

-- CreateIndex
CREATE INDEX "files_hospital_id_patient_id_idx" ON "core"."files"("hospital_id", "patient_id");

-- CreateIndex
CREATE INDEX "files_status_idx" ON "core"."files"("status");

-- CreateIndex
CREATE UNIQUE INDEX "files_bucket_object_key_key" ON "core"."files"("bucket", "object_key");

-- CreateIndex
CREATE INDEX "idempotency_keys_expires_at_idx" ON "core"."idempotency_keys"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "idempotency_keys_hospital_id_key_route_key" ON "core"."idempotency_keys"("hospital_id", "key", "route");

-- CreateIndex
CREATE INDEX "outbox_events_occurred_at_idx" ON "core"."outbox_events"("occurred_at");

-- CreateIndex
CREATE INDEX "outbox_events_hospital_id_event_type_occurred_at_idx" ON "core"."outbox_events"("hospital_id", "event_type", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "outbox_events_aggregate_aggregate_id_idx" ON "core"."outbox_events"("aggregate", "aggregate_id");

-- CreateIndex
CREATE INDEX "outbox_events_correlation_id_idx" ON "core"."outbox_events"("correlation_id");

-- CreateIndex
CREATE INDEX "dr_drills_hospital_id_scheduled_at_idx" ON "core"."dr_drills"("hospital_id", "scheduled_at" DESC);

-- CreateIndex
CREATE INDEX "downtime_windows_hospital_id_from_at_idx" ON "core"."downtime_windows"("hospital_id", "from_at" DESC);

-- CreateIndex
CREATE INDEX "hospitals_group_id_status_idx" ON "core"."hospitals"("group_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "hospitals_code_key" ON "core"."hospitals"("code");

-- CreateIndex
CREATE INDEX "branches_hospital_id_status_idx" ON "core"."branches"("hospital_id", "status");

-- CreateIndex
CREATE INDEX "branches_group_id_status_idx" ON "core"."branches"("group_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "branches_hospital_id_code_key" ON "core"."branches"("hospital_id", "code");

-- CreateIndex
CREATE INDEX "org_units_hospital_id_branch_id_active_idx" ON "core"."org_units"("hospital_id", "branch_id", "active");

-- CreateIndex
CREATE UNIQUE INDEX "org_units_branch_id_code_key" ON "core"."org_units"("branch_id", "code");

-- CreateIndex
CREATE INDEX "org_branch_registrations_hospital_id_branch_id_kind_idx" ON "core"."org_branch_registrations"("hospital_id", "branch_id", "kind");

-- CreateIndex
CREATE INDEX "org_branch_registrations_hospital_id_valid_to_idx" ON "core"."org_branch_registrations"("hospital_id", "valid_to");

-- CreateIndex
CREATE UNIQUE INDEX "org_data_domains_hospital_id_domain_key_key" ON "core"."org_data_domains"("hospital_id", "domain_key");

-- CreateIndex
CREATE INDEX "org_user_branch_access_hospital_id_user_id_idx" ON "core"."org_user_branch_access"("hospital_id", "user_id");

-- CreateIndex
CREATE INDEX "org_user_branch_access_hospital_id_branch_id_idx" ON "core"."org_user_branch_access"("hospital_id", "branch_id");

-- CreateIndex
CREATE UNIQUE INDEX "org_user_branch_access_user_id_branch_id_from_at_key" ON "core"."org_user_branch_access"("user_id", "branch_id", "from_at");

-- CreateIndex
CREATE INDEX "org_cross_branch_access_log_hospital_id_patient_id_occurred_idx" ON "core"."org_cross_branch_access_log"("hospital_id", "patient_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "org_cross_branch_access_log_hospital_id_actor_user_id_occur_idx" ON "core"."org_cross_branch_access_log"("hospital_id", "actor_user_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "org_cross_branch_access_log_hospital_id_basis_occurred_at_idx" ON "core"."org_cross_branch_access_log"("hospital_id", "basis", "occurred_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "org_branch_onboarding_branch_id_key" ON "core"."org_branch_onboarding"("branch_id");

-- CreateIndex
CREATE INDEX "org_branch_onboarding_hospital_id_idx" ON "core"."org_branch_onboarding"("hospital_id");

-- CreateIndex
CREATE UNIQUE INDEX "org_residency_policies_hospital_id_from_zone_to_zone_effect_key" ON "core"."org_residency_policies"("hospital_id", "from_zone", "to_zone", "effective_from");

-- AddForeignKey
ALTER TABLE "core"."role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "core"."roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."role_permissions" ADD CONSTRAINT "role_permissions_permission_key_fkey" FOREIGN KEY ("permission_key") REFERENCES "core"."permissions"("key") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "core"."roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."access_requests" ADD CONSTRAINT "access_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."access_requests" ADD CONSTRAINT "access_requests_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "core"."roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."access_review_items" ADD CONSTRAINT "access_review_items_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "core"."access_reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."password_history" ADD CONSTRAINT "password_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."settings" ADD CONSTRAINT "settings_key_fkey" FOREIGN KEY ("key") REFERENCES "core"."setting_definitions"("key") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."numbering_allocations" ADD CONSTRAINT "numbering_allocations_series_id_fkey" FOREIGN KEY ("series_id") REFERENCES "core"."numbering_series"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."hospitals" ADD CONSTRAINT "hospitals_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "core"."org_groups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."branches" ADD CONSTRAINT "branches_hospital_id_fkey" FOREIGN KEY ("hospital_id") REFERENCES "core"."hospitals"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."branches" ADD CONSTRAINT "branches_parent_branch_id_fkey" FOREIGN KEY ("parent_branch_id") REFERENCES "core"."branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."org_units" ADD CONSTRAINT "org_units_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "core"."branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."org_branch_registrations" ADD CONSTRAINT "org_branch_registrations_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "core"."branches"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."org_user_branch_access" ADD CONSTRAINT "org_user_branch_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."org_user_branch_access" ADD CONSTRAINT "org_user_branch_access_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "core"."branches"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "core"."org_branch_onboarding" ADD CONSTRAINT "org_branch_onboarding_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "core"."branches"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ─────────────────────────────────────────────────────────────────────────────
-- ROLLBACK:
--   This is the initial migration; rolling back means dropping the four schemas
--   it creates. Safe ONLY before any tenant data exists.
--
--   DROP SCHEMA IF EXISTS "analytics" CASCADE;
--   DROP SCHEMA IF EXISTS "integration" CASCADE;
--   DROP SCHEMA IF EXISTS "mdm" CASCADE;
--   DROP SCHEMA IF EXISTS "core" CASCADE;
--
--   `ext` is NOT dropped: it is owned by infrastructure, not by migrations.
--
--   Once a tenant is live this migration is not reversible, and per docs/09 §16
--   that fact belongs in the release note rather than being discovered during an
--   incident. Every release after Phase 0 uses expand/contract (docs/10 §6) so
--   rollback never requires a database restore.
-- ─────────────────────────────────────────────────────────────────────────────
