-- ─────────────────────────────────────────────────────────────────────────────
-- Row-Level Security
--
-- This file is the reason the product can claim tenant isolation at all.
-- docs/03 §RLS, docs/04 §4, EN-041 §3.3, and the non-negotiable test suite in
-- docs/09 §3.1 — in particular case 5: "Run a raw repository query without
-- `SET LOCAL app.hospital_id` → RLS must return zero rows (proves the policy,
-- not the app guard, is doing the work)."
--
-- Two design choices carry that guarantee:
--
--  1. `current_setting(..., true)` — the `true` means "missing is NULL, not an
--     error". A NULL tenant makes every predicate NULL, which is not TRUE, so the
--     row is filtered. Default-deny therefore comes from SQL semantics rather
--     than from remembering to write a guard. Using `current_setting(name)`
--     without the flag would raise instead, and an exception is a *louder* but
--     less safe failure mode: a caller could catch it.
--
--  2. Every policy has BOTH `USING` (what you can read) and `WITH CHECK` (what
--     you can write). EN-041 §3.3.3 calls out the omission of `WITH CHECK` as
--     "a common oversight that makes read isolation useless" — you could not read
--     another branch's row, but you could create one there.
--
-- The policies are generated by iterating the catalogue rather than hand-written
-- 90 times, so a table added in a later phase cannot be forgotten. `pg_policies`
-- still shows the concrete policy for any table when an assessor asks.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── session-scope accessors ──────────────────────────────────────────────────
-- STABLE + PARALLEL SAFE so the planner treats each as a per-statement constant
-- and can still use an index. EN-041 §13: "an RLS-induced full scan on a
-- 100 M-row table is the classic multi-tenant failure and is a CI check."

CREATE OR REPLACE FUNCTION core.current_hospital_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE
AS $$ SELECT NULLIF(current_setting('app.hospital_id', true), '')::uuid $$;

CREATE OR REPLACE FUNCTION core.current_user_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE
AS $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$;

CREATE OR REPLACE FUNCTION core.current_scope() RETURNS text
LANGUAGE sql STABLE PARALLEL SAFE
AS $$ SELECT COALESCE(NULLIF(current_setting('app.scope', true), ''), 'branch') $$;

-- Branches this session may touch. Empty array (not NULL) when unset, so
-- `= ANY(...)` yields false rather than NULL — same outcome, clearer intent.
CREATE OR REPLACE FUNCTION core.current_branch_ids() RETURNS uuid[]
LANGUAGE sql STABLE PARALLEL SAFE
AS $$
  SELECT COALESCE(
    NULLIF(current_setting('app.branch_ids', true), '')::uuid[],
    ARRAY[]::uuid[]
  )
$$;

-- EN-041 §3.3.4: group-scoped roles get a widened hospital set. Ordinary roles
-- see exactly one hospital, so cross-tenant reads are impossible for them.
CREATE OR REPLACE FUNCTION core.accessible_hospital_ids() RETURNS uuid[]
LANGUAGE sql STABLE PARALLEL SAFE
AS $$
  SELECT CASE
    WHEN core.current_scope() = 'group'
      THEN COALESCE(NULLIF(current_setting('app.hospital_ids', true), '')::uuid[], ARRAY[]::uuid[])
    WHEN core.current_hospital_id() IS NOT NULL
      THEN ARRAY[core.current_hospital_id()]
    ELSE ARRAY[]::uuid[]
  END
$$;

COMMENT ON FUNCTION core.accessible_hospital_ids() IS
  'The tenant set for this transaction. Empty when app.hospital_id is unset, which is what makes RLS default-deny (docs/09 §3.1 case 5).';

-- ── policy generation ────────────────────────────────────────────────────────
DO $$
DECLARE
  r                record;
  v_has_hospital   boolean;
  v_hospital_null  boolean;
  v_has_branch     boolean;
  v_using          text;
  v_check          text;
  v_count          int := 0;
BEGIN
  FOR r IN
    SELECT n.nspname AS schema_name, c.relname AS table_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN ('core', 'mdm', 'integration')
      -- 'r' = ordinary table, 'p' = partitioned parent. Partitions ('r' with a
      -- parent) inherit the parent's policy when queried through it, and
      -- core.ensure_month_partition() enables RLS on each child as well.
      AND c.relkind IN ('r', 'p')
      AND c.relispartition = false
      AND c.relname NOT LIKE '\_prisma%'
    ORDER BY n.nspname, c.relname
  LOOP
    SELECT
      count(*) FILTER (WHERE column_name = 'hospital_id') > 0,
      bool_or(column_name = 'hospital_id' AND is_nullable = 'YES'),
      count(*) FILTER (WHERE column_name = 'branch_id') > 0
    INTO v_has_hospital, v_hospital_null, v_has_branch
    FROM information_schema.columns
    WHERE table_schema = r.schema_name AND table_name = r.table_name;

    EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', r.schema_name, r.table_name);

    IF v_has_hospital AND NOT v_hospital_null THEN
      -- ── Tenant-scoped table ────────────────────────────────────────────────
      v_using := 'hospital_id = ANY (core.accessible_hospital_ids())';

      IF v_has_branch THEN
        -- Branch-isolated. A NULL branch_id means "applies to every branch the
        -- user can already reach" (a hospital-level setting), so it is readable;
        -- a non-NULL branch_id must be one of the granted branches.
        -- EN-041 §14 AC-1: a Branch-A user querying Branch B gets zero rows.
        v_using := v_using || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))';
      END IF;

      -- Writes are held to the same predicate: EN-041 §14 AC-3 requires an INSERT
      -- carrying another branch's id to be rejected by the database, not by code.
      v_check := v_using;

    ELSIF v_has_hospital AND v_hospital_null THEN
      -- ── Mixed table: system rows (hospital_id IS NULL) plus tenant rows ─────
      -- e.g. the 64 system role templates, global feature flags, default audit
      -- field policies. System rows are readable by everyone and writable by
      -- nobody through the application role.
      v_using := '(hospital_id IS NULL OR hospital_id = ANY (core.accessible_hospital_ids()))';
      IF v_has_branch THEN
        v_using := v_using || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))';
      END IF;
      -- A tenant may only ever write its OWN rows; it can read the system ones.
      v_check := 'hospital_id = ANY (core.accessible_hospital_ids())';
      IF v_has_branch THEN
        v_check := v_check || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))';
      END IF;

    ELSE
      -- ── Global reference table (no tenant column) ──────────────────────────
      -- `core.permissions`, `core.setting_definitions`: catalogues synced from
      -- packages/contracts at boot. Readable by any authenticated session,
      -- writable only by the migration role (which owns them and bypasses RLS).
      v_using := 'true';
      v_check := 'false';
    END IF;

    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I.%I', r.schema_name, r.table_name);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I.%I FOR ALL TO hms_app USING (%s) WITH CHECK (%s)',
      r.schema_name, r.table_name, v_using, v_check
    );

    -- The read-only analytics role gets the same visibility, no write path at all.
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_ro ON %I.%I', r.schema_name, r.table_name);
    EXECUTE format(
      'CREATE POLICY tenant_isolation_ro ON %I.%I FOR SELECT TO hms_readonly USING (%s)',
      r.schema_name, r.table_name, v_using
    );

    v_count := v_count + 1;
  END LOOP;

  RAISE NOTICE 'Row-level security enabled with tenant policies on % tables', v_count;
END
$$;

-- ── RLS on partitions created later ──────────────────────────────────────────
-- Extend the maintenance function so every new monthly partition is protected
-- the moment it exists. Belt and braces: queries go through the parent, but a
-- direct partition query (a support engineer, a restore-to-scratch) is covered too.
CREATE OR REPLACE FUNCTION core.ensure_month_partition(
  p_schema      text,
  p_table       text,
  p_month_start date
) RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  v_partition  text;
  v_from       date := date_trunc('month', p_month_start)::date;
  v_to         date := (date_trunc('month', p_month_start) + interval '1 month')::date;
  v_qualified  text;
  v_using      text;
  v_has_branch boolean;
BEGIN
  v_partition := format('%s_%s', p_table, to_char(v_from, 'YYYYMM'));
  v_qualified := format('%I.%I', p_schema, v_partition);

  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = p_schema AND c.relname = v_partition
  ) THEN
    RETURN v_partition;
  END IF;

  EXECUTE format(
    'CREATE TABLE %s PARTITION OF %I.%I FOR VALUES FROM (%L) TO (%L)',
    v_qualified, p_schema, p_table, v_from, v_to
  );

  SELECT count(*) FILTER (WHERE column_name = 'branch_id') > 0
  INTO v_has_branch
  FROM information_schema.columns
  WHERE table_schema = p_schema AND table_name = p_table;

  v_using := 'hospital_id = ANY (core.accessible_hospital_ids())';
  IF v_has_branch THEN
    v_using := v_using || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))';
  END IF;

  EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', v_qualified);
  EXECUTE format('CREATE POLICY tenant_isolation ON %s FOR ALL TO hms_app USING (%s) WITH CHECK (%s)',
                 v_qualified, v_using, v_using);
  EXECUTE format('CREATE POLICY tenant_isolation_ro ON %s FOR SELECT TO hms_readonly USING (%s)',
                 v_qualified, v_using);
  EXECUTE format('GRANT SELECT, INSERT ON %s TO hms_app', v_qualified);
  EXECUTE format('GRANT SELECT ON %s TO hms_readonly', v_qualified);

  -- Storage parameters belong to leaf partitions, never to the parent, so every
  -- new month is tuned as it is created (see the previous migration for why).
  PERFORM core.apply_partition_storage_params(
    v_qualified,
    CASE WHEN p_table IN ('audit_log', 'login_audit', 'org_cross_branch_access_log')
         THEN 'append_only' ELSE 'churny' END
  );

  RETURN v_partition;
END;
$$;

-- ── the self-test EN-041 §6 exposes as `GET /org/rls/self-test` ──────────────
-- Returns one row per table with its policy status. Used by the branch go-live
-- smoke test (EN-041 §3.9.9), by the integration suite, and by an assessor who
-- asks "prove isolation is on".
CREATE OR REPLACE VIEW core.v_rls_coverage AS
SELECT
  n.nspname                                        AS schema_name,
  c.relname                                        AS table_name,
  c.relrowsecurity                                 AS rls_enabled,
  c.relforcerowsecurity                            AS rls_forced,
  count(p.polname) FILTER (WHERE p.polname IS NOT NULL) AS policy_count,
  bool_or(p.polname = 'tenant_isolation')          AS has_tenant_policy,
  -- A policy without WITH CHECK is the dangerous half-measure EN-041 §3.3.3 warns
  -- about: reads are isolated but writes are not.
  bool_or(p.polname = 'tenant_isolation' AND p.polwithcheck IS NOT NULL) AS has_write_check,
  EXISTS (
    SELECT 1 FROM information_schema.columns col
    WHERE col.table_schema = n.nspname AND col.table_name = c.relname
      AND col.column_name = 'hospital_id'
  )                                                AS is_tenant_scoped
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_policy p ON p.polrelid = c.oid
WHERE n.nspname IN ('core', 'mdm', 'integration')
  AND c.relkind IN ('r', 'p')
  AND c.relispartition = false
  AND c.relname NOT LIKE '\_prisma%'
GROUP BY n.nspname, c.relname, c.relrowsecurity, c.relforcerowsecurity, c.oid;

COMMENT ON VIEW core.v_rls_coverage IS
  'One row per application table with its RLS status. `has_tenant_policy` false or `has_write_check` false on a tenant-scoped table is a release-blocking defect (docs/09 §3.1).';

GRANT SELECT ON core.v_rls_coverage TO hms_app, hms_readonly;

-- ─────────────────────────────────────────────────────────────────────────────
-- ROLLBACK:
--   Disabling RLS removes tenant isolation entirely and must never be done on a
--   live multi-tenant database. For a local reset only:
--
--   DO $$ DECLARE r record; BEGIN
--     FOR r IN SELECT n.nspname, c.relname FROM pg_class c
--              JOIN pg_namespace n ON n.oid = c.relnamespace
--              WHERE n.nspname IN ('core','mdm','integration') AND c.relkind IN ('r','p')
--     LOOP
--       EXECUTE format('ALTER TABLE %I.%I DISABLE ROW LEVEL SECURITY', r.nspname, r.relname);
--     END LOOP;
--   END $$;
--   DROP VIEW IF EXISTS core.v_rls_coverage;
--   DROP FUNCTION IF EXISTS core.accessible_hospital_ids, core.current_branch_ids,
--     core.current_scope, core.current_user_id, core.current_hospital_id;
-- ─────────────────────────────────────────────────────────────────────────────
