import { Inject, Injectable } from '@nestjs/common';
import { ProblemType, newId, type Page } from '@vims/contracts';
import { AuditService } from '../../../core/audit/audit.service.js';
import { getContext } from '../../../core/context/request-context.js';
import { DatabaseService, type TransactionClient } from '../../../core/db/database.service.js';
import { NumberingService } from '../../../core/numbering/numbering.service.js';
import { OutboxService } from '../../../core/outbox/outbox.service.js';
import { CursorService } from '../../../core/pagination/cursor.service.js';
import { AppError } from '../../../core/problem/app-error.js';
import { currentTenantContext } from '../../../core/tenancy/tenant-context.js';
import { withDatabaseRefusals } from './radiology.errors.js';
import { radiologyEvent } from './radiology.events.js';
import type {
  CancelRadOrderRequest,
  CheckInRequest,
  CreateAppointmentRequest,
  CreateRadOrderRequest,
  PublishMwlRequest,
  RadOrderQuery,
  SafetyScreenRequest,
  WithdrawMwlRequest,
} from './radiology.schemas.js';
import type { RadOrderItemView, RadOrderView } from './radiology.types.js';

/**
 * OP-008 §3.1–§3.3.1 — the imaging order, its schedule and the modality
 * worklist.
 *
 * Four things about this service are not CRUD, and each one is a rule from
 * `OP-008 §5` that the database also holds:
 *
 * **The accession number and the Study Instance UID are minted here, once.**
 * `EN-035 §5` is explicit that both are generated by the RIS and never by the
 * modality: they are the join key across the HMS, the worklist and the archive,
 * and a modality that invents its own produces a study nothing can claim. The
 * accession comes from the `RAD_ACC` numbering series inside the caller's
 * transaction, so an order that fails after allocating gives the number back.
 * The UID is a `2.25.` OID derived from a fresh UUID — the form DICOM PS3.5 §B.2
 * blesses precisely so a site needs no registered OID arc before it can scan.
 *
 * **The statutory flags are not accepted from the client.** `is_pcpndt` and
 * `is_ionising` are stamped onto the order line by `rad.enforce_procedure_safety
 * _flags()` from the procedure master, on INSERT, and snapshotted there so a
 * later master edit cannot lift a Form F or a dose obligation off a study
 * already performed under it. This service reads the master for the display
 * fields and lets the trigger own the two that matter.
 *
 * **The MRI and contrast gates are status gates, not warnings.** The CHECKs on
 * `rad_orders` refuse to let an order with an unsafe implant, or a documented
 * iodinated-contrast allergy on a contrast study, reach `scheduled` without a
 * named override or a premedication protocol. So scheduling is where they bite,
 * which is where OP-008 §14 AC-3 and AC-10 put them.
 *
 * **A worklist entry is withdrawn, not deleted.** `EN-035 §5` gives it sixty
 * seconds after a cancellation, "so a patient is never scanned against a
 * cancelled order", and the withdrawal carries a time and a reason.
 */
@Injectable()
export class RadOrdersService {
  constructor(
    @Inject(DatabaseService) private readonly db: DatabaseService,
    @Inject(AuditService) private readonly audit: AuditService,
    @Inject(OutboxService) private readonly outbox: OutboxService,
    @Inject(NumberingService) private readonly numbering: NumberingService,
    @Inject(CursorService) private readonly cursors: CursorService,
  ) {}

  // ── create ────────────────────────────────────────────────────────────────

  async create(body: CreateRadOrderRequest): Promise<RadOrderView> {
    const ctx = getContext();
    const branchId = body.branchId ?? ctx.branchId;
    if (branchId === null) {
      throw AppError.conflict(
        'This session is not acting in a branch, and an imaging order belongs to one. Choose a branch and try again.',
      );
    }

    const id = newId();
    await withDatabaseRefusals(() =>
      this.db.withTenant(currentTenantContext(), async (tx) => {
        await this.assertPatientVisible(tx, body.patientId);

        const procedures = await this.loadProcedures(
          tx,
          body.items.map((i) => i.procedureKey),
        );

        const allocation = await this.numbering.allocate(tx, {
          key: 'RAD_ACC',
          branchId,
          refType: 'rad.rad_orders',
          refId: id,
        });

        const contrastRequired = body.items.some((i) => i.contrast);
        const tatMinutes = Math.min(
          ...procedures.map((p) => tatFor(p, body.priority)).filter((m): m is number => m !== null),
          Number.POSITIVE_INFINITY,
        );

        await tx.query(
          `INSERT INTO rad.rad_orders (
             id, hospital_id, branch_id, accession_no, patient_id,
             visit_id, admission_id, er_visit_id, encounter_id, clinical_order_id,
             source, ordering_user_id, ordering_practitioner_key, external_referrer,
             priority, status, clinical_indication, questions_to_answer, icd_codes,
             is_mlc, transport_mode, isolation, contrast_required,
             tat_due_at, created_by, updated_by, updated_at
           ) VALUES (
             $1, $2, $3, $4, $5,
             $6, $7, $8, $9, $10,
             $11::rad."RadOrderSource", $12, $13, $14,
             $15::rad."RadPriority", 'placed', $16, $17, $18::text[],
             $19, $20, $21, $22,
             CASE WHEN $23::int IS NULL THEN NULL ELSE now() + ($23::int || ' minutes')::interval END,
             $12, $12, now()
           )`,
          [
            id,
            ctx.hospitalId,
            branchId,
            allocation.formatted,
            body.patientId,
            body.visitId ?? null,
            body.admissionId ?? null,
            body.erVisitId ?? null,
            body.encounterId ?? null,
            body.clinicalOrderId ?? null,
            body.source,
            ctx.userId,
            await this.practitionerKeyOf(tx, ctx.userId),
            body.externalReferrer ?? null,
            body.priority,
            body.clinicalIndication,
            body.questionsToAnswer ?? null,
            body.icdCodes,
            body.isMlc,
            body.transportMode ?? null,
            body.isolation ?? null,
            contrastRequired,
            Number.isFinite(tatMinutes) ? tatMinutes : null,
          ],
        );

        let lineNo = 0;
        for (const item of body.items) {
          lineNo += 1;
          const procedure = procedures.find((p) => p.record_key === item.procedureKey);
          if (procedure === undefined) throw AppError.notFound('The imaging procedure');

          await tx.query(
            `INSERT INTO rad.rad_order_items (
               id, hospital_id, order_id, line_no, procedure_key, procedure_code, procedure_name,
               modality, body_part_dicom, laterality, contrast, views, status,
               study_instance_uid, scheduled_procedure_step_id, tat_due_at,
               created_by, updated_by, updated_at
             ) VALUES (
               $1, $2, $3, $4, $5, $6, $7,
               $8::mdm."RadModality", $9, $10::clinical."Laterality", $11, $12::text[], 'placed',
               $13, $14,
               CASE WHEN $15::int IS NULL THEN NULL ELSE now() + ($15::int || ' minutes')::interval END,
               $16, $16, now()
             )`,
            [
              newId(),
              ctx.hospitalId,
              id,
              lineNo,
              item.procedureKey,
              procedure.code,
              procedure.name,
              procedure.modality,
              item.bodyPartDicom ?? procedure.body_part_dicom,
              item.laterality,
              item.contrast || procedure.contrast_default,
              item.views,
              newStudyInstanceUid(),
              `${allocation.formatted}-${String(lineNo)}`,
              tatFor(procedure, body.priority),
              ctx.userId,
            ],
          );
        }

        await this.writeTransition(tx, id, null, null, 'placed', null);

        await this.audit.write(tx, {
          action: 'insert',
          entity: 'rad.rad_orders',
          rowId: id,
          businessKey: allocation.formatted,
          dataClass: 'phi',
          patientId: body.patientId,
          encounterId: body.encounterId ?? null,
          before: null,
          after: {
            status: 'placed',
            priority: body.priority,
            item_count: body.items.length,
            modalities: [...new Set(procedures.map((p) => p.modality))],
          },
        });

        await this.outbox.publish(
          tx,
          radiologyEvent('rad.order.received', id, {
            orderId: id,
            accessionNo: allocation.formatted,
            patientId: body.patientId,
            encounterId: body.encounterId ?? null,
            orderingUserId: ctx.userId ?? '',
            modality: procedures[0]?.modality ?? 'OT',
            priority: body.priority === 'portable_stat' ? 'stat' : body.priority,
            clinicalIndication: body.clinicalIndication,
            pregnancyStatus: null,
            receivedAt: new Date().toISOString(),
          }),
        );
      }),
    );

    return this.get(id);
  }

  // ── safety screen (OP-008 §3.1.2) ─────────────────────────────────────────

  /**
   * Records the answers to the pregnancy, contrast and MRI questions.
   *
   * The overrides are stamped with the acting user, never taken from the body:
   * `OP-008 §5` allows a radiologist to proceed past an unsafe implant or a
   * documented contrast allergy, and the whole value of that permission is that
   * it names who exercised it. A client-supplied `overrideBy` would be a
   * signature field anybody could fill in.
   */
  async safetyScreen(id: string, body: SafetyScreenRequest): Promise<RadOrderView> {
    const ctx = getContext();
    const before = await this.load(id);

    await withDatabaseRefusals(() =>
      this.db.withTenant(currentTenantContext(), async (tx) => {
        await tx.query(
          `UPDATE rad.rad_orders SET
             pregnancy_status = COALESCE($2::clinical."PregnancyStatus", pregnancy_status),
             lmp_date         = COALESCE($3::date, lmp_date),
             pregnancy_checked_by = CASE WHEN $2::clinical."PregnancyStatus" IS NULL THEN pregnancy_checked_by ELSE $16 END,
             pregnancy_checked_at = CASE WHEN $2::clinical."PregnancyStatus" IS NULL THEN pregnancy_checked_at ELSE now() END,
             radiation_justification = COALESCE($4, radiation_justification),
             pregnancy_consent_doc_id = COALESCE($5::uuid, pregnancy_consent_doc_id),
             contrast_required = COALESCE($6::boolean, contrast_required),
             egfr = COALESCE($7::numeric, egfr),
             egfr_at = CASE WHEN $7::numeric IS NULL THEN egfr_at ELSE now() END,
             contrast_allergy_known = COALESCE($8::boolean, contrast_allergy_known),
             premed_protocol_key = COALESCE($9::uuid, premed_protocol_key),
             premed_ordered_at = CASE WHEN $9::uuid IS NULL THEN premed_ordered_at ELSE now() END,
             metformin_hold_advised = COALESCE($10::boolean, metformin_hold_advised),
             contrast_approved_by = CASE WHEN $11::text IS NULL THEN contrast_approved_by ELSE $16 END,
             contrast_approval_reason = COALESCE($11, contrast_approval_reason),
             mri_safety_completed = COALESCE($12::boolean, mri_safety_completed),
             mri_safety_answers = COALESCE($13::jsonb, mri_safety_answers),
             mri_unsafe_implant = COALESCE($14::boolean, mri_unsafe_implant),
             mri_override_by = CASE WHEN $15::text IS NULL THEN mri_override_by ELSE $16 END,
             mri_override_reason = COALESCE($15, mri_override_reason),
             sedation_required = COALESCE($17::boolean, sedation_required),
             updated_by = $16, updated_at = now(), version = version + 1
           WHERE id = $1`,
          [
            id,
            body.pregnancyStatus ?? null,
            body.lmpDate ?? null,
            body.radiationJustification ?? null,
            body.pregnancyConsentDocId ?? null,
            body.contrastRequired ?? null,
            body.egfr ?? null,
            body.contrastAllergyKnown ?? null,
            body.premedProtocolKey ?? null,
            body.metforminHoldAdvised ?? null,
            body.contrastApprovalReason ?? null,
            body.mriSafetyCompleted ?? null,
            body.mriSafetyAnswers === undefined ? null : JSON.stringify(body.mriSafetyAnswers),
            body.mriUnsafeImplant ?? null,
            body.mriOverrideReason ?? null,
            ctx.userId,
            body.sedationRequired ?? null,
          ],
        );

        await this.audit.write(tx, {
          action: 'update',
          entity: 'rad.rad_orders',
          rowId: id,
          businessKey: before.accession_no,
          dataClass: 'phi',
          patientId: before.patient_id,
          encounterId: before.encounter_id,
          before: {
            pregnancy_status: before.pregnancy_status,
            contrast_allergy_known: before.contrast_allergy_known,
            mri_unsafe_implant: before.mri_unsafe_implant,
          },
          after: {
            pregnancy_status: body.pregnancyStatus ?? before.pregnancy_status,
            contrast_allergy_known: body.contrastAllergyKnown ?? before.contrast_allergy_known,
            mri_unsafe_implant: body.mriUnsafeImplant ?? before.mri_unsafe_implant,
            mri_override: body.mriOverrideReason !== undefined,
            contrast_override: body.contrastApprovalReason !== undefined,
          },
        });
      }),
    );

    return this.get(id);
  }

  // ── schedule, arrive ──────────────────────────────────────────────────────

  async schedule(body: CreateAppointmentRequest): Promise<RadOrderView> {
    const ctx = getContext();
    const appointmentId = newId();
    let orderId = '';

    await withDatabaseRefusals(() =>
      this.db.withTenant(currentTenantContext(), async (tx) => {
        const item = await this.loadItem(tx, body.orderItemId);
        orderId = item.order_id;
        const room = await this.loadRoom(tx, body.roomId);

        // OP-008 §5: "Equipment with expired AERB licence or QA overdue → room
        // blocked for scheduling (override by RSO with reason)." The block is a
        // column somebody set with a reason; honouring it here is what makes
        // setting it mean anything.
        if (room.scheduling_blocked && room.scheduling_override_by === null) {
          throw new AppError(
            ProblemType.BUSINESS_RULE_VIOLATED,
            `${room.name} is blocked for scheduling: ${room.scheduling_block_reason ?? 'no reason recorded'}.`,
            {
              nextAction:
                'The Radiation Safety Officer can lift the block with a recorded reason, or book another room.',
              reference: 'OP-008 §5 — AERB licence and QA validity',
            },
          );
        }
        if (room.aerb_licence_valid_to !== null && room.aerb_licence_valid_to < new Date()) {
          throw new AppError(
            ProblemType.BUSINESS_RULE_VIOLATED,
            `The AERB licence for ${room.name} expired on ${room.aerb_licence_valid_to.toISOString().slice(0, 10)}. No new slots may be booked in it.`,
            { reference: 'AERB Safety Code AERB/RF-MED/SC-3 (Rev.1)' },
          );
        }

        await tx.query(
          `INSERT INTO rad.rad_appointments (
             id, hospital_id, branch_id, order_item_id, room_id, patient_id,
             start_at, end_at, status, created_by, updated_by, updated_at
           ) VALUES ($1, $2, $3, $4, $5, $6, $7::timestamptz, $8::timestamptz, 'booked', $9, $9, now())`,
          [
            appointmentId,
            ctx.hospitalId,
            item.branch_id,
            body.orderItemId,
            body.roomId,
            item.patient_id,
            body.startAt,
            body.endAt,
            ctx.userId,
          ],
        );

        await this.advance(tx, item.order_id, body.orderItemId, 'scheduled', null);

        await this.audit.write(tx, {
          action: 'insert',
          entity: 'rad.rad_appointments',
          rowId: appointmentId,
          businessKey: item.accession_no,
          dataClass: 'phi',
          patientId: item.patient_id,
          encounterId: null,
          before: null,
          after: { room_id: body.roomId, start_at: body.startAt },
        });

        await this.outbox.publish(
          tx,
          radiologyEvent('rad.order.scheduled', appointmentId, {
            appointmentId,
            orderId: item.order_id,
            patientId: item.patient_id,
            roomId: body.roomId,
            startsAt: new Date(body.startAt).toISOString(),
            scheduledBy: ctx.userId ?? '',
          }),
        );
      }),
    );

    return this.get(orderId);
  }

  async checkIn(id: string, body: CheckInRequest): Promise<RadOrderView> {
    const before = await this.load(id);

    await withDatabaseRefusals(() =>
      this.db.withTenant(currentTenantContext(), async (tx) => {
        await tx.query(
          `UPDATE rad.rad_appointments SET arrived_at = now(), status = 'arrived', updated_at = now()
            WHERE order_item_id IN (SELECT id FROM rad.rad_order_items WHERE order_id = $1)
              AND status IN ('booked', 'confirmed')`,
          [id],
        );
        await this.advance(tx, id, null, 'arrived', null);

        await this.audit.write(tx, {
          action: 'update',
          entity: 'rad.rad_orders',
          rowId: id,
          businessKey: before.accession_no,
          dataClass: 'phi',
          patientId: before.patient_id,
          encounterId: before.encounter_id,
          before: { status: before.status },
          after: { status: 'arrived' },
        });

        await this.outbox.publish(
          tx,
          radiologyEvent('rad.order.arrived', id, {
            orderId: id,
            patientId: before.patient_id,
            roomId: body.roomId ?? null,
            arrivedAt: new Date().toISOString(),
          }),
        );
      }),
    );

    return this.get(id);
  }

  // ── modality worklist (OP-008 §3.3.1, EN-008 §3) ──────────────────────────

  /**
   * Publishes the scheduled procedure step to the worklist the scanners query.
   *
   * `OP-008 §5`: "MWL is the only source of demographics on modalities". So the
   * entry carries the DICOM rendering of the patient's identity — including
   * `patient_sex_dicom`, which is the patient's own recorded sex and a required
   * DICOM PS3.3 (0010,0040) attribute. The PC-PNDT guard in `migration.sql §C.7`
   * is written specifically so that this lawful field is not caught by it, and
   * it is worth being explicit about the difference: the Act prohibits recording
   * or communicating the sex of a *foetus*, not the sex of the patient in front
   * of the scanner.
   */
  async publishMwl(orderItemId: string, body: PublishMwlRequest): Promise<{ readonly entryId: string }> {
    const ctx = getContext();
    const entryId = newId();

    await withDatabaseRefusals(() =>
      this.db.withTenant(currentTenantContext(), async (tx) => {
        const item = await this.loadItem(tx, orderItemId);
        const room = await this.loadRoom(tx, body.roomId);
        const patient = await tx.maybeOne<{
          uhid: string;
          full_name: string;
          dob: Date | null;
          gender: string;
        }>(`SELECT uhid, full_name, dob, gender::text AS gender FROM patient.patients WHERE id = $1`, [
          item.patient_id,
        ]);
        if (patient === undefined) throw AppError.notFound('The patient');
        if (item.study_instance_uid === null) {
          throw AppError.conflict('This order line has no Study Instance UID; it cannot be published.');
        }

        const scheduledAt = body.scheduledAt ?? new Date().toISOString();

        await tx.query(
          `INSERT INTO rad.pacs_mwl_entries (
             id, hospital_id, branch_id, order_item_id, accession_no, study_instance_uid,
             scheduled_procedure_step_id, patient_name_dicom, patient_id_dicom, patient_birth_date,
             patient_sex_dicom, modality_aet, modality, requested_procedure_id,
             requested_procedure_description, scheduled_at, expires_at, status, published_at,
             created_by, updated_by, updated_at
           ) VALUES (
             $1, $2, $3, $4, $5, $6,
             $7, $8, $9, $10::date,
             $11, $12, $13::mdm."RadModality", $14,
             $15, $16::timestamptz, $16::timestamptz + ($17 || ' hours')::interval, 'pending', now(),
             $18, $18, now()
           )
           ON CONFLICT (hospital_id, study_instance_uid) DO UPDATE SET
             modality_aet = EXCLUDED.modality_aet,
             scheduled_at = EXCLUDED.scheduled_at,
             expires_at = EXCLUDED.expires_at,
             status = 'pending',
             withdrawn_at = NULL,
             withdrawn_reason = NULL,
             published_at = now(),
             updated_at = now()`,
          [
            entryId,
            ctx.hospitalId,
            item.branch_id,
            orderItemId,
            item.accession_no,
            item.study_instance_uid,
            item.scheduled_procedure_step_id ?? item.accession_no,
            dicomPersonName(patient.full_name),
            patient.uhid,
            patient.dob === null ? null : patient.dob.toISOString().slice(0, 10),
            dicomSex(patient.gender),
            room.ae_title,
            item.modality,
            item.accession_no,
            item.procedure_name,
            scheduledAt,
            String(body.expiresInHours),
            ctx.userId,
          ],
        );

        await this.audit.write(tx, {
          action: 'insert',
          entity: 'rad.pacs_mwl_entries',
          rowId: entryId,
          businessKey: item.accession_no,
          dataClass: 'phi',
          patientId: item.patient_id,
          encounterId: null,
          before: null,
          after: { modality_aet: room.ae_title, study_instance_uid: item.study_instance_uid },
        });

        await this.outbox.publish(
          tx,
          radiologyEvent('rad.mwl.published', item.order_id, {
            orderId: item.order_id,
            accessionNo: item.accession_no,
            patientId: item.patient_id,
            roomId: body.roomId,
            expiresAt: new Date(
              new Date(scheduledAt).getTime() + body.expiresInHours * 3_600_000,
            ).toISOString(),
            publishedAt: new Date().toISOString(),
          }),
        );
        await this.outbox.publish(
          tx,
          radiologyEvent('pacs.mwl.created', entryId, {
            entryId,
            accessionNo: item.accession_no,
            patientId: item.patient_id,
            scheduledAt: new Date(scheduledAt).toISOString(),
          }),
        );
      }),
    );

    return { entryId };
  }

  async withdrawMwl(orderItemId: string, body: WithdrawMwlRequest): Promise<{ readonly withdrawn: number }> {
    let withdrawn = 0;

    await withDatabaseRefusals(() =>
      this.db.withTenant(currentTenantContext(), async (tx) => {
        const item = await this.loadItem(tx, orderItemId);
        const status = body.cause === 'completed' ? 'completed' : body.cause;
        const removed = await tx.rows<{ id: string }>(
          `UPDATE rad.pacs_mwl_entries
              SET status = $2,
                  withdrawn_at = CASE WHEN $2 IN ('cancelled', 'expired') THEN now() ELSE NULL END,
                  withdrawn_reason = CASE WHEN $2 IN ('cancelled', 'expired') THEN $3 ELSE NULL END,
                  updated_at = now()
            WHERE order_item_id = $1 AND status NOT IN ('cancelled', 'expired', 'completed')
            RETURNING id`,
          [orderItemId, status, body.reason],
        );
        withdrawn = removed.length;

        for (const row of removed) {
          await this.audit.write(tx, {
            action: 'update',
            entity: 'rad.pacs_mwl_entries',
            rowId: row.id,
            businessKey: item.accession_no,
            dataClass: 'phi',
            patientId: item.patient_id,
            encounterId: null,
            before: null,
            after: { status },
            reasonText: body.reason,
          });
          await this.outbox.publish(
            tx,
            radiologyEvent('pacs.mwl.removed', row.id, {
              entryId: row.id,
              accessionNo: item.accession_no,
              reason: body.cause === 'completed' ? 'performed' : body.cause,
              at: new Date().toISOString(),
            }),
          );
        }

        if (withdrawn > 0) {
          await this.outbox.publish(
            tx,
            radiologyEvent('rad.mwl.removed', item.order_id, {
              orderId: item.order_id,
              accessionNo: item.accession_no,
              reason: body.cause,
              removedAt: new Date().toISOString(),
            }),
          );
        }
      }),
    );

    return { withdrawn };
  }

  // ── cancel ────────────────────────────────────────────────────────────────

  /**
   * `OP-008 §5`: a cancellation after acquisition needs approval, "because the
   * exposure already happened" — the dose is in the patient whatever the order
   * says afterwards, and the charge reversal is a different decision from the
   * clinical one.
   */
  async cancel(id: string, body: CancelRadOrderRequest): Promise<RadOrderView> {
    const before = await this.load(id);
    const afterAcquisition = ['acquired', 'awaiting_report', 'preliminary', 'reported', 'amended'].includes(
      before.status,
    );

    if (['cancelled', 'rejected'].includes(before.status)) {
      throw new AppError(ProblemType.ALREADY_DECIDED, 'This imaging order is already cancelled.');
    }
    if (afterAcquisition && body.afterAcquisitionApprovedBy === undefined) {
      throw new AppError(
        ProblemType.APPROVAL_REQUIRED,
        'The images have already been acquired, so cancelling this order needs a named approval.',
        {
          clinicalImpact:
            'The exposure has happened. Cancelling the order does not undo it, and the dose record stays.',
          nextAction: 'Send the cancellation again with the approving radiologist recorded.',
        },
      );
    }

    await withDatabaseRefusals(() =>
      this.db.withTenant(currentTenantContext(), async (tx) => {
        await tx.query(
          `UPDATE rad.rad_order_items SET status = 'cancelled', cancel_reason = $2,
                  updated_by = $3, updated_at = now(), version = version + 1
            WHERE order_id = $1 AND status NOT IN ('cancelled', 'reported', 'amended')`,
          [id, body.reason, getContext().userId],
        );
        await tx.query(
          `UPDATE rad.rad_orders SET status = 'cancelled', cancelled_at = now(), cancel_reason = $2,
                  updated_by = $3, updated_at = now(), version = version + 1
            WHERE id = $1`,
          [id, body.reason, getContext().userId],
        );
        await this.writeTransition(tx, id, null, before.status, 'cancelled', body.reason);

        // EN-035 §5 gives this sixty seconds: a worklist entry that outlives its
        // order is how a patient is scanned against a cancelled request.
        const entries = await tx.rows<{ id: string }>(
          `UPDATE rad.pacs_mwl_entries
              SET status = 'cancelled', withdrawn_at = now(), withdrawn_reason = $2, updated_at = now()
            WHERE order_item_id IN (SELECT id FROM rad.rad_order_items WHERE order_id = $1)
              AND status NOT IN ('cancelled', 'expired', 'completed')
            RETURNING id`,
          [id, body.reason],
        );

        await this.audit.write(tx, {
          action: 'update',
          entity: 'rad.rad_orders',
          rowId: id,
          businessKey: before.accession_no,
          dataClass: 'phi',
          patientId: before.patient_id,
          encounterId: before.encounter_id,
          before: { status: before.status },
          after: { status: 'cancelled', after_acquisition: afterAcquisition },
          reasonText: body.reason,
        });

        await this.outbox.publish(
          tx,
          radiologyEvent('rad.order.cancelled', id, {
            orderId: id,
            patientId: before.patient_id,
            reason: body.reason,
            afterAcquisition,
            cancelledBy: getContext().userId ?? '',
            cancelledAt: new Date().toISOString(),
          }),
        );
        for (const row of entries) {
          await this.outbox.publish(
            tx,
            radiologyEvent('pacs.mwl.removed', row.id, {
              entryId: row.id,
              accessionNo: before.accession_no,
              reason: 'cancelled',
              at: new Date().toISOString(),
            }),
          );
        }
      }),
    );

    return this.get(id);
  }

  // ── reads ─────────────────────────────────────────────────────────────────

  async get(id: string): Promise<RadOrderView> {
    return this.db.withTenant(currentTenantContext(), async (tx) => {
      const header = await this.loadIn(tx, id);
      const items = await tx.rows<RadOrderItemRow>(ITEM_SELECT, [id]);
      return toOrderView(header, items);
    });
  }

  async list(query: RadOrderQuery): Promise<Page<RadOrderView>> {
    const ctx = getContext();
    const hospitalId = ctx.hospitalId ?? '';
    const resource = 'rad.orders';
    const limit = this.cursors.pageSize(query.limit);
    const after = this.cursors.start(query.cursor, { hospitalId, resource });

    return this.db.withTenant(currentTenantContext(), async (tx) => {
      const values: unknown[] = [];
      const bind = (value: unknown): string => `$${String(values.push(value))}`;
      const clauses: string[] = [];
      if (query.patientId !== undefined) clauses.push(`o.patient_id = ${bind(query.patientId)}::uuid`);
      if (query.status !== undefined) clauses.push(`o.status = ${bind(query.status)}::rad."RadOrderStatus"`);
      if (query.priority !== undefined)
        clauses.push(`o.priority = ${bind(query.priority)}::rad."RadPriority"`);
      if (query.modality !== undefined) {
        clauses.push(
          `EXISTS (SELECT 1 FROM rad.rad_order_items i WHERE i.order_id = o.id AND i.modality = ${bind(query.modality)}::mdm."RadModality")`,
        );
      }
      if (after !== null) {
        clauses.push(`(o.ordered_at, o.id) < (${bind(after.k[0])}::timestamptz, ${bind(after.id)}::uuid)`);
      }
      const where = clauses.length === 0 ? '' : `WHERE ${clauses.join(' AND ')}`;

      const rows = await tx.rows<RadOrderRow & { cursor_key: string }>(
        `${ORDER_SELECT} ${where}
          ORDER BY o.ordered_at DESC, o.id DESC
          LIMIT ${bind(limit + 1)}`,
        values,
      );

      const page = this.cursors.keysetPage<RadOrderRow>(rows, limit, {
        hospitalId,
        resource,
        direction: 'desc',
      });

      const ids = page.items.map((o) => o.id);
      const items = ids.length === 0 ? [] : await tx.rows<RadOrderItemRow>(`${ITEM_SELECT_MANY}`, [ids]);

      return {
        items: page.items.map((header) =>
          toOrderView(
            header,
            items.filter((i) => i.order_id === header.id),
          ),
        ),
        nextCursor: page.nextCursor,
        hasMore: page.hasMore,
      };
    });
  }

  // ── shared helpers, used by the exam and report services ──────────────────

  /**
   * Moves an order (and optionally one line) forward, writing the transition to
   * `rad_order_events`.
   *
   * The order's own status is the *least advanced* of its lines, so a two-line
   * order is not "reported" because one line is. `rad_order_events` is
   * `INSERT`-only (`migration.sql §D.1`), which is what makes the TAT clock in
   * `OP-008 §3.7` reconstructible rather than merely current.
   */
  async advance(
    tx: TransactionClient,
    orderId: string,
    orderItemId: string | null,
    to: string,
    reason: string | null,
  ): Promise<void> {
    const from = await tx.maybeOne<{ status: string }>(
      `SELECT status::text AS status FROM rad.rad_orders WHERE id = $1`,
      [orderId],
    );

    if (orderItemId !== null) {
      await tx.query(
        `UPDATE rad.rad_order_items SET status = $2::rad."RadOrderStatus",
                updated_by = $3, updated_at = now(), version = version + 1
          WHERE id = $1 AND status NOT IN ('cancelled', 'rejected')`,
        [orderItemId, to, getContext().userId],
      );
    } else {
      await tx.query(
        `UPDATE rad.rad_order_items SET status = $2::rad."RadOrderStatus",
                updated_by = $3, updated_at = now(), version = version + 1
          WHERE order_id = $1 AND status NOT IN ('cancelled', 'rejected')`,
        [orderId, to, getContext().userId],
      );
    }

    await tx.query(
      `UPDATE rad.rad_orders o
          SET status = COALESCE((
                SELECT i.status FROM rad.rad_order_items i
                 WHERE i.order_id = $1 AND i.status NOT IN ('cancelled', 'rejected')
                 ORDER BY array_position(
                   ARRAY['placed','on_hold_payment','on_hold_preauth','on_hold_safety','scheduled','arrived',
                         'in_progress','acquired','awaiting_report','preliminary','reported','amended']::text[],
                   i.status::text)
                 LIMIT 1
              ), o.status),
              updated_by = $2, updated_at = now(), version = o.version + 1
        WHERE o.id = $1 AND o.status NOT IN ('cancelled', 'rejected')`,
      [orderId, getContext().userId],
    );

    await this.writeTransition(tx, orderId, orderItemId, from?.status ?? null, to, reason);
  }

  async writeTransition(
    tx: TransactionClient,
    orderId: string,
    orderItemId: string | null,
    from: string | null,
    to: string,
    reason: string | null,
  ): Promise<void> {
    const ctx = getContext();
    await tx.query(
      `INSERT INTO rad.rad_order_events
         (id, hospital_id, order_id, order_item_id, from_status, to_status, reason, actor_user_id, actor_role, at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())`,
      [newId(), ctx.hospitalId, orderId, orderItemId, from, to, reason, ctx.userId, ctx.roleKeys[0] ?? null],
    );
  }

  async loadItem(tx: TransactionClient, orderItemId: string): Promise<RadOrderItemContext> {
    const row = await tx.maybeOne<RadOrderItemContext>(
      `SELECT i.id, i.order_id, i.procedure_name, i.modality::text AS modality, i.status::text AS status,
              i.study_instance_uid, i.scheduled_procedure_step_id, i.is_pcpndt, i.is_ionising,
              o.branch_id, o.patient_id, o.accession_no, o.encounter_id, o.priority::text AS priority,
              o.status::text AS order_status
         FROM rad.rad_order_items i
         JOIN rad.rad_orders o ON o.id = i.order_id
        WHERE i.id = $1`,
      [orderItemId],
    );
    if (row === undefined) throw AppError.notFound('The imaging order line');
    return row;
  }

  private async loadRoom(tx: TransactionClient, roomId: string): Promise<RadRoomRow> {
    const row = await tx.maybeOne<RadRoomRow>(
      `SELECT id, name, ae_title, status::text AS status, scheduling_blocked, scheduling_block_reason,
              scheduling_override_by, aerb_licence_valid_to, pcpndt_registration_no,
              pcpndt_registration_valid_to
         FROM rad.rad_modality_rooms WHERE id = $1`,
      [roomId],
    );
    if (row === undefined) throw AppError.notFound('The modality room');
    return row;
  }

  private async load(id: string): Promise<RadOrderRow> {
    return this.db.withTenant(currentTenantContext(), (tx) => this.loadIn(tx, id));
  }

  private async loadIn(tx: TransactionClient, id: string): Promise<RadOrderRow> {
    const row = await tx.maybeOne<RadOrderRow>(`${ORDER_SELECT} WHERE o.id = $1`, [id]);
    if (row === undefined) throw AppError.notFound('The imaging order');
    return row;
  }

  /** A patient in another hospital is filtered by RLS and reads as missing. */
  private async assertPatientVisible(tx: TransactionClient, patientId: string): Promise<void> {
    const row = await tx.maybeOne<{ id: string }>(
      `SELECT id FROM patient.patients WHERE id = $1 AND deleted_at IS NULL`,
      [patientId],
    );
    if (row === undefined) throw AppError.notFound('The patient');
  }

  private async practitionerKeyOf(tx: TransactionClient, userId: string | null): Promise<string | null> {
    if (userId === null) return null;
    const row = await tx.maybeOne<{ record_key: string }>(
      `SELECT record_key FROM mdm.mdm_practitioners
        WHERE user_id = $1 AND status = 'active' ORDER BY version DESC LIMIT 1`,
      [userId],
    );
    return row?.record_key ?? null;
  }

  private async loadProcedures(
    tx: TransactionClient,
    keys: readonly string[],
  ): Promise<readonly ProcedureRow[]> {
    const rows = await tx.rows<ProcedureRow>(
      `SELECT DISTINCT ON (record_key)
              record_key, code, name, modality::text AS modality, body_part_dicom, contrast_default,
              laterality_required, is_pcpndt, is_ionising,
              tat_routine_minutes, tat_urgent_minutes, tat_stat_minutes
         FROM mdm.mdm_rad_procedures
        WHERE record_key = ANY($1::uuid[])
          AND status = 'active'
          AND effective_from <= now()
          AND (effective_to IS NULL OR effective_to > now())
        ORDER BY record_key, effective_from DESC, version DESC`,
      [[...new Set(keys)]],
    );

    const missing = [...new Set(keys)].filter((k) => !rows.some((r) => r.record_key === k));
    if (missing.length > 0) {
      throw new AppError(
        ProblemType.RETIRED_MASTER_RECORD,
        'One of the imaging procedures on this request is not an active, effective-dated entry in the procedure master.',
        {
          nextAction: 'Pick the procedure from the catalogue rather than sending a key directly.',
        },
      );
    }
    return rows;
  }
}

// ── row shapes and projections ──────────────────────────────────────────────

const ORDER_SELECT = `
  SELECT o.id, o.accession_no, o.patient_id, o.branch_id, o.encounter_id,
         o.source::text AS source, o.priority::text AS priority, o.status::text AS status,
         o.billing_status::text AS billing_status, o.clinical_indication, o.is_mlc,
         o.pregnancy_status::text AS pregnancy_status, o.contrast_required, o.contrast_allergy_known,
         o.mri_unsafe_implant, o.ordered_at::text AS ordered_at, o.cancel_reason,
         o.ordered_at::text AS cursor_key
    FROM rad.rad_orders o`;

const ITEM_SELECT = `
  SELECT i.order_id, i.id, i.line_no, i.procedure_key, i.procedure_code, i.procedure_name,
         i.modality::text AS modality, i.laterality::text AS laterality, i.contrast,
         i.status::text AS status, i.study_instance_uid, i.scheduled_procedure_step_id,
         i.is_pcpndt, i.is_ionising
    FROM rad.rad_order_items i WHERE i.order_id = $1 ORDER BY i.line_no`;

const ITEM_SELECT_MANY = `
  SELECT i.order_id, i.id, i.line_no, i.procedure_key, i.procedure_code, i.procedure_name,
         i.modality::text AS modality, i.laterality::text AS laterality, i.contrast,
         i.status::text AS status, i.study_instance_uid, i.scheduled_procedure_step_id,
         i.is_pcpndt, i.is_ionising
    FROM rad.rad_order_items i WHERE i.order_id = ANY($1::uuid[]) ORDER BY i.line_no`;

interface RadOrderRow {
  readonly id: string;
  readonly accession_no: string;
  readonly patient_id: string;
  readonly branch_id: string;
  readonly encounter_id: string | null;
  readonly source: string;
  readonly priority: string;
  readonly status: string;
  readonly billing_status: string;
  readonly clinical_indication: string;
  readonly is_mlc: boolean;
  readonly pregnancy_status: string | null;
  readonly contrast_required: boolean;
  readonly contrast_allergy_known: boolean;
  readonly mri_unsafe_implant: boolean;
  readonly ordered_at: string;
  readonly cancel_reason: string | null;
}

interface RadOrderItemRow {
  readonly order_id: string;
  readonly id: string;
  readonly line_no: number;
  readonly procedure_key: string;
  readonly procedure_code: string;
  readonly procedure_name: string;
  readonly modality: string;
  readonly laterality: string;
  readonly contrast: boolean;
  readonly status: string;
  readonly study_instance_uid: string | null;
  readonly scheduled_procedure_step_id: string | null;
  readonly is_pcpndt: boolean;
  readonly is_ionising: boolean;
}

export interface RadOrderItemContext {
  readonly id: string;
  readonly order_id: string;
  readonly procedure_name: string;
  readonly modality: string;
  readonly status: string;
  readonly study_instance_uid: string | null;
  readonly scheduled_procedure_step_id: string | null;
  readonly is_pcpndt: boolean;
  readonly is_ionising: boolean;
  readonly branch_id: string;
  readonly patient_id: string;
  readonly accession_no: string;
  readonly encounter_id: string | null;
  readonly priority: string;
  readonly order_status: string;
}

interface RadRoomRow {
  readonly id: string;
  readonly name: string;
  readonly ae_title: string;
  readonly status: string;
  readonly scheduling_blocked: boolean;
  readonly scheduling_block_reason: string | null;
  readonly scheduling_override_by: string | null;
  readonly aerb_licence_valid_to: Date | null;
  readonly pcpndt_registration_no: string | null;
  readonly pcpndt_registration_valid_to: Date | null;
}

interface ProcedureRow {
  readonly record_key: string;
  readonly code: string;
  readonly name: string;
  readonly modality: string;
  readonly body_part_dicom: string | null;
  readonly contrast_default: boolean;
  readonly laterality_required: boolean;
  readonly is_pcpndt: boolean;
  readonly is_ionising: boolean;
  readonly tat_routine_minutes: number | null;
  readonly tat_urgent_minutes: number | null;
  readonly tat_stat_minutes: number | null;
}

function tatFor(procedure: ProcedureRow, priority: string): number | null {
  switch (priority) {
    case 'stat':
    case 'portable_stat':
      return procedure.tat_stat_minutes;
    case 'urgent':
      return procedure.tat_urgent_minutes;
    default:
      return procedure.tat_routine_minutes;
  }
}

/**
 * A DICOM Person Name (VR PN): five caret-delimited components, of which this
 * fills the family and given names. The modality displays this and nothing else,
 * which is why `OP-008 §5` makes the worklist the only source of demographics —
 * a technologist typing a name at the console is how one patient's images end up
 * under another's identity.
 */
function dicomPersonName(fullName: string): string {
  const parts = fullName.trim().split(/\s+/);
  if (parts.length <= 1) return `${fullName.trim()}^`;
  const family = parts[parts.length - 1] ?? '';
  const given = parts.slice(0, -1).join(' ');
  return `${family}^${given}`.slice(0, 200);
}

/** DICOM PS3.3 (0010,0040) Patient's Sex: M, F, O or empty. The patient's, never a foetus's. */
function dicomSex(gender: string): string | null {
  switch (gender) {
    case 'male':
      return 'M';
    case 'female':
      return 'F';
    case 'other':
      return 'O';
    default:
      return null;
  }
}

/**
 * A Study Instance UID in the `2.25.` arc.
 *
 * DICOM PS3.5 §B.2 defines `2.25.<uuid as an unsigned decimal integer>` as a
 * conformant UID derivable from a UUID with no registration. It matters that
 * this needs no configuration: the alternative is a per-hospital OID root that
 * somebody must obtain before the first scan, and a site that has not obtained
 * one yet would otherwise be tempted to let the modality generate the UID —
 * which `EN-035 §5` forbids, because then nothing in the RIS can claim the
 * study when it arrives.
 */
function newStudyInstanceUid(): string {
  const hex = newId().replace(/-/g, '');
  return `2.25.${BigInt(`0x${hex}`).toString(10)}`;
}

function toOrderView(header: RadOrderRow, items: readonly RadOrderItemRow[]): RadOrderView {
  return {
    id: header.id,
    accessionNo: header.accession_no,
    patientId: header.patient_id,
    branchId: header.branch_id,
    source: header.source,
    priority: header.priority,
    status: header.status,
    billingStatus: header.billing_status,
    clinicalIndication: header.clinical_indication,
    isMlc: header.is_mlc,
    pregnancyStatus: header.pregnancy_status,
    contrastRequired: header.contrast_required,
    contrastAllergyKnown: header.contrast_allergy_known,
    mriUnsafeImplant: header.mri_unsafe_implant,
    orderedAt: header.ordered_at,
    cancelReason: header.cancel_reason,
    items: items.map((i): RadOrderItemView => ({
      id: i.id,
      lineNo: i.line_no,
      procedureKey: i.procedure_key,
      procedureCode: i.procedure_code,
      procedureName: i.procedure_name,
      modality: i.modality,
      laterality: i.laterality,
      contrast: i.contrast,
      status: i.status,
      studyInstanceUid: i.study_instance_uid,
      scheduledProcedureStepId: i.scheduled_procedure_step_id,
      isPcpndt: i.is_pcpndt,
      isIonising: i.is_ionising,
    })),
  };
}
