export {
  bdi,
  escapeHtml,
  letterheadStyles,
  renderDuplicateMark,
  renderLetterhead,
  renderPrintFooter,
} from './letterhead.js';

export {
  a4DocumentPayloadSchema,
  a4DocumentTemplate,
  renderA4Document,
  type A4DocumentPayload,
} from './document.js';

export {
  encodeQr,
  formatInformation,
  generatorPolynomial,
  reedSolomonCodewords,
  renderQrSvg,
  versionInformation,
  type QrEcc,
  type QrOptions,
  type QrSvgOptions,
  type QrSymbol,
} from './qr.js';

export {
  HEIGHT,
  LATER_PAGE_BUDGET_MM,
  PAGE_BOX_MM,
  amendmentChangeSchema,
  amendmentSchema,
  assertReleaseConsistency,
  authBlockMm,
  authoriserSchema,
  buildVerifyUrl,
  closeDocument,
  firstPageBudgetMm,
  forbiddenInQr,
  linesFor,
  metaMm,
  openDocument,
  paginate,
  patientBannerMm,
  patientBannerSchema,
  proseMm,
  amendmentBlocks,
  renderAuthorisers,
  renderBlocks,
  renderEndOfReport,
  renderMetaGrid,
  renderPatientBanner,
  renderReportPages,
  renderStatusBanner,
  renderStatusSeal,
  renderVerifyBlock,
  reportStatusSchema,
  reportStyles,
  statusBannerMm,
  supersededSchema,
  verifySchema,
  type Amendment,
  type Authoriser,
  type ChromeShape,
  type PageBlock,
  type PaginateOptions,
  type PatientBanner,
  type ReportStatus,
  type ShellOptions,
  type VerifyBlock,
} from './report-shell.js';

export {
  isCriticalFlag,
  labCriticalValueSchema,
  labReportPayloadSchema,
  labReportTemplate,
  labResultGroupSchema,
  labResultRowSchema,
  labSpecimenSchema,
  renderLabReport,
  resultFlagSchema,
  type LabReportPayload,
  type LabResultRow,
  type ResultFlagKey,
} from './lab-report.js';

export {
  cumulativeAnalyteSchema,
  cumulativeCellSchema,
  cumulativeColumnSchema,
  labCumulativeReportPayloadSchema,
  labCumulativeReportTemplate,
  renderLabCumulativeReport,
  renderSparkline,
  trendDirection,
  type CumulativeAnalyte,
  type LabCumulativeReportPayload,
} from './lab-cumulative-report.js';

export {
  radContrastSchema,
  radCriticalFindingSchema,
  radDoseSchema,
  radFindingLevelSchema,
  radKeyImageSchema,
  radReportPayloadSchema,
  radReportTemplate,
  renderRadReport,
  studySummaryLine,
  type RadFindingLevel,
  type RadReportPayload,
} from './rad-report.js';
