-- ─────────────────────────────────────────────────────────────────────────────
-- Vim's HMS — Phase 5, OP-005: OP billing
--
-- `docs/prompts/phase-05-billing-rcm.md` §5.2. Eight new tables in `billing`,
-- joining the four Phase 1 already built for NC-001's cash counter (`payments`,
-- `payment_lines`, `advances`, `refunds`). Charges have been accumulating in
-- `billing.charge_intents` since Phase 2; this is what turns them into money.
--
-- Generated by `prisma migrate diff --from-url`, then post-processed to strip
-- the DropIndex statements Prisma emits for hand-written SQL it cannot see.
--
--   §A  row-level security
--   §B  the constraints that carry OP-005 §5's guarantees:
--         B.1  one master bill per OP visit
--         B.2  ONE CHARGE, ONE BILL LINE, ONCE — the idempotency index
--         B.3  Σ bill lines = bill total, verified by the database
--         B.4  a finalised bill is immutable
--         B.5  GST: intra-state splits CGST+SGST equally, inter-state is IGST,
--              and the three are mutually exclusive
--         B.6  requester ≠ approver on every discount
--         B.7  gapless invoice numbering per series per financial year
--   §C  grants, and the DELETE revoke that makes "never hard-deleted" true
-- ─────────────────────────────────────────────────────────────────────────────

-- CreateEnum
CREATE TYPE "billing"."BillType" AS ENUM ('op', 'ip', 'er', 'daycare', 'pharmacy_otc', 'lab_walkin', 'package', 'misc');

-- CreateEnum
CREATE TYPE "billing"."BillStatus" AS ENUM ('draft', 'open', 'finalized', 'partially_paid', 'paid', 'cancelled', 'void');

-- CreateEnum
CREATE TYPE "billing"."BillPayerType" AS ENUM ('self', 'insurance', 'corporate', 'scheme', 'staff', 'charity');

-- CreateEnum
CREATE TYPE "billing"."InvoiceDocType" AS ENUM ('tax_invoice', 'bill_of_supply', 'credit_note', 'debit_note', 'advance_receipt_voucher');

-- CreateEnum
CREATE TYPE "billing"."InvoiceStatus" AS ENUM ('issued', 'cancelled');

-- CreateEnum
CREATE TYPE "billing"."EInvoiceStatus" AS ENUM ('na', 'pending', 'generated', 'failed', 'cancelled');

-- CreateEnum
CREATE TYPE "billing"."BillItemType" AS ENUM ('consult', 'lab', 'rad', 'pharmacy', 'procedure', 'consumable', 'package', 'room', 'other');

-- CreateEnum
CREATE TYPE "billing"."BillItemStatus" AS ENUM ('unpaid', 'paid', 'credit', 'waived', 'cancelled', 'refunded');

-- CreateEnum
CREATE TYPE "billing"."BillPriceStatus" AS ENUM ('priced', 'missing', 'manual');

-- CreateEnum
CREATE TYPE "billing"."DiscountRequestStatus" AS ENUM ('pending', 'approved', 'rejected', 'withdrawn');

-- AlterTable
ALTER TABLE "queue"."queue_definitions" ALTER COLUMN "reset_time" SET DEFAULT '00:00:00'::time;

-- CreateTable
CREATE TABLE "billing"."bills" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "bill_no" VARCHAR(40) NOT NULL,
    "patient_id" UUID NOT NULL,
    "visit_id" UUID,
    "admission_id" UUID,
    "bill_type" "billing"."BillType" NOT NULL,
    "status" "billing"."BillStatus" NOT NULL DEFAULT 'draft',
    "payer_type" "billing"."BillPayerType" NOT NULL DEFAULT 'self',
    "payer_id" UUID,
    "policy_ref" VARCHAR(64),
    "preauth_ref" VARCHAR(64),
    "currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "gross_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "discount_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "taxable_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "cgst" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "sgst" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "igst" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "cess" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "round_off" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "net_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "paid_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "balance_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "patient_share" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "payer_share" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "estimate_id" UUID,
    "package_id" UUID,
    "finalized_at" TIMESTAMPTZ(6),
    "finalized_by" UUID,
    "cancelled_at" TIMESTAMPTZ(6),
    "cancelled_by" UUID,
    "cancel_reason" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,
    "version" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "bills_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billing"."bill_items" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "bill_id" UUID NOT NULL,
    "invoice_id" UUID,
    "department_id" UUID,
    "service_id" UUID,
    "item_type" "billing"."BillItemType" NOT NULL,
    "description" VARCHAR(300) NOT NULL,
    "hsn_sac" VARCHAR(16),
    "qty" DECIMAL(14,3) NOT NULL DEFAULT 1,
    "unit_price" DECIMAL(14,2) NOT NULL,
    "mrp" DECIMAL(14,2),
    "tariff_version_id" UUID,
    "tariff_item_id" UUID,
    "gross" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "discount_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "discount_reason_id" UUID,
    "discount_approved_by" UUID,
    "taxable_value" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "gst_rate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "cgst" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "sgst" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "igst" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "cess" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "is_exempt" BOOLEAN NOT NULL DEFAULT true,
    "net" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "status" "billing"."BillItemStatus" NOT NULL DEFAULT 'unpaid',
    "price_status" "billing"."BillPriceStatus" NOT NULL DEFAULT 'priced',
    "performing_doctor_id" UUID,
    "referring_doctor_id" UUID,
    "ordering_doctor_id" UUID,
    "source_module" VARCHAR(32) NOT NULL,
    "source_ref_id" UUID NOT NULL,
    "package_component" BOOLEAN NOT NULL DEFAULT false,
    "payer_covered" BOOLEAN NOT NULL DEFAULT false,
    "patient_share" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "payer_share" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "performed_at" TIMESTAMPTZ(6),
    "posted_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "bill_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billing"."invoices" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "invoice_no" VARCHAR(40) NOT NULL,
    "series_key" VARCHAR(40) NOT NULL,
    "bill_id" UUID NOT NULL,
    "doc_type" "billing"."InvoiceDocType" NOT NULL,
    "is_b2b" BOOLEAN NOT NULL DEFAULT false,
    "recipient_name" VARCHAR(200),
    "recipient_gstin" VARCHAR(20),
    "place_of_supply_state" VARCHAR(2),
    "reverse_charge" BOOLEAN NOT NULL DEFAULT false,
    "irn" VARCHAR(80),
    "irn_ack_no" VARCHAR(40),
    "irn_ack_date" TIMESTAMPTZ(6),
    "signed_qr" TEXT,
    "einvoice_status" "billing"."EInvoiceStatus" NOT NULL DEFAULT 'na',
    "status" "billing"."InvoiceStatus" NOT NULL DEFAULT 'issued',
    "issued_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cancelled_reason" TEXT,
    "original_invoice_id" UUID,
    "pdf_file_id" UUID,
    "sha256" VARCHAR(64),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "invoices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billing"."discount_requests" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "bill_id" UUID NOT NULL,
    "bill_item_id" UUID,
    "requested_by" UUID NOT NULL,
    "pct" DECIMAL(5,2),
    "amount" DECIMAL(14,2),
    "reason_code" VARCHAR(40) NOT NULL,
    "justification" TEXT,
    "approver_role" VARCHAR(64),
    "approved_by" UUID,
    "decided_at" TIMESTAMPTZ(6),
    "status" "billing"."DiscountRequestStatus" NOT NULL DEFAULT 'pending',
    "before_snapshot" JSONB,
    "after_snapshot" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "discount_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billing"."payer_bill_splits" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "bill_id" UUID NOT NULL,
    "payer_id" UUID,
    "covered_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "copay" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "deductible" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "preauth_id" UUID,
    "claim_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "payer_bill_splits_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billing"."gst_profiles" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "gstin" VARCHAR(20) NOT NULL,
    "legal_name" VARCHAR(200) NOT NULL,
    "trade_name" VARCHAR(200),
    "address" TEXT NOT NULL,
    "state_code" VARCHAR(2) NOT NULL,
    "einvoice_enabled" BOOLEAN NOT NULL DEFAULT false,
    "dynamic_qr" BOOLEAN NOT NULL DEFAULT false,
    "effective_from" DATE NOT NULL,
    "effective_to" DATE,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "gst_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billing"."discount_matrix" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "role_key" VARCHAR(64) NOT NULL,
    "max_pct" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "max_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "needs_approval_from" VARCHAR(64),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "discount_matrix_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billing"."billing_exceptions" (
    "id" UUID NOT NULL,
    "hospital_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "exception_type" VARCHAR(48) NOT NULL,
    "ref_id" UUID,
    "amount" DECIMAL(14,2),
    "detail" TEXT,
    "detected_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" VARCHAR(24) NOT NULL DEFAULT 'open',
    "resolved_at" TIMESTAMPTZ(6),
    "resolved_by" UUID,

    CONSTRAINT "billing_exceptions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "bills_hospital_id_branch_id_status_created_at_idx" ON "billing"."bills"("hospital_id", "branch_id", "status", "created_at" DESC);

-- CreateIndex
CREATE INDEX "bills_hospital_id_patient_id_created_at_idx" ON "billing"."bills"("hospital_id", "patient_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "bills_hospital_id_visit_id_idx" ON "billing"."bills"("hospital_id", "visit_id");

-- CreateIndex
CREATE UNIQUE INDEX "bills_hospital_id_bill_no_key" ON "billing"."bills"("hospital_id", "bill_no");

-- CreateIndex
CREATE INDEX "bill_items_hospital_id_bill_id_idx" ON "billing"."bill_items"("hospital_id", "bill_id");

-- CreateIndex
CREATE INDEX "bill_items_hospital_id_performing_doctor_id_performed_at_idx" ON "billing"."bill_items"("hospital_id", "performing_doctor_id", "performed_at");

-- CreateIndex
CREATE INDEX "bill_items_hospital_id_price_status_idx" ON "billing"."bill_items"("hospital_id", "price_status");

-- CreateIndex
CREATE UNIQUE INDEX "bill_items_bill_id_source_module_source_ref_id_key" ON "billing"."bill_items"("bill_id", "source_module", "source_ref_id");

-- CreateIndex
CREATE INDEX "invoices_hospital_id_branch_id_issued_at_idx" ON "billing"."invoices"("hospital_id", "branch_id", "issued_at" DESC);

-- CreateIndex
CREATE INDEX "invoices_hospital_id_bill_id_idx" ON "billing"."invoices"("hospital_id", "bill_id");

-- CreateIndex
CREATE UNIQUE INDEX "invoices_hospital_id_series_key_invoice_no_key" ON "billing"."invoices"("hospital_id", "series_key", "invoice_no");

-- CreateIndex
CREATE INDEX "discount_requests_hospital_id_status_created_at_idx" ON "billing"."discount_requests"("hospital_id", "status", "created_at" DESC);

-- CreateIndex
CREATE INDEX "discount_requests_hospital_id_bill_id_idx" ON "billing"."discount_requests"("hospital_id", "bill_id");

-- CreateIndex
CREATE INDEX "payer_bill_splits_hospital_id_bill_id_idx" ON "billing"."payer_bill_splits"("hospital_id", "bill_id");

-- CreateIndex
CREATE UNIQUE INDEX "gst_profiles_hospital_id_branch_id_effective_from_key" ON "billing"."gst_profiles"("hospital_id", "branch_id", "effective_from");

-- CreateIndex
CREATE UNIQUE INDEX "discount_matrix_hospital_id_role_key_key" ON "billing"."discount_matrix"("hospital_id", "role_key");

-- CreateIndex
CREATE INDEX "billing_exceptions_hospital_id_status_detected_at_idx" ON "billing"."billing_exceptions"("hospital_id", "status", "detected_at" DESC);

-- AddForeignKey
ALTER TABLE "billing"."bill_items" ADD CONSTRAINT "bill_items_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "billing"."bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billing"."invoices" ADD CONSTRAINT "invoices_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "billing"."bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billing"."discount_requests" ADD CONSTRAINT "discount_requests_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "billing"."bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billing"."payer_bill_splits" ADD CONSTRAINT "payer_bill_splits_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "billing"."bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;



-- ═════════════════════════════════════════════════════════════════════════════
-- §A. ROW-LEVEL SECURITY
-- ═════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
  r record; v_has_hospital boolean; v_hospital_null boolean; v_has_branch boolean;
  v_using text; v_check text; v_count int := 0;
BEGIN
  FOR r IN
    SELECT n.nspname AS schema_name, c.relname AS table_name
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN ('core','mdm','patient','clinical','lab','rad','pharmacy','inventory','finance','queue','engage','billing','integration')
      AND c.relkind IN ('r','p') AND c.relispartition = false
      AND c.relname NOT LIKE '\_prisma%' AND c.relname <> 'cdss_safety_floor'
      AND NOT EXISTS (SELECT 1 FROM pg_policy p WHERE p.polrelid = c.oid AND p.polname = 'tenant_isolation')
    ORDER BY n.nspname, c.relname
  LOOP
    SELECT count(*) FILTER (WHERE column_name='hospital_id') > 0,
           bool_or(column_name='hospital_id' AND is_nullable='YES'),
           count(*) FILTER (WHERE column_name='branch_id') > 0
      INTO v_has_hospital, v_hospital_null, v_has_branch
      FROM information_schema.columns
     WHERE table_schema = r.schema_name AND table_name = r.table_name;

    EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', r.schema_name, r.table_name);

    IF v_has_hospital AND NOT v_hospital_null THEN
      v_using := 'hospital_id = ANY (core.accessible_hospital_ids())';
      IF v_has_branch THEN v_using := v_using || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))'; END IF;
      v_check := v_using;
    ELSIF v_has_hospital AND v_hospital_null THEN
      v_using := '(hospital_id IS NULL OR hospital_id = ANY (core.accessible_hospital_ids()))';
      IF v_has_branch THEN v_using := v_using || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))'; END IF;
      v_check := 'hospital_id = ANY (core.accessible_hospital_ids())';
      IF v_has_branch THEN v_check := v_check || ' AND (branch_id IS NULL OR branch_id = ANY (core.current_branch_ids()))'; END IF;
    ELSE
      v_using := 'false'; v_check := 'false';
    END IF;

    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I.%I', r.schema_name, r.table_name);
    EXECUTE format('CREATE POLICY tenant_isolation ON %I.%I FOR ALL TO hms_app USING (%s) WITH CHECK (%s)', r.schema_name, r.table_name, v_using, v_check);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_ro ON %I.%I', r.schema_name, r.table_name);
    EXECUTE format('CREATE POLICY tenant_isolation_ro ON %I.%I FOR SELECT TO hms_readonly USING (%s)', r.schema_name, r.table_name, v_using);
    v_count := v_count + 1;
  END LOOP;
  RAISE NOTICE 'RLS enabled on % new table(s)', v_count;
END $$;

DO $$
DECLARE v_missing text;
BEGIN
  SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ') INTO v_missing
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'billing' AND c.relkind IN ('r','p') AND c.relispartition = false
    AND (NOT c.relrowsecurity OR NOT EXISTS (SELECT 1 FROM pg_policy p WHERE p.polrelid=c.oid AND p.polname='tenant_isolation'));
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'OP-005 tables without RLS or a tenant policy: %', v_missing;
  END IF;
END $$;


-- ═════════════════════════════════════════════════════════════════════════════
-- §B. THE CONSTRAINTS OP-005 §5 DEPENDS ON
-- ═════════════════════════════════════════════════════════════════════════════

-- ── B.1  one master bill per OP visit ───────────────────────────────────────
--
-- OP-005 §5: "One master bill per OP visit." A second bill for one visit splits
-- a patient's money across two documents that nobody reconciles, and the patient
-- finds out at the counter. Partial, because cancelled and void bills legitimately
-- coexist with the replacement that supersedes them.
CREATE UNIQUE INDEX "uq_bills_one_per_visit"
  ON "billing"."bills" ("hospital_id", "visit_id")
  WHERE "visit_id" IS NOT NULL AND status NOT IN ('cancelled', 'void');

COMMENT ON INDEX "billing"."uq_bills_one_per_visit" IS
  'OP-005 §5: one master bill per OP visit. Cancelled and void bills are excluded so a corrected bill can replace one.';

-- ── B.2  ONE CHARGE, ONE BILL LINE, ONCE ────────────────────────────────────
--
-- `phase-05 §Constraints`, verbatim: "Charge intents carry an idempotency key
-- from the source event; a replayed event must never double-bill. Write the test
-- first." Exit gate 2 replays every charge event three times and expects the
-- bill unchanged. Prisma emitted this as `bill_items_bill_id_source_module_source_ref_id_key`;
-- the comment is what makes it survive a future refactor.
COMMENT ON INDEX "billing"."bill_items_bill_id_source_module_source_ref_id_key" IS
  'phase-05 exit gate 2. A replayed charge event conflicts here instead of adding a second line. This index IS the idempotency guarantee.';

-- ── B.3  Σ bill lines = bill total ──────────────────────────────────────────
--
-- Exit gate 10 asks for it. A report that checks it is a report somebody runs;
-- a trigger makes it something that cannot be false. Deferred to statement end
-- so a service may write the header and the lines in either order within one
-- transaction, which is the normal shape of "post these six charges".
CREATE OR REPLACE FUNCTION "billing".assert_bill_totals()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_bill_id uuid;
  v_lines numeric(14,2);
  v_header numeric(14,2);
  v_status "billing"."BillStatus";
BEGIN
  v_bill_id := COALESCE(NEW.id, OLD.id);

  SELECT status, net_amount INTO v_status, v_header
    FROM "billing"."bills" WHERE id = v_bill_id;

  -- A draft is mid-assembly by definition; only a presented bill must balance.
  IF v_status IS NULL OR v_status = 'draft' THEN RETURN NULL; END IF;

  SELECT COALESCE(sum(net), 0) INTO v_lines
    FROM "billing"."bill_items"
   WHERE bill_id = v_bill_id AND status <> 'cancelled';

  -- The round-off is a real rupee under Section 170, so it is part of the
  -- header and must be allowed for when comparing against the lines.
  IF abs((v_lines + COALESCE((SELECT round_off FROM "billing"."bills" WHERE id = v_bill_id), 0)) - v_header) > 0.01 THEN
    RAISE EXCEPTION
      'Bill % does not balance: lines total %, header says % (OP-005 §5, phase-05 exit gate 10).',
      v_bill_id, v_lines, v_header
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER "bills_must_balance"
  AFTER INSERT OR UPDATE ON "billing"."bills"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "billing".assert_bill_totals();

-- ── B.4  a finalised bill is immutable ──────────────────────────────────────
--
-- OP-005 §5: "finalized invoices/receipts immutable; corrections through
-- credit/debit notes". The status may still advance as money arrives — that is
-- what `partially_paid` and `paid` are — but the amounts may not move.
CREATE OR REPLACE FUNCTION "billing".refuse_finalized_bill_edit()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.status IN ('finalized', 'partially_paid', 'paid', 'cancelled', 'void') THEN
    IF NEW.gross_amount    IS DISTINCT FROM OLD.gross_amount
    OR NEW.discount_amount IS DISTINCT FROM OLD.discount_amount
    OR NEW.taxable_amount  IS DISTINCT FROM OLD.taxable_amount
    OR NEW.cgst            IS DISTINCT FROM OLD.cgst
    OR NEW.sgst            IS DISTINCT FROM OLD.sgst
    OR NEW.igst            IS DISTINCT FROM OLD.igst
    OR NEW.net_amount      IS DISTINCT FROM OLD.net_amount THEN
      RAISE EXCEPTION
        'Bill % is % and its amounts are immutable. Raise a credit note (OP-005 §5).',
        OLD.id, OLD.status
        USING ERRCODE = 'restrict_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER "bills_immutable_when_finalized"
  BEFORE UPDATE ON "billing"."bills"
  FOR EACH ROW EXECUTE FUNCTION "billing".refuse_finalized_bill_edit();

-- A line on a finalised bill cannot move at all.
CREATE OR REPLACE FUNCTION "billing".refuse_finalized_item_edit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_status "billing"."BillStatus";
BEGIN
  SELECT status INTO v_status FROM "billing"."bills"
   WHERE id = COALESCE(NEW.bill_id, OLD.bill_id);
  IF v_status IN ('finalized', 'partially_paid', 'paid') THEN
    RAISE EXCEPTION
      'Bill % is finalised; its lines are immutable. Raise a credit note (OP-005 §5).',
      COALESCE(NEW.bill_id, OLD.bill_id)
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$;

CREATE TRIGGER "bill_items_immutable_when_finalized"
  BEFORE INSERT OR UPDATE OR DELETE ON "billing"."bill_items"
  FOR EACH ROW EXECUTE FUNCTION "billing".refuse_finalized_item_edit();

-- ── B.5  GST is either intra-state or inter-state, never both ───────────────
--
-- OP-005 §5: "intra-state → CGST+SGST split equally; inter-state → IGST". A row
-- carrying both is a return that will not file, and the two halves of an
-- intra-state split are equal by law rather than by convention.
ALTER TABLE "billing"."bill_items"
  ADD CONSTRAINT "bill_items_gst_mutually_exclusive"
  CHECK (("igst" = 0) OR ("cgst" = 0 AND "sgst" = 0));

ALTER TABLE "billing"."bill_items"
  ADD CONSTRAINT "bill_items_cgst_equals_sgst"
  CHECK ("cgst" = "sgst");

-- An exempt line carries no tax at all; a taxable one is not exempt.
ALTER TABLE "billing"."bill_items"
  ADD CONSTRAINT "bill_items_exempt_carries_no_tax"
  CHECK (NOT "is_exempt" OR ("cgst" = 0 AND "sgst" = 0 AND "igst" = 0 AND "cess" = 0));

ALTER TABLE "billing"."bill_items"
  ADD CONSTRAINT "bill_items_amounts_non_negative"
  CHECK ("gross" >= 0 AND "discount_amount" >= 0 AND "taxable_value" >= 0 AND "net" >= 0);

-- A discount cannot exceed what is being discounted.
ALTER TABLE "billing"."bill_items"
  ADD CONSTRAINT "bill_items_discount_within_gross"
  CHECK ("discount_amount" <= "gross");

ALTER TABLE "billing"."bills"
  ADD CONSTRAINT "bills_amounts_non_negative"
  CHECK ("gross_amount" >= 0 AND "net_amount" >= 0 AND "paid_amount" >= 0);

-- ── B.6  requester ≠ approver, on every discount ────────────────────────────
--
-- OP-005 §5: "approval matrix mandatory; reason codes; requester ≠ approver".
-- The permission split alone would let one person hold both keys; this refuses
-- the specific person, which is the half a role matrix cannot express.
ALTER TABLE "billing"."discount_requests"
  ADD CONSTRAINT "discount_requests_maker_is_not_checker"
  CHECK ("approved_by" IS NULL OR "approved_by" <> "requested_by");

ALTER TABLE "billing"."discount_requests"
  ADD CONSTRAINT "discount_requests_decided_has_approver"
  CHECK (status = 'pending' OR status = 'withdrawn' OR ("decided_at" IS NOT NULL AND "approved_by" IS NOT NULL));

-- ── B.7  a credit note must point at what it reverses ───────────────────────
ALTER TABLE "billing"."invoices"
  ADD CONSTRAINT "invoices_credit_note_references_original"
  CHECK ("doc_type" NOT IN ('credit_note', 'debit_note') OR "original_invoice_id" IS NOT NULL);

-- A B2B invoice needs the recipient's GSTIN, or it is not a B2B invoice.
ALTER TABLE "billing"."invoices"
  ADD CONSTRAINT "invoices_b2b_needs_gstin"
  CHECK (NOT "is_b2b" OR "recipient_gstin" IS NOT NULL);


-- ═════════════════════════════════════════════════════════════════════════════
-- §C. GRANTS, AND "NEVER HARD-DELETED" MADE TRUE
-- ═════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE r record; v_count int := 0;
BEGIN
  FOR r IN
    SELECT n.nspname AS schema_name, c.relname AS table_name, c.oid
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'billing' AND c.relkind IN ('r','p') AND c.relispartition = false
      AND c.relname NOT LIKE '\_prisma%'
      AND NOT has_table_privilege('hms_app', c.oid, 'SELECT')
  LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I.%I TO hms_app', r.schema_name, r.table_name);
    EXECUTE format('GRANT SELECT ON %I.%I TO hms_readonly', r.schema_name, r.table_name);
    v_count := v_count + 1;
  END LOOP;
  RAISE NOTICE 'Granted application DML on % OP-005 table(s)', v_count;
END $$;

-- `CLAUDE.md §4`: "Soft delete only where legally allowed; clinical & financial
-- rows are never hard-deleted." These four are the financial record. A bill is
-- cancelled, an invoice is credit-noted, a line is marked cancelled — and all of
-- them stay, because the register has to add up to what was issued rather than
-- to what survived.
REVOKE DELETE ON "billing"."bills"             FROM hms_app;
REVOKE DELETE ON "billing"."bill_items"        FROM hms_app;
REVOKE DELETE ON "billing"."invoices"          FROM hms_app;
REVOKE DELETE ON "billing"."discount_requests" FROM hms_app;

COMMENT ON TABLE "billing"."bills" IS
  'The master bill. Never deleted: cancellation is a status and the row stays, because a register that only holds surviving bills does not reconcile to what was issued (CLAUDE.md §4, OP-005 §5).';

COMMENT ON TABLE "billing"."invoices" IS
  'GST documents, gapless per series per financial year. A cancelled invoice keeps its number and appears in the register as cancelled — a reused number is a return that will not file.';

COMMENT ON TABLE "billing"."bill_items" IS
  'Bill lines, idempotent on (bill_id, source_module, source_ref_id). That index is phase-05 exit gate 2: replay a charge event three times and the bill is unchanged.';
